#!/usr/bin/env node
/**
 * Generate the real product fragments embedded by the LiczMat Pro page.
 *
 * The pages are read from the built repository. Run `node scripts/build.mjs` before this
 * developer tool when those pages are stale or missing (the generator never runs it).
 */

import { execFile } from "node:child_process";
import { mkdtemp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import http from "node:http";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath, pathToFileURL } from "node:url";
import { PRO_COPY } from "../src/pro-copy.mjs";
import { DEFAULT_CURRENCY, MONEY_LOCALE } from "../src/currency.mjs";
import { route } from "../src/ia.mjs";
import { LANGS } from "../src/site.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "src", "pro-samples");
const GENERATED = "<!-- generated by scripts/pro-samples.mjs, do not edit -->";
const execFileAsync = promisify(execFile);
const requested = (() => {
  const at = process.argv.indexOf("--lang");
  if (at < 0) return LANGS;
  if (!process.argv[at + 1] || !LANGS.includes(process.argv[at + 1])) {
    throw new Error(`Usage: node scripts/pro-samples.mjs [--lang ${LANGS.join("|")}]`);
  }
  return [process.argv[at + 1]];
})();

const VAT = { pl: 23, uk: 20, de: 19, en: 0, cs: 21, sk: 23, ro: 21, hr: 25, sr: 20, it: 22, nl: 21, es: 21, fr: 20 };
const PRICES = {
  PLN: [8900, 4200, 3100, 8000, 12000], EUR: [2100, 1000, 750, 2000, 2800],
  USD: [2300, 1100, 800, 2200, 3100], UAH: [100000, 48000, 36000, 96000, 134000],
  CZK: [48000, 23000, 17000, 46000, 64000], RON: [10500, 5000, 3800, 10000, 14000],
  RSD: [230000, 110000, 83000, 220000, 310000],
};
const requiredCopy = ["x_firm", "x_firm_street", "x_firm_postal", "x_firm_city", "x_firm_phone", "x_firm_email", "x_client", "x_street", "x_postal", "x_city", "x_phone", "x_project", "x_project2", "x_project3", "x_project4", "x_client2", "x_client3", "x_quote", "x_room", "x_mat1", "x_mat2", "x_mat3", "x_other", "x_labour", "x_unit_pack", "x_unit_bag"];

for (const lang of requested) {
  const missing = requiredCopy.filter((key) => !PRO_COPY[lang]?.[key]);
  if (missing.length) throw new Error(`PRO_COPY.${lang} is not ready; missing: ${missing.join(", ")}`);
  if (!PRICES[DEFAULT_CURRENCY[lang]]) throw new Error(`No sample prices for ${lang} currency ${DEFAULT_CURRENCY[lang]}`);
}

let playwright;
try {
  const dir = process.env.LM_PLAYWRIGHT || "C:/Projekty/lm-test/node_modules/playwright";
  playwright = await import(pathToFileURL(path.join(dir, "index.mjs")).href);
} catch (error) {
  throw new Error(`Playwright is required to generate Pro samples. Set LM_PLAYWRIGHT to its package directory. (${error.message})`);
}

const pagePath = (id, lang) => route(id)?.path(lang);
for (const lang of requested) for (const id of ["quotes", "calendar"]) {
  const rel = pagePath(id, lang);
  const file = path.join(ROOT, rel.replace(/^\//, ""), "index.html");
  try { await stat(file); } catch {
    throw new Error(`Built page is missing: ${file}. Run node scripts/build.mjs before scripts/pro-samples.mjs.`);
  }
}

const totalsFor = (lang) => {
  const currencyCode = DEFAULT_CURRENCY[lang];
  const [p1, p2, p3, other, labourRate] = PRICES[currencyCode];
  const materials = 7 * p1 + 5 * p2 + 2 * p3;
  const labour = Math.round(6.2 * labourRate);
  const subtotal = materials + other + labour;
  const margin = Math.round(subtotal * 0.1);
  const net = subtotal + margin;
  const vat = Math.round(net * VAT[lang] / 100);
  return { currencyCode, prices: [p1, p2, p3, other, labourRate], materials, other, labour, subtotal, marginPct: 10, margin, net, vatPct: VAT[lang] || null, vat, gross: net + vat, mixed: false, materialsText: "", otherText: "" };
};
const sync = (at) => ({ createdAt: at, updatedAt: at, deletedAt: null, schemaVersion: 1 });
const sampleData = (lang) => {
  const x = PRO_COPY[lang];
  const totals = totalsFor(lang);
  const [p1, p2, p3, other, labourRate] = totals.prices;
  const T0 = Date.UTC(2026, 8, 20);
  const line = (id, name, units, unit, minor, category, manual = false) => ({ id, projectId: "p1", name, calculationType: "SURFACE_COVERAGE", materialCategory: category, requiredUnits: units, unitLabel: unit, totalCostMinor: minor, wastePercentage: 0, wasteCostMinor: 0, currencyCode: totals.currencyCode, inputJson: JSON.stringify(manual ? { manual: true } : { area: "6.2" }), ...sync(T0) });
  const project = (id, name, dueDate, status, clientId, color = "") => ({ id, name, archived: false, clientId, status, dueDate, valueMinor: null, currencyCode: "", note: "", color, ...sync(T0) });
  const client = (id, name, address, phone = "") => ({ id, name, phone, email: "", address, note: "", projectIds: id === "c1" ? ["p1"] : [], archived: false, ...sync(T0) });
  const ws = {
    projects: [project("p1", x.x_project, "2026-10-14", "active", "c1", "blue"), project("p2", x.x_project2, "2026-10-07", "new", "c2"), project("p3", x.x_project3, "2026-10-21", "new", "c3", "amber"), project("p4", x.x_project4, "2026-10-28", "new", "c2", "violet")],
    rooms: [{ id: "r1", projectId: "p1", name: x.x_room, lengthM: 2.5, widthM: 2.48, heightM: 2.5, ...sync(T0) }],
    estimations: [line("e1", x.x_mat1, 7, x.x_unit_pack, 7 * p1, "TILES"), line("e2", x.x_mat2, 5, x.x_unit_bag, 5 * p2, "ADHESIVE"), line("e3", x.x_mat3, 2, x.x_unit_bag, 2 * p3, "GROUT"), line("e4", x.x_other, 1, "", other, "OTHER", true)], shoppingItems: [],
  };
  const crm = { clients: [client("c1", x.x_client, `${x.x_street}, ${x.x_city}`, x.x_phone), client("c2", x.x_client2, ""), client("c3", x.x_client3, "")], quotes: [{ id: "q1", number: "W/10/2026", name: x.x_quote, projectId: "p1", labour: [{ id: "l1", name: x.x_labour, quantity: 6.2, unit: "m²", amountMinor: totals.labour }], marginPct: 10, vatPct: VAT[lang] || null, note: "", currencyCode: totals.currencyCode, validUntil: "2026-10-17", ...sync(Date.UTC(2026, 9, 3)) }] };
  const quote = { lang, company: { name: x.x_firm, street: x.x_firm_street, postalCode: x.x_firm_postal, city: x.x_firm_city, nip: "", phone: x.x_firm_phone, email: x.x_firm_email, www: "", bankAccount: "", logo: "" }, quote: { number: "W/10/2026", createdAt: Date.UTC(2026, 9, 3), validUntil: "2026-10-17", note: "" }, client: { name: x.x_client, phone: x.x_phone, email: "", street: x.x_street, postalCode: x.x_postal, city: x.x_city }, projectName: x.x_project, materialRows: [{ name: x.x_mat1, qtyText: `7 ${x.x_unit_pack}`, unitPriceMinor: p1, valueMinor: 7 * p1 }, { name: x.x_mat2, qtyText: `5 ${x.x_unit_bag}`, unitPriceMinor: p2, valueMinor: 5 * p2 }, { name: x.x_mat3, qtyText: `2 ${x.x_unit_bag}`, unitPriceMinor: p3, valueMinor: 2 * p3 }], otherRows: [{ name: x.x_other, qtyText: "1", unitPriceMinor: other, valueMinor: other }], labourRows: [{ name: x.x_labour, qtyText: `${new Intl.NumberFormat(MONEY_LOCALE[lang]).format(6.2)} m²`, unitPriceMinor: labourRate, valueMinor: totals.labour }], totals, visibility: { forBlock: true } };
  return { ws, crm, quote };
};

const TYPES = { ".html": "text/html; charset=utf-8", ".css": "text/css", ".js": "text/javascript", ".mjs": "text/javascript", ".svg": "image/svg+xml", ".png": "image/png", ".webp": "image/webp" };
const server = http.createServer(async (req, res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url, "http://localhost").pathname);
    let file = path.resolve(ROOT, `.${pathname}`);
    if (!file.startsWith(ROOT + path.sep) && file !== ROOT) throw new Error("outside root");
    if ((await stat(file)).isDirectory()) file = path.join(file, "index.html");
    res.writeHead(200, { "content-type": TYPES[path.extname(file)] || "application/octet-stream" });
    res.end(await readFile(file));
  } catch { res.writeHead(404); res.end("not found"); }
});
await new Promise((resolve, reject) => server.listen(0, "127.0.0.1", (error) => error ? reject(error) : resolve()));
const base = `http://127.0.0.1:${server.address().port}`;

const cleanFragment = async (page, selector, kind) => page.$eval(selector, (source, kind) => {
  const root = document.createElement("div");
  if (kind === "editor") {
    root.className = "pro-editor";
    // A clone forgets which option a <select> had chosen (it falls back to the first one,
    // "bez VAT"), so the live values are written down before anything is copied.
    source.querySelectorAll("select").forEach((el) => el.setAttribute("data-pro-text", el.selectedOptions[0]?.textContent || ""));
    source.querySelectorAll("input").forEach((el) => el.setAttribute("data-pro-text", el.hidden ? "" : el.value));
    const sections = [...source.querySelectorAll("section.dash-sec")];
    const materials = sections.find((s) => s.querySelector("#quo-material-list"));
    const summary = sections.find((s) => s.classList.contains("quo-summary-card"));
    root.append(materials.cloneNode(true), summary.cloneNode(true));
    root.querySelector("#quo-hidden-wrap")?.remove();
    root.querySelector("#quo-own-material-list")?.remove();
    root.querySelector(".quo-own-picker")?.remove();
    root.querySelector("#quo-materials-form")?.remove();
    root.querySelectorAll("button,.row-actions,form").forEach((e) => e.remove());
    for (const input of root.querySelectorAll("input,select")) {
      const span = document.createElement("span"); span.className = "pro-field";
      const text = input.getAttribute("data-pro-text") || "";
      if (!text) { input.remove(); continue; }
      span.textContent = text;
      input.replaceWith(span);
    }
  } else if (kind === "calendar") {
    root.className = "pro-calendar";
    root.append(source.cloneNode(true));
    root.querySelector("#cal-add-toggle")?.closest("p")?.remove();
    root.querySelector("#cal-add-form")?.remove();
    const month = root.querySelector("#cal-month-toggle");
    if (month) { const text = document.createTextNode(month.firstChild?.textContent || month.textContent); month.replaceWith(text); }
    root.querySelector("#cal-today")?.remove();
    root.querySelectorAll(".cal-nav button").forEach((b) => b.disabled = true);
    root.querySelectorAll(".cal-day").forEach((b) => { const d = document.createElement("div"); for (const a of [...b.attributes]) if (a.name === "class" || a.name === "data-day") d.setAttribute(a.name, a.value); d.innerHTML = b.innerHTML; b.replaceWith(d); });
  } else {
    root.append(source.cloneNode(true));
    root.firstElementChild.removeAttribute("hidden");
    root.querySelectorAll('img[src^="data:"]').forEach((img) => { img.src = img.classList.contains("qdoc-foot-mark") ? "/assets/logo-mark.svg" : "/assets/qr-liczmat.svg"; });
    root.querySelectorAll("img").forEach((img) => { if (!img.hasAttribute("alt")) img.alt = ""; });
  }
  root.querySelectorAll("a").forEach((a) => { const span = document.createElement("span"); if (a.className) span.className = a.className; span.innerHTML = a.innerHTML; a.replaceWith(span); });
  root.querySelectorAll("h1,h2,h3,h4").forEach((h) => { const p = document.createElement("p"); p.className = `pro-sample-h pro-sample-h${h.tagName.slice(1)}${h.className ? ` ${h.className}` : ""}`; p.innerHTML = h.innerHTML; h.replaceWith(p); });
  root.querySelectorAll("*").forEach((el) => ["id", "for", "aria-controls", "aria-describedby", "aria-labelledby", "name"].forEach((a) => el.removeAttribute(a)));
  const html = kind === "quote" ? root.innerHTML : root.outerHTML;
  if (/[—–]/u.test(html)) throw new Error(`${kind} fragment contains a forbidden dash`);
  return html;
}, kind);

const tmp = await mkdtemp(path.join(os.tmpdir(), "liczmat-pro-samples-"));
let browser;
try {
  await mkdir(OUT, { recursive: true });
  await execFileAsync(process.execPath, [path.join(ROOT, "scripts", "export-quote-sheet.mjs"), tmp], { cwd: ROOT });
  browser = await playwright.chromium.launch();
  for (const lang of requested) {
    const data = sampleData(lang);
    const context = await browser.newContext({ viewport: { width: 1400, height: 1000 }, colorScheme: "light" });
    await context.route("**", (r) => r.request().url().startsWith(base) || r.request().url().startsWith("file:") ? r.continue() : r.abort());
    await context.addInitScript(([lang, ws, crm]) => { localStorage.setItem("materio-lang", lang); localStorage.setItem("materio-lang-banner-dismissed", "1"); localStorage.setItem("liczmat-signed-in", "pro"); localStorage.setItem("materio-workspace-v1", ws); localStorage.setItem("liczmat-crm-v1", crm); localStorage.setItem("liczmat-consent", '{"v":1,"analytics":false}'); }, [lang, JSON.stringify(data.ws), JSON.stringify(data.crm)]);
    const page = await context.newPage();
    await page.goto(pathToFileURL(path.join(tmp, `sheet-${lang}.html`)).href);
    if (!await page.evaluate((json) => window.lmRenderQuote(json), JSON.stringify(data.quote))) throw new Error(`${lang}: quote renderer failed`);
    await page.waitForFunction(() => document.documentElement.dataset.lmReady === "1");
    const quote = await cleanFragment(page, "#ws-pdf-doc", "quote");

    await page.clock.install({ time: new Date("2026-10-04T12:00:00+02:00") });
    await page.goto(base + pagePath("quotes", lang) + "?id=q1", { waitUntil: "load" });
    await page.waitForSelector("html[data-quotes-ready]");
    const editor = await cleanFragment(page, "#quo-detail", "editor");
    await page.goto(base + pagePath("calendar", lang), { waitUntil: "load" });
    await page.waitForSelector(".cal-wrap [data-day='2026-10-14']");
    await page.locator(".cal-wrap [data-day='2026-10-14']").filter({ visible: true }).first().click();
    const calendar = await cleanFragment(page, ".cal-wrap", "calendar");
    for (const [kind, html] of Object.entries({ quote, editor, calendar })) {
      const file = path.join(OUT, `${kind}-${lang}.html`);
      await writeFile(file, `${GENERATED}\n${html}\n`, "utf8");
      console.log(`${path.relative(ROOT, file)} ${(await stat(file)).size} bytes`);
    }
    await context.close();
  }
} finally {
  await browser?.close(); server.close(); await rm(tmp, { recursive: true, force: true });
}
