#!/usr/bin/env node
import { readFileSync } from "node:fs";
import { LANGS, urlLiczmatPro, URL_APP } from "../src/site.mjs";
import { PRO_COPY, PRO_COPY_KEYS } from "../src/pro-copy.mjs";

let passed = 0;
const failed = [];
const check = (name, ok) => ok ? passed++ : failed.push(name);
const read = (file) => readFileSync(new URL(`../${file}`, import.meta.url), "utf8");

check("13 language blocks", Object.keys(PRO_COPY).length === 13 && LANGS.every((lang) => PRO_COPY[lang]));
for (const lang of LANGS) {
  check(`${lang}: complete copy`, PRO_COPY_KEYS.every((key) => String(PRO_COPY[lang][key] || "").trim()));
  const html = read(urlLiczmatPro(lang).replace(/^\//, "") + "index.html");
  check(`${lang}: page exists`, html.includes(`<html lang="${lang}"`));
  const flat = html.replace(/&nbsp;|&#160;|\u00a0/g, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");
  check(`${lang}: copy is printed`, ["lead", "q_h", "c_h", "p_h", "t_h", "b_h"].every((key) => flat.includes(PRO_COPY[lang][key].replace(/\s+/g, " "))));
  check(`${lang}: three levels`, (html.match(/class="pro-plan(?: |")/g) || []).length === 3);
  check(`${lang}: real samples`, html.includes('class="qdoc') && html.includes('class="pro-editor') && html.includes('class="pro-calendar'));
  check(`${lang}: sample comments stripped`, !html.includes("generated by scripts/pro-samples.mjs"));
  check(`${lang}: comparison table`, html.includes('class="pro-table"') && (html.match(/class="pro-group"/g) || []).length === 5);
  check(`${lang}: checkout routes`, html.includes(`${URL_APP}?buy=monthly`) && html.includes(`${URL_APP}?buy=yearly`));
  check(`${lang}: no breadcrumb`, !html.includes('"BreadcrumbList"'));
}

const build = read("scripts/build.mjs");
check("build validates PRO_COPY", build.includes("PRO_COPY_KEYS") && build.includes("pro/${lang}: no ${key}"));
check("meta comes from PRO_COPY", build.includes("description: PRO_COPY[lang].meta"));
const paywall = read("assets/paywall.js");
check("paywall formats zero", paywall.includes("lmMoneyMinor(0, code)"));
check("paywall hides page CTAs for Pro", paywall.includes('querySelectorAll("[data-pro-buy]")'));
check("period switch is wired", paywall.includes("data-pro-set") && paywall.includes("data-pro-period"));

if (failed.length) {
  console.error(`${failed.length} checks FAILED:\n${failed.map((x) => `  FAIL ${x}`).join("\n")}`);
  process.exit(1);
}
console.log(`propage: ${passed}/${passed} checks pass`);
