/* LiczMat website — the words on the unit converter page, in ten languages.
 *
 * Session 57, item C1 of the parity audit. It sits in src/ rather than in
 * assets/i18n-pages.js for the reason src/calc-seo.mjs does, and the measurement is the
 * same one: every page on this site downloads assets/i18n.<lang>.js, and 23 keys per
 * language of copy that only the build and a reader of the finished HTML ever see cost
 * about 1.4 kB on every page load for nothing. It is not a small number where it lands —
 * /app/ is the heaviest page on the site and it went 1 kB past its budget in
 * scripts/test-perf.mjs the moment these keys were in the bundle, which is what a budget
 * with no margin in it is for.
 *
 * The page can afford this because it is localized: it has one URL per language and the
 * language switcher navigates, so nothing on it is ever re-translated in the browser. The
 * one string that IS needed at runtime stays in the dictionary — `conv_bad`, which
 * assets/converter.js writes when the field holds no number.
 *
 * ONE KEY IS NOT HERE. `convpage_title` stayed in assets/i18n-pages.js, because the
 * footer of every page on the site carries a link to this one and src/template.mjs takes
 * that label from the route's `footer.key` — a dictionary key. Moving it here made all 383
 * footers print the literal word "convpage_title", which is the session-41 defect exactly:
 * every key present, every URL resolving, every suite green, and a word nobody wrote on
 * every page of the site. §7 of scripts/test-converter.mjs is the net that caught it.
 *
 * WHAT IS COPIED AND WHAT IS WRITTEN. The title and the eleven category names are the
 * app's own strings (`converter_title` and `conv_cat_*` in res/values*), as are `cat`, `value`,
 * `from` and `swap`. One module may not be called two different things on the two
 * products — session 53 wrote that rule down when the app took the website's `cal_*`
 * strings, and this is the same rule running the other way. The rest — the lead, the meta
 * description, the note about base units and the one about temperature — is written here,
 * because the app has no page to say it on.
 *
 * scripts/test-copy.mjs reads this file alongside the dictionaries, so the six stop-slop
 * rules cover it exactly as they cover everything else a visitor can read.
 */

export const CONV_COPY = {
  pl: {
    convpage_lead: "Przelicz długość, powierzchnię, objętość, masę, temperaturę, ciśnienie i moc. Liczy przeglądarka, bez konta.",
    convpage_meta: "Konwerter jednostek online: metry i cale, metry kwadratowe i stopy, litry, kilogramy, stopnie, bary, kilowaty. Jedenaście kategorii, bez rejestracji.",
    conv_hub_d: "Metry, cale, litry, kilogramy, stopnie i dalsze — jedenaście kategorii jednostek.",
    conv_open: "Otwórz konwerter",
    conv_cat: "Wybierz kategorię",
    conv_value: "Wartość",
    conv_from: "Z",
    conv_to: "Na",
    conv_swap: "Zamień",
    conv_units_t: "Co przelicza",
    conv_how_d: "Każda kategoria ma jednostkę bazową. Wartość przeliczamy na nią, a z niej na jednostkę docelową, więc każda para jednostek działa tak samo.",
    conv_temp_d: "Temperatura jest wyjątkiem: skale różnią się też zerem, więc °C, °F i K przeliczamy przez stopnie Celsjusza, a nie mnożnikiem.",
    conv_c_length: "Długość",
    conv_c_area: "Powierzchnia",
    conv_c_volume: "Objętość",
    conv_c_mass: "Masa",
    conv_c_temperature: "Temperatura",
    conv_c_speed: "Prędkość",
    conv_c_time: "Czas",
    conv_c_pressure: "Ciśnienie",
    conv_c_energy: "Energia",
    conv_c_power: "Moc",
    conv_c_data: "Dane",
  },
  uk: {
    convpage_lead: "Переведіть довжину, площу, обʼєм, масу, температуру, тиск і потужність. Рахує браузер, без облікового запису.",
    convpage_meta: "Конвертер одиниць онлайн: метри й дюйми, квадратні метри й фути, літри, кілограми, градуси, бари, кіловати. Одинадцять категорій, без реєстрації.",
    conv_hub_d: "Метри, дюйми, літри, кілограми, градуси й інше — одинадцять категорій одиниць.",
    conv_open: "Відкрити конвертер",
    conv_cat: "Виберіть категорію",
    conv_value: "Значення",
    conv_from: "З",
    conv_to: "На",
    conv_swap: "Поміняти",
    conv_units_t: "Що переводить",
    conv_how_d: "Кожна категорія має базову одиницю. Значення переводимо в базову, а з неї — у цільову, тому будь-яка пара одиниць працює однаково.",
    conv_temp_d: "Температура — виняток: шкали відрізняються ще й нулем, тому °C, °F і K переводимо через градуси Цельсія, а не множником.",
    conv_c_length: "Довжина",
    conv_c_area: "Площа",
    conv_c_volume: "Обʼєм",
    conv_c_mass: "Маса",
    conv_c_temperature: "Температура",
    conv_c_speed: "Швидкість",
    conv_c_time: "Час",
    conv_c_pressure: "Тиск",
    conv_c_energy: "Енергія",
    conv_c_power: "Потужність",
    conv_c_data: "Дані",
  },
  de: {
    convpage_lead: "Rechne Länge, Fläche, Volumen, Masse, Temperatur, Druck und Leistung um. Der Browser rechnet, ohne Konto.",
    convpage_meta: "Einheitenumrechner online: Meter und Zoll, Quadratmeter und Fuß, Liter, Kilogramm, Grad, Bar, Kilowatt. Elf Kategorien, ohne Anmeldung.",
    conv_hub_d: "Meter, Zoll, Liter, Kilogramm, Grad und mehr — elf Kategorien von Einheiten.",
    conv_open: "Umrechner öffnen",
    conv_cat: "Kategorie wählen",
    conv_value: "Wert",
    conv_from: "Von",
    conv_to: "Nach",
    conv_swap: "Tauschen",
    conv_units_t: "Was umgerechnet wird",
    conv_how_d: "Jede Kategorie hat eine Basiseinheit. Der Wert geht in die Basiseinheit und von dort in die Zieleinheit, deshalb funktioniert jedes Paar gleich.",
    conv_temp_d: "Temperatur ist die Ausnahme: die Skalen unterscheiden sich auch im Nullpunkt, deshalb laufen °C, °F und K über Grad Celsius statt über einen Faktor.",
    conv_c_length: "Länge",
    conv_c_area: "Fläche",
    conv_c_volume: "Volumen",
    conv_c_mass: "Masse",
    conv_c_temperature: "Temperatur",
    conv_c_speed: "Geschwindigkeit",
    conv_c_time: "Zeit",
    conv_c_pressure: "Druck",
    conv_c_energy: "Energie",
    conv_c_power: "Leistung",
    conv_c_data: "Daten",
  },
  en: {
    convpage_lead: "Convert length, area, volume, mass, temperature, pressure and power. Your browser does it, with no account.",
    convpage_meta: "Unit converter online: metres and inches, square metres and feet, litres, kilograms, degrees, bars, kilowatts. Eleven categories, no sign-up.",
    conv_hub_d: "Metres, inches, litres, kilograms, degrees and more — eleven categories of units.",
    conv_open: "Open the converter",
    conv_cat: "Choose category",
    conv_value: "Value",
    conv_from: "From",
    conv_to: "To",
    conv_swap: "Swap",
    conv_units_t: "What it converts",
    conv_how_d: "Every category has a base unit. The value goes into the base unit and from there into the target one, so any pair of units works the same way.",
    conv_temp_d: "Temperature is the exception: the scales differ in their zero as well, so °C, °F and K go through degrees Celsius instead of a factor.",
    conv_c_length: "Length",
    conv_c_area: "Area",
    conv_c_volume: "Volume",
    conv_c_mass: "Mass",
    conv_c_temperature: "Temperature",
    conv_c_speed: "Speed",
    conv_c_time: "Time",
    conv_c_pressure: "Pressure",
    conv_c_energy: "Energy",
    conv_c_power: "Power",
    conv_c_data: "Data",
  },
  cs: {
    convpage_lead: "Převeďte délku, plochu, objem, hmotnost, teplotu, tlak a výkon. Počítá prohlížeč, bez účtu.",
    convpage_meta: "Převodník jednotek online: metry a palce, metry čtvereční a stopy, litry, kilogramy, stupně, bary, kilowatty. Jedenáct kategorií, bez registrace.",
    conv_hub_d: "Metry, palce, litry, kilogramy, stupně a další — jedenáct kategorií jednotek.",
    conv_open: "Otevřít převodník",
    conv_cat: "Vyberte kategorii",
    conv_value: "Hodnota",
    conv_from: "Z",
    conv_to: "Na",
    conv_swap: "Prohodit",
    conv_units_t: "Co převádí",
    conv_how_d: "Každá kategorie má základní jednotku. Hodnotu převedeme na ni a z ní na cílovou, takže každá dvojice jednotek funguje stejně.",
    conv_temp_d: "Teplota je výjimka: stupnice se liší i nulou, takže °C, °F a K převádíme přes stupně Celsia, ne násobkem.",
    conv_c_length: "Délka",
    conv_c_area: "Plocha",
    conv_c_volume: "Objem",
    conv_c_mass: "Hmotnost",
    conv_c_temperature: "Teplota",
    conv_c_speed: "Rychlost",
    conv_c_time: "Čas",
    conv_c_pressure: "Tlak",
    conv_c_energy: "Energie",
    conv_c_power: "Výkon",
    conv_c_data: "Data",
  },
  sk: {
    convpage_lead: "Preveďte dĺžku, plochu, objem, hmotnosť, teplotu, tlak a výkon. Počíta prehliadač, bez účtu.",
    convpage_meta: "Prevodník jednotiek online: metre a palce, štvorcové metre a stopy, litre, kilogramy, stupne, bary, kilowatty. Jedenásť kategórií, bez registrácie.",
    conv_hub_d: "Metre, palce, litre, kilogramy, stupne a ďalšie — jedenásť kategórií jednotiek.",
    conv_open: "Otvoriť prevodník",
    conv_cat: "Vyberte kategóriu",
    conv_value: "Hodnota",
    conv_from: "Z",
    conv_to: "Na",
    conv_swap: "Vymeniť",
    conv_units_t: "Čo prevádza",
    conv_how_d: "Každá kategória má základnú jednotku. Hodnotu prevedieme na ňu a z nej na cieľovú, takže každá dvojica jednotiek funguje rovnako.",
    conv_temp_d: "Teplota je výnimka: stupnice sa líšia aj nulou, takže °C, °F a K prevádzame cez stupne Celzia, nie násobkom.",
    conv_c_length: "Dĺžka",
    conv_c_area: "Plocha",
    conv_c_volume: "Objem",
    conv_c_mass: "Hmotnosť",
    conv_c_temperature: "Teplota",
    conv_c_speed: "Rýchlosť",
    conv_c_time: "Čas",
    conv_c_pressure: "Tlak",
    conv_c_energy: "Energia",
    conv_c_power: "Výkon",
    conv_c_data: "Dáta",
  },
  ro: {
    convpage_lead: "Convertește lungimea, suprafața, volumul, masa, temperatura, presiunea și puterea. Calculează browserul, fără cont.",
    convpage_meta: "Convertor de unități online: metri și țoli, metri pătrați și picioare, litri, kilograme, grade, bari, kilowați. Unsprezece categorii, fără cont.",
    conv_hub_d: "Metri, țoli, litri, kilograme, grade și altele — unsprezece categorii de unități.",
    conv_open: "Deschide convertorul",
    conv_cat: "Alege categoria",
    conv_value: "Valoare",
    conv_from: "Din",
    conv_to: "În",
    conv_swap: "Schimbă",
    conv_units_t: "Ce convertește",
    conv_how_d: "Fiecare categorie are o unitate de bază. Valoarea trece prin ea spre unitatea aleasă, așa că orice pereche de unități funcționează la fel.",
    conv_temp_d: "Temperatura este excepția: scările diferă și prin zero, așa că °C, °F și K trec prin grade Celsius, nu printr-un factor.",
    conv_c_length: "Lungime",
    conv_c_area: "Suprafață",
    conv_c_volume: "Volum",
    conv_c_mass: "Masă",
    conv_c_temperature: "Temperatură",
    conv_c_speed: "Viteză",
    conv_c_time: "Timp",
    conv_c_pressure: "Presiune",
    conv_c_energy: "Energie",
    conv_c_power: "Putere",
    conv_c_data: "Date",
  },
  hr: {
    convpage_lead: "Pretvori duljinu, površinu, volumen, masu, temperaturu, tlak i snagu. Računa preglednik, bez korisničkog računa.",
    convpage_meta: "Pretvarač jedinica online: metri i inči, četvorni metri i stope, litre, kilogrami, stupnjevi, bari, kilovati. Jedanaest kategorija, bez registracije.",
    conv_hub_d: "Metri, inči, litre, kilogrami, stupnjevi i više — jedanaest kategorija jedinica.",
    conv_open: "Otvori pretvarač",
    conv_cat: "Odaberi kategoriju",
    conv_value: "Vrijednost",
    conv_from: "Iz",
    conv_to: "U",
    conv_swap: "Zamijeni",
    conv_units_t: "Što pretvara",
    conv_how_d: "Svaka kategorija ima osnovnu jedinicu. Vrijednost ide u nju pa iz nje u odabranu jedinicu, pa svaki par jedinica radi jednako.",
    conv_temp_d: "Temperatura je iznimka: ljestvice se razlikuju i po nuli, pa °C, °F i K idu preko Celzijevih stupnjeva, a ne preko faktora.",
    conv_c_length: "Duljina",
    conv_c_area: "Površina",
    conv_c_volume: "Volumen",
    conv_c_mass: "Masa",
    conv_c_temperature: "Temperatura",
    conv_c_speed: "Brzina",
    conv_c_time: "Vrijeme",
    conv_c_pressure: "Tlak",
    conv_c_energy: "Energija",
    conv_c_power: "Snaga",
    conv_c_data: "Podaci",
  },
  sr: {
    convpage_lead: "Pretvori dužinu, površinu, zapreminu, masu, temperaturu, pritisak i snagu. Računa pregledač, bez naloga.",
    convpage_meta: "Konvertor jedinica onlajn: metri i inči, kvadratni metri i stope, litri, kilogrami, stepeni, bari, kilovati. Jedanaest kategorija, bez registracije.",
    conv_hub_d: "Metri, inči, litri, kilogrami, stepeni i još — jedanaest kategorija jedinica.",
    conv_open: "Otvori konvertor",
    conv_cat: "Izaberi kategoriju",
    conv_value: "Vrednost",
    conv_from: "Iz",
    conv_to: "U",
    conv_swap: "Zameni",
    conv_units_t: "Šta pretvara",
    conv_how_d: "Svaka kategorija ima osnovnu jedinicu. Vrednost ide u nju pa iz nje u izabranu jedinicu, pa svaki par jedinica radi isto.",
    conv_temp_d: "Temperatura je izuzetak: skale se razlikuju i po nuli, pa °C, °F i K idu preko Celzijusovih stepeni, a ne preko faktora.",
    conv_c_length: "Dužina",
    conv_c_area: "Površina",
    conv_c_volume: "Zapremina",
    conv_c_mass: "Masa",
    conv_c_temperature: "Temperatura",
    conv_c_speed: "Brzina",
    conv_c_time: "Vreme",
    conv_c_pressure: "Pritisak",
    conv_c_energy: "Energija",
    conv_c_power: "Snaga",
    conv_c_data: "Podaci",
  },
  ru: {
    convpage_lead: "Переведите длину, площадь, объём, массу, температуру, давление и мощность. Считает браузер, без аккаунта.",
    convpage_meta: "Конвертер единиц онлайн: метры и дюймы, квадратные метры и футы, литры, килограммы, градусы, бары, киловатты. Одиннадцать категорий, без регистрации.",
    conv_hub_d: "Метры, дюймы, литры, килограммы, градусы и другое — одиннадцать категорий единиц.",
    conv_open: "Открыть конвертер",
    conv_cat: "Выберите категорию",
    conv_value: "Значение",
    conv_from: "Из",
    conv_to: "В",
    conv_swap: "Поменять",
    conv_units_t: "Что переводит",
    conv_how_d: "У каждой категории есть базовая единица. Значение переводим в неё, а из неё — в целевую, поэтому любая пара единиц работает одинаково.",
    conv_temp_d: "Температура — исключение: шкалы отличаются ещё и нулём, поэтому °C, °F и K переводим через градусы Цельсия, а не множителем.",
    conv_c_length: "Длина",
    conv_c_area: "Площадь",
    conv_c_volume: "Объём",
    conv_c_mass: "Масса",
    conv_c_temperature: "Температура",
    conv_c_speed: "Скорость",
    conv_c_time: "Время",
    conv_c_pressure: "Давление",
    conv_c_energy: "Энергия",
    conv_c_power: "Мощность",
    conv_c_data: "Данные",
  },
};

/** Every key the converter page spends, so the build can check all ten languages. */
export const CONV_COPY_KEYS = Object.keys(CONV_COPY.pl);
