/* LiczMat website — the words on the "my materials" page, in ten languages.
 *
 * Session 59, item C6 of the parity audit. It sits in src/ rather than in
 * assets/i18n-pages.js for the reason src/conv-copy.mjs and src/calc-seo.mjs do, and the
 * measurement is the same: every page on this site downloads assets/i18n.<lang>.js, and
 * 27 keys per language of copy that only the build and a reader of the finished HTML ever
 * see is about 1.6 kB on every page load for nothing. /app/ is the heaviest page on the
 * site and had 0.7 kB of gzipped headroom before this session started, which is what a
 * budget with no margin in it is for.
 *
 * The page can afford this because it is localized: one URL per language, and the language
 * switcher navigates rather than re-translating the DOM. What the browser writes at
 * runtime — the list, the trend, the undo strip — stays in the dictionary, under the same
 * `omat_` prefix, because those strings are chosen after the page has been served.
 *
 * ONE KEY IS NOT HERE, for the reason `convpage_title` is not in src/conv-copy.mjs:
 * `omatpage_title` is this route's `footer.key` in src/ia.mjs, so the footer of all 393
 * pages takes its label from the dictionary. Moving it here would print the literal word
 * "omatpage_title" in every footer, in every language, with every suite still green —
 * session 41's defect, and session 57 walked into it a second time with a different key.
 *
 * WHAT IS COPIED AND WHAT IS WRITTEN. The five `omat_app_*` labels are the app's own
 * `MaterialApplication.labelPl` and its nine translations: one concept may not be called
 * two things on the two products, which is the rule session 53 wrote down when the app
 * took this site's `cal_*` strings. The measurement labels are the field labels the
 * calculators already use. The rest — the lead, the meta description, and the two notes
 * saying what the history does and does not record — is written here, because the app has
 * no page to say it on.
 *
 * scripts/test-copy.mjs reads this file alongside the dictionaries, so the six stop-slop
 * rules cover it exactly as they cover everything else a visitor can read.
 */

export const OMAT_COPY = {
  pl: {
    omatpage_lead: "Zapisz materiał, którego nie ma w katalogu, razem z ceną u twojego dostawcy. Każda kolejna cena zostaje w historii.",
    omatpage_meta: "Własne materiały i historia cen na koncie LiczMat.",
    omat_add_t: "Nowy materiał",
    omat_name: "Nazwa",
    omat_name_ph: "np. Gres od Kowalskiego 60×60",
    omat_cat: "Kategoria",
    omat_app: "Do czego służy",
    omat_app_WALL_FLOOR_COVERING: "Okładziny ścian i podłóg",
    omat_app_DRYWALL_BOARDING: "Zabudowa płytami G-K",
    omat_app_COATING: "Materiały kryjące",
    omat_app_PANEL_CUTTING: "Rozkrój płyt i arkuszy",
    omat_app_LINEAR_STOCK: "Profile, listwy, rury, pręty",
    omat_app_OTHER: "Pozostałe",
    omat_purpose: "Do czego służy: opis",
    omat_purpose_ph: "np. drzwi wewnętrzne, meble kuchenne",
    omat_unit: "Jednostka",
    omat_f_widthMm: "Szerokość (mm)",
    omat_f_lengthMm: "Długość (mm)",
    omat_f_kerfMm: "Szerokość cięcia (mm)",
    omat_f_coveragePerUnitM2: "Wydajność opakowania (m²)",
    omat_f_packageAreaM2: "Powierzchnia opakowania (m²)",
    omat_f_wastePercent: "Zapas (%)",
    omat_price: "Cena za opakowanie",
    omat_price_unit: "Cena za jednostkę",
    omat_save: "Zapisz materiał",
    omat_list_t: "Twoje materiały",
    omat_search: "Szukaj w materiałach",
    omat_search_none: "Nie znaleziono pasujących materiałów.",
    omat_hist_t: "Historia cen",
    omat_hist_note: "Zapisujemy każdą wpisaną cenę i jej datę. Zmiana nazwy albo wymiarów nie zostawia śladu. Wiersz ma jedną datę zmiany.",
    omat_sync_note: "Materiały są częścią konta i synchronizują się po zalogowaniu.",
    omat_use_note: "Materiał z tej listy wybierzesz w kalkulatorze tak samo jak pozycję z katalogu.",
    omat_cur_note: "Cena trzyma walutę, w której ją wpisano. Nic nie jest przeliczane po kursie.",
    omat_guest_note: "Zaloguj się, żeby dodawać własne materiały i ceny.",
    omat_signin: "Zaloguj się",
  },
  en: {
    omatpage_lead: "Save a material the catalogue does not have, with the price your own supplier charges. Every later price stays in the history.",
    omatpage_meta: "Your own materials and price history in your LiczMat account.",
    omat_add_t: "New material",
    omat_name: "Name",
    omat_name_ph: "e.g. Porcelain tile 60×60 from my supplier",
    omat_cat: "Category",
    omat_app: "What it is for",
    omat_app_WALL_FLOOR_COVERING: "Wall and floor coverings",
    omat_app_DRYWALL_BOARDING: "Plasterboard construction",
    omat_app_COATING: "Coating materials",
    omat_app_PANEL_CUTTING: "Cutting boards and sheets",
    omat_app_LINEAR_STOCK: "Profiles, trims, pipes, rods",
    omat_app_OTHER: "Other",
    omat_purpose: "What it is for: description",
    omat_purpose_ph: "e.g. interior doors, kitchen furniture",
    omat_unit: "Unit",
    omat_f_widthMm: "Width (mm)",
    omat_f_lengthMm: "Length (mm)",
    omat_f_kerfMm: "Kerf (mm)",
    omat_f_coveragePerUnitM2: "Coverage per package (m²)",
    omat_f_packageAreaM2: "Area per package (m²)",
    omat_f_wastePercent: "Allowance (%)",
    omat_price: "Price per package",
    omat_price_unit: "Price per unit",
    omat_save: "Save material",
    omat_list_t: "Your materials",
    omat_search: "Search your materials",
    omat_search_none: "No matching materials found.",
    omat_hist_t: "Price history",
    omat_hist_note: "Every price you enter is kept with its date. A changed name or dimension leaves no trace. A row carries one date of change.",
    omat_sync_note: "Materials belong to your account and sync after you sign in.",
    omat_use_note: "A material from this list is picked in a calculator exactly like a catalogue entry.",
    omat_cur_note: "A price keeps the currency it was entered in. Nothing is converted at a rate.",
    omat_guest_note: "Sign in to add your own materials and prices.",
    omat_signin: "Sign in",
  },
  de: {
    omatpage_lead: "Speichern Sie ein Material, das der Katalog nicht hat, mit dem Preis Ihres Lieferanten. Jeder spätere Preis bleibt in der Historie.",
    omatpage_meta: "Eigene Materialien und Preisverlauf in deinem LiczMat-Konto.",
    omat_add_t: "Neues Material",
    omat_name: "Name",
    omat_name_ph: "z. B. Feinsteinzeug 60×60 vom Händler",
    omat_cat: "Kategorie",
    omat_app: "Wofür es ist",
    omat_app_WALL_FLOOR_COVERING: "Wand- und Bodenbeläge",
    omat_app_DRYWALL_BOARDING: "Trockenbau mit Gipsplatten",
    omat_app_COATING: "Deckende Materialien",
    omat_app_PANEL_CUTTING: "Zuschnitt von Platten",
    omat_app_LINEAR_STOCK: "Profile, Leisten, Rohre, Stäbe",
    omat_app_OTHER: "Sonstiges",
    omat_purpose: "Verwendungszweck: Beschreibung",
    omat_purpose_ph: "z. B. Innentüren, Küchenmöbel",
    omat_unit: "Einheit",
    omat_f_widthMm: "Breite (mm)",
    omat_f_lengthMm: "Länge (mm)",
    omat_f_kerfMm: "Schnittbreite (mm)",
    omat_f_coveragePerUnitM2: "Ergiebigkeit je Gebinde (m²)",
    omat_f_packageAreaM2: "Fläche je Gebinde (m²)",
    omat_f_wastePercent: "Zuschlag (%)",
    omat_price: "Preis je Gebinde",
    omat_price_unit: "Preis je Einheit",
    omat_save: "Material speichern",
    omat_list_t: "Ihre Materialien",
    omat_search: "Materialien durchsuchen",
    omat_search_none: "Keine passenden Materialien gefunden.",
    omat_hist_t: "Preisverlauf",
    omat_hist_note: "Jeder eingetragene Preis wird mit Datum gespeichert. Ein geänderter Name hinterlässt keine Spur. Die Zeile trägt ein Änderungsdatum.",
    omat_sync_note: "Materialien gehören zu deinem Konto und werden nach der Anmeldung synchronisiert.",
    omat_use_note: "Ein Material aus dieser Liste wählen Sie im Rechner genauso wie einen Katalogeintrag.",
    omat_cur_note: "Ein Preis behält die Währung, in der er eingetragen wurde. Nichts wird zum Kurs umgerechnet.",
    omat_guest_note: "Melde dich an, um eigene Materialien und Preise hinzuzufügen.",
    omat_signin: "Anmelden",
  },
  uk: {
    omatpage_lead: "Збережіть матеріал, якого немає в каталозі, разом із ціною вашого постачальника. Кожна наступна ціна лишається в історії.",
    omatpage_meta: "Власні матеріали та історія цін у твоєму акаунті LiczMat.",
    omat_add_t: "Новий матеріал",
    omat_name: "Назва",
    omat_name_ph: "напр. Керамограніт 60×60 від постачальника",
    omat_cat: "Категорія",
    omat_app: "Для чого він",
    omat_app_WALL_FLOOR_COVERING: "Покриття стін і підлог",
    omat_app_DRYWALL_BOARDING: "Зашивка гіпсокартоном",
    omat_app_COATING: "Покривні матеріали",
    omat_app_PANEL_CUTTING: "Розкрій плит і аркушів",
    omat_app_LINEAR_STOCK: "Профілі, планки, труби, прути",
    omat_app_OTHER: "Інше",
    omat_purpose: "Для чого призначено: опис",
    omat_purpose_ph: "напр. міжкімнатні двері, кухонні меблі",
    omat_unit: "Одиниця",
    omat_f_widthMm: "Ширина (мм)",
    omat_f_lengthMm: "Довжина (мм)",
    omat_f_kerfMm: "Ширина різу (мм)",
    omat_f_coveragePerUnitM2: "Витрата на упаковку (м²)",
    omat_f_packageAreaM2: "Площа упаковки (м²)",
    omat_f_wastePercent: "Запас (%)",
    omat_price: "Ціна за упаковку",
    omat_price_unit: "Ціна за одиницю",
    omat_save: "Зберегти матеріал",
    omat_list_t: "Ваші матеріали",
    omat_search: "Пошук у матеріалах",
    omat_search_none: "Відповідних матеріалів не знайдено.",
    omat_hist_t: "Історія цін",
    omat_hist_note: "Кожну внесену ціну зберігаємо з датою. Змінена назва чи розмір сліду не лишає. Рядок має одну дату зміни.",
    omat_sync_note: "Матеріали є частиною акаунта й синхронізуються після входу.",
    omat_use_note: "Матеріал із цього списку обирають у калькуляторі так само, як позицію з каталогу.",
    omat_cur_note: "Ціна тримає валюту, у якій її внесли. Нічого не перераховується за курсом.",
    omat_guest_note: "Увійди, щоб додавати власні матеріали й ціни.",
    omat_signin: "Увійти",
  },
  cs: {
    omatpage_lead: "Uložte materiál, který katalog nemá, i s cenou vašeho dodavatele. Každá další cena zůstane v historii.",
    omatpage_meta: "Vlastní materiály a historie cen ve tvém účtu LiczMat.",
    omat_add_t: "Nový materiál",
    omat_name: "Název",
    omat_name_ph: "např. Dlažba 60×60 od dodavatele",
    omat_cat: "Kategorie",
    omat_app: "K čemu slouží",
    omat_app_WALL_FLOOR_COVERING: "Obklady stěn a podlah",
    omat_app_DRYWALL_BOARDING: "Sádrokartonové konstrukce",
    omat_app_COATING: "Krycí materiály",
    omat_app_PANEL_CUTTING: "Nářez desek a archů",
    omat_app_LINEAR_STOCK: "Profily, lišty, trubky, tyče",
    omat_app_OTHER: "Ostatní",
    omat_purpose: "K čemu slouží: popis",
    omat_purpose_ph: "např. interiérové dveře, kuchyňský nábytek",
    omat_unit: "Jednotka",
    omat_f_widthMm: "Šířka (mm)",
    omat_f_lengthMm: "Délka (mm)",
    omat_f_kerfMm: "Šířka řezu (mm)",
    omat_f_coveragePerUnitM2: "Vydatnost balení (m²)",
    omat_f_packageAreaM2: "Plocha balení (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cena za balení",
    omat_price_unit: "Cena za jednotku",
    omat_save: "Uložit materiál",
    omat_list_t: "Vaše materiály",
    omat_search: "Hledat v materiálech",
    omat_search_none: "Nebyly nalezeny odpovídající materiály.",
    omat_hist_t: "Historie cen",
    omat_hist_note: "Každou zadanou cenu ukládáme s datem. Změněný název ani rozměr stopu nenechá. Řádek nese jedno datum změny.",
    omat_sync_note: "Materiály patří k tvému účtu a po přihlášení se synchronizují.",
    omat_use_note: "Materiál z tohoto seznamu vyberete v kalkulačce stejně jako položku z katalogu.",
    omat_cur_note: "Cena si drží měnu, ve které byla zadána. Nic se nepřepočítává kurzem.",
    omat_guest_note: "Přihlas se a přidávej vlastní materiály a ceny.",
    omat_signin: "Přihlásit se",
  },
  sk: {
    omatpage_lead: "Uložte materiál, ktorý katalóg nemá, aj s cenou vášho dodávateľa. Každá ďalšia cena zostane v histórii.",
    omatpage_meta: "Vlastné materiály a história cien v tvojom účte LiczMat.",
    omat_add_t: "Nový materiál",
    omat_name: "Názov",
    omat_name_ph: "napr. Dlažba 60×60 od dodávateľa",
    omat_cat: "Kategória",
    omat_app: "Na čo slúži",
    omat_app_WALL_FLOOR_COVERING: "Obklady stien a podláh",
    omat_app_DRYWALL_BOARDING: "Sadrokartónové konštrukcie",
    omat_app_COATING: "Krycie materiály",
    omat_app_PANEL_CUTTING: "Rezanie dosiek a hárkov",
    omat_app_LINEAR_STOCK: "Profily, lišty, rúrky, tyče",
    omat_app_OTHER: "Ostatné",
    omat_purpose: "Na čo slúži: opis",
    omat_purpose_ph: "napr. interiérové dvere, kuchynský nábytok",
    omat_unit: "Jednotka",
    omat_f_widthMm: "Šírka (mm)",
    omat_f_lengthMm: "Dĺžka (mm)",
    omat_f_kerfMm: "Šírka rezu (mm)",
    omat_f_coveragePerUnitM2: "Výdatnosť balenia (m²)",
    omat_f_packageAreaM2: "Plocha balenia (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cena za balenie",
    omat_price_unit: "Cena za jednotku",
    omat_save: "Uložiť materiál",
    omat_list_t: "Vaše materiály",
    omat_search: "Hľadať v materiáloch",
    omat_search_none: "Nenašli sa zodpovedajúce materiály.",
    omat_hist_t: "História cien",
    omat_hist_note: "Každú zadanú cenu ukladáme s dátumom. Zmenený názov ani rozmer stopu nenechá. Riadok nesie jeden dátum zmeny.",
    omat_sync_note: "Materiály patria k tvojmu účtu a po prihlásení sa synchronizujú.",
    omat_use_note: "Materiál z tohto zoznamu vyberiete v kalkulačke rovnako ako položku z katalógu.",
    omat_cur_note: "Cena si drží menu, v ktorej bola zadaná. Nič sa neprepočítava kurzom.",
    omat_guest_note: "Prihlás sa a pridávaj vlastné materiály a ceny.",
    omat_signin: "Prihlásiť sa",
  },
  ro: {
    omatpage_lead: "Salvați un material pe care catalogul nu îl are, cu prețul furnizorului dumneavoastră. Fiecare preț ulterior rămâne în istoric.",
    omatpage_meta: "Materialele tale și istoricul prețurilor în contul LiczMat.",
    omat_add_t: "Material nou",
    omat_name: "Denumire",
    omat_name_ph: "ex. Gresie 60×60 de la furnizor",
    omat_cat: "Categorie",
    omat_app: "La ce folosește",
    omat_app_WALL_FLOOR_COVERING: "Placări de pereți și pardoseli",
    omat_app_DRYWALL_BOARDING: "Construcții din gips-carton",
    omat_app_COATING: "Materiale de acoperire",
    omat_app_PANEL_CUTTING: "Debitare de plăci și coli",
    omat_app_LINEAR_STOCK: "Profile, baghete, țevi, bare",
    omat_app_OTHER: "Altele",
    omat_purpose: "La ce se folosește: descriere",
    omat_purpose_ph: "de ex. uși de interior, mobilier de bucătărie",
    omat_unit: "Unitate",
    omat_f_widthMm: "Lățime (mm)",
    omat_f_lengthMm: "Lungime (mm)",
    omat_f_kerfMm: "Lățimea tăieturii (mm)",
    omat_f_coveragePerUnitM2: "Randament pe ambalaj (m²)",
    omat_f_packageAreaM2: "Suprafață pe ambalaj (m²)",
    omat_f_wastePercent: "Rezervă (%)",
    omat_price: "Preț pe ambalaj",
    omat_price_unit: "Preț pe unitate",
    omat_save: "Salvează materialul",
    omat_list_t: "Materialele dumneavoastră",
    omat_search: "Căutați în materiale",
    omat_search_none: "Nu s-au găsit materiale potrivite.",
    omat_hist_t: "Istoricul prețurilor",
    omat_hist_note: "Fiecare preț introdus este păstrat cu data lui. Un nume schimbat nu lasă urmă. Rândul poartă o singură dată a modificării.",
    omat_sync_note: "Materialele fac parte din cont și se sincronizează după autentificare.",
    omat_use_note: "Un material din această listă se alege în calculator exact ca o intrare din catalog.",
    omat_cur_note: "Un preț păstrează moneda în care a fost introdus. Nimic nu este convertit la cursul zilei.",
    omat_guest_note: "Autentifică-te ca să adaugi propriile materiale și prețuri.",
    omat_signin: "Autentifică-te",
  },
  hr: {
    omatpage_lead: "Spremite materijal kojega nema u katalogu, zajedno s cijenom vašeg dobavljača. Svaka sljedeća cijena ostaje u povijesti.",
    omatpage_meta: "Tvoji materijali i povijest cijena na računu LiczMat.",
    omat_add_t: "Novi materijal",
    omat_name: "Naziv",
    omat_name_ph: "npr. Gres 60×60 od dobavljača",
    omat_cat: "Kategorija",
    omat_app: "Čemu služi",
    omat_app_WALL_FLOOR_COVERING: "Obloge zidova i podova",
    omat_app_DRYWALL_BOARDING: "Gipsane konstrukcije",
    omat_app_COATING: "Pokrivni materijali",
    omat_app_PANEL_CUTTING: "Rezanje ploča i araka",
    omat_app_LINEAR_STOCK: "Profili, letvice, cijevi, šipke",
    omat_app_OTHER: "Ostalo",
    omat_purpose: "Čemu služi: opis",
    omat_purpose_ph: "npr. unutarnja vrata, kuhinjski namještaj",
    omat_unit: "Jedinica",
    omat_f_widthMm: "Širina (mm)",
    omat_f_lengthMm: "Duljina (mm)",
    omat_f_kerfMm: "Širina reza (mm)",
    omat_f_coveragePerUnitM2: "Izdašnost pakiranja (m²)",
    omat_f_packageAreaM2: "Površina pakiranja (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cijena po pakiranju",
    omat_price_unit: "Cijena po jedinici",
    omat_save: "Spremi materijal",
    omat_list_t: "Vaši materijali",
    omat_search: "Pretražite materijale",
    omat_search_none: "Nema odgovarajućih materijala.",
    omat_hist_t: "Povijest cijena",
    omat_hist_note: "Svaku unesenu cijenu čuvamo s datumom. Promijenjen naziv ili dimenzija ne ostavlja trag. Redak nosi jedan datum promjene.",
    omat_sync_note: "Materijali su dio računa i sinkroniziraju se nakon prijave.",
    omat_use_note: "Materijal s ovog popisa bira se u kalkulatoru jednako kao stavka iz kataloga.",
    omat_cur_note: "Cijena zadržava valutu u kojoj je unesena. Ništa se ne preračunava po tečaju.",
    omat_guest_note: "Prijavi se da dodaješ vlastite materijale i cijene.",
    omat_signin: "Prijavi se",
  },
  sr: {
    omatpage_lead: "Sačuvajte materijal kojeg nema u katalogu, zajedno sa cenom vašeg dobavljača. Svaka sledeća cena ostaje u istoriji.",
    omatpage_meta: "Tvoji materijali i istorija cena na nalogu LiczMat.",
    omat_add_t: "Novi materijal",
    omat_name: "Naziv",
    omat_name_ph: "npr. Gres 60×60 od dobavljača",
    omat_cat: "Kategorija",
    omat_app: "Čemu služi",
    omat_app_WALL_FLOOR_COVERING: "Obloge zidova i podova",
    omat_app_DRYWALL_BOARDING: "Gipsane konstrukcije",
    omat_app_COATING: "Pokrivni materijali",
    omat_app_PANEL_CUTTING: "Sečenje ploča i tabli",
    omat_app_LINEAR_STOCK: "Profili, lajsne, cevi, šipke",
    omat_app_OTHER: "Ostalo",
    omat_purpose: "Čemu služi: opis",
    omat_purpose_ph: "npr. unutrašnja vrata, kuhinjski nameštaj",
    omat_unit: "Jedinica",
    omat_f_widthMm: "Širina (mm)",
    omat_f_lengthMm: "Dužina (mm)",
    omat_f_kerfMm: "Širina reza (mm)",
    omat_f_coveragePerUnitM2: "Izdašnost pakovanja (m²)",
    omat_f_packageAreaM2: "Površina pakovanja (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cena po pakovanju",
    omat_price_unit: "Cena po jedinici",
    omat_save: "Sačuvaj materijal",
    omat_list_t: "Vaši materijali",
    omat_search: "Pretražite materijale",
    omat_search_none: "Nema odgovarajućih materijala.",
    omat_hist_t: "Istorija cena",
    omat_hist_note: "Svaku unetu cenu čuvamo sa datumom. Promenjen naziv ili dimenzija ne ostavlja trag. Red nosi jedan datum promene.",
    omat_sync_note: "Materijali su deo naloga i sinhronizuju se posle prijave.",
    omat_use_note: "Materijal sa ovog spiska bira se u kalkulatoru isto kao stavka iz kataloga.",
    omat_cur_note: "Cena zadržava valutu u kojoj je uneta. Ništa se ne preračunava po kursu.",
    omat_guest_note: "Prijavi se da dodaješ sopstvene materijale i cene.",
    omat_signin: "Prijavi se",
  },
  it: {
    omatpage_lead: "Salva un materiale che il catalogo non ha, con il prezzo che ti fa il tuo fornitore. Ogni prezzo successivo resta nella storia.",
    omatpage_meta: "I tuoi materiali e la cronologia dei prezzi nel tuo account LiczMat.",
    omat_add_t: "Nuovo materiale",
    omat_name: "Nome",
    omat_name_ph: "es. Gres 60×60 del mio fornitore",
    omat_cat: "Categoria",
    omat_app: "A che cosa serve",
    omat_app_WALL_FLOOR_COVERING: "Rivestimenti di pareti e pavimenti",
    omat_app_DRYWALL_BOARDING: "Costruzione in cartongesso",
    omat_app_COATING: "Materiali da stendere",
    omat_app_PANEL_CUTTING: "Taglio di pannelli e lastre",
    omat_app_LINEAR_STOCK: "Profili, listelli, tubi, tondini",
    omat_app_OTHER: "Altro",
    omat_purpose: "A cosa serve: descrizione",
    omat_purpose_ph: "ad es. porte interne, mobili da cucina",
    omat_unit: "Unità",
    omat_f_widthMm: "Larghezza (mm)",
    omat_f_lengthMm: "Lunghezza (mm)",
    omat_f_kerfMm: "Spessore di taglio (mm)",
    omat_f_coveragePerUnitM2: "Resa per confezione (m²)",
    omat_f_packageAreaM2: "Superficie per confezione (m²)",
    omat_f_wastePercent: "Scorta (%)",
    omat_price: "Prezzo per confezione",
    omat_price_unit: "Prezzo per unità",
    omat_save: "Salva il materiale",
    omat_list_t: "I tuoi materiali",
    omat_search: "Cerca nei materiali",
    omat_search_none: "Nessun materiale corrispondente.",
    omat_hist_t: "Storia dei prezzi",
    omat_hist_note: "Ogni prezzo che inserisci resta con la sua data. Un nome o una misura cambiati non lasciano traccia: una riga porta una sola data di modifica.",
    omat_sync_note: "I materiali fanno parte dell'account e si sincronizzano dopo l'accesso.",
    omat_use_note: "Un materiale di questo elenco si sceglie in un calcolatore come una voce del catalogo.",
    omat_cur_note: "Un prezzo mantiene la valuta in cui è stato inserito. Nulla viene convertito a un cambio.",
    omat_guest_note: "Accedi per aggiungere i tuoi materiali e prezzi.",
    omat_signin: "Accedi",
  },
  nl: {
    omatpage_lead: "Bewaar een materiaal dat de catalogus niet heeft, met de prijs die jouw leverancier rekent. Elke latere prijs blijft in de geschiedenis staan.",
    omatpage_meta: "Je eigen materialen en prijsgeschiedenis in je LiczMat-account.",
    omat_add_t: "Nieuw materiaal",
    omat_name: "Naam",
    omat_name_ph: "bv. Keramische tegel 60×60 van mijn leverancier",
    omat_cat: "Categorie",
    omat_app: "Waar het voor is",
    omat_app_WALL_FLOOR_COVERING: "Wand- en vloerbekleding",
    omat_app_DRYWALL_BOARDING: "Gipswandbouw",
    omat_app_COATING: "Materiaal dat je aanbrengt",
    omat_app_PANEL_CUTTING: "Platen en panelen zagen",
    omat_app_LINEAR_STOCK: "Profielen, lijsten, buizen, staven",
    omat_app_OTHER: "Overig",
    omat_purpose: "Waarvoor het dient: beschrijving",
    omat_purpose_ph: "bijv. binnendeuren, keukenmeubels",
    omat_unit: "Eenheid",
    omat_f_widthMm: "Breedte (mm)",
    omat_f_lengthMm: "Lengte (mm)",
    omat_f_kerfMm: "Zaagsnede (mm)",
    omat_f_coveragePerUnitM2: "Rendement per verpakking (m²)",
    omat_f_packageAreaM2: "Oppervlak per verpakking (m²)",
    omat_f_wastePercent: "Marge (%)",
    omat_price: "Prijs per verpakking",
    omat_price_unit: "Prijs per eenheid",
    omat_save: "Materiaal opslaan",
    omat_list_t: "Jouw materialen",
    omat_search: "Zoek in materialen",
    omat_search_none: "Geen overeenkomende materialen gevonden.",
    omat_hist_t: "Prijsgeschiedenis",
    omat_hist_note: "Elke prijs die je invult wordt met zijn datum bewaard. Een gewijzigde naam of maat laat geen spoor na. Een regel draagt één wijzigingsdatum.",
    omat_sync_note: "Materialen horen bij je account en synchroniseren nadat je inlogt.",
    omat_use_note: "Een materiaal uit deze lijst kies je in een rekenmachine net als een regel uit de catalogus.",
    omat_cur_note: "Een prijs houdt de valuta waarin hij is ingevuld. Er wordt niets tegen een koers omgerekend.",
    omat_guest_note: "Log in om je eigen materialen en prijzen toe te voegen.",
    omat_signin: "Log in",
  },
  es: {
    omatpage_lead: "Guarda un material que el catálogo no tiene, con el precio que te hace tu proveedor. Cada precio posterior se queda en el historial.",
    omatpage_meta: "Tus materiales y el historial de precios en tu cuenta LiczMat.",
    omat_add_t: "Material nuevo",
    omat_name: "Nombre",
    omat_name_ph: "p. ej. Porcelánico 60×60 de mi proveedor",
    omat_cat: "Categoría",
    omat_app: "Para qué sirve",
    omat_app_WALL_FLOOR_COVERING: "Revestimientos de paredes y suelos",
    omat_app_DRYWALL_BOARDING: "Construcción con pladur",
    omat_app_COATING: "Materiales que se aplican",
    omat_app_PANEL_CUTTING: "Corte de tableros y planchas",
    omat_app_LINEAR_STOCK: "Perfiles, molduras, tubos, barras",
    omat_app_OTHER: "Otros",
    omat_purpose: "Para qué sirve: descripción",
    omat_purpose_ph: "p. ej. puertas interiores, muebles de cocina",
    omat_unit: "Unidad",
    omat_f_widthMm: "Anchura (mm)",
    omat_f_lengthMm: "Longitud (mm)",
    omat_f_kerfMm: "Grosor de corte (mm)",
    omat_f_coveragePerUnitM2: "Rendimiento por envase (m²)",
    omat_f_packageAreaM2: "Superficie por envase (m²)",
    omat_f_wastePercent: "Merma (%)",
    omat_price: "Precio por envase",
    omat_price_unit: "Precio por unidad",
    omat_save: "Guardar el material",
    omat_list_t: "Tus materiales",
    omat_search: "Buscar en materiales",
    omat_search_none: "No se encontraron materiales coincidentes.",
    omat_hist_t: "Historial de precios",
    omat_hist_note: "Cada precio que escribes se guarda con su fecha. Un nombre o una medida cambiados no dejan rastro: una fila lleva una sola fecha de cambio.",
    omat_sync_note: "Los materiales forman parte de la cuenta y se sincronizan después de iniciar sesión.",
    omat_use_note: "Un material de esta lista se elige en una calculadora igual que una entrada del catálogo.",
    omat_cur_note: "Un precio mantiene la moneda en la que se escribió. No se convierte nada a ningún cambio.",
    omat_guest_note: "Inicia sesión para añadir tus propios materiales y precios.",
    omat_signin: "Inicia sesión",
  },
  fr: {
    omatpage_lead: "Enregistre un matériau que le catalogue n'a pas, au prix que pratique ton fournisseur. Chaque prix suivant reste dans l'historique.",
    omatpage_meta: "Tes matériaux et l'historique des prix dans ton compte LiczMat.",
    omat_add_t: "Nouveau matériau",
    omat_name: "Nom",
    omat_name_ph: "p. ex. Grès 60×60 de mon fournisseur",
    omat_cat: "Catégorie",
    omat_app: "À quoi il sert",
    omat_app_WALL_FLOOR_COVERING: "Revêtements de murs et de sols",
    omat_app_DRYWALL_BOARDING: "Construction en placo",
    omat_app_COATING: "Matériaux que l'on applique",
    omat_app_PANEL_CUTTING: "Découpe de panneaux et de plaques",
    omat_app_LINEAR_STOCK: "Profilés, moulures, tubes, barres",
    omat_app_OTHER: "Autres",
    omat_purpose: "À quoi il sert: description",
    omat_purpose_ph: "p. ex. portes intérieures, meubles de cuisine",
    omat_unit: "Unité",
    omat_f_widthMm: "Largeur (mm)",
    omat_f_lengthMm: "Longueur (mm)",
    omat_f_kerfMm: "Trait de scie (mm)",
    omat_f_coveragePerUnitM2: "Rendement par emballage (m²)",
    omat_f_packageAreaM2: "Surface par emballage (m²)",
    omat_f_wastePercent: "Marge (%)",
    omat_price: "Prix par emballage",
    omat_price_unit: "Prix par unité",
    omat_save: "Enregistrer le matériau",
    omat_list_t: "Tes matériaux",
    omat_search: "Rechercher dans les matériaux",
    omat_search_none: "Aucun.",
    omat_hist_t: "Historique des prix",
    omat_hist_note: "Chaque prix que tu saisis est gardé avec sa date. Un nom ou une dimension modifiés ne laissent pas de trace. Une ligne porte une seule date de modification.",
    omat_sync_note: "Les matériaux font partie du compte et se synchronisent après ta connexion.",
    omat_use_note: "Un matériau de cette liste se choisit dans un calculateur comme une entrée du catalogue.",
    omat_cur_note: "Un prix garde la devise dans laquelle il a été saisi. Rien n'est converti à un taux.",
    omat_guest_note: "Connecte-toi pour ajouter tes propres matériaux et prix.",
    omat_signin: "Se connecter",
  },
};

/** Every key the page needs, so validate() can fail on a language missing one. */
export const OMAT_COPY_KEYS = Object.keys(OMAT_COPY.pl);
