/* LiczMat website — the words on the "my materials" page, in ten languages.
 *
 * Session 59, item C6 of the parity audit. It sits in src/ rather than in
 * assets/i18n-pages.js for the reason src/conv-copy.mjs and src/calc-seo.mjs do, and the
 * measurement is the same: every page on this site downloads assets/i18n.<lang>.js, and
 * 27 keys per language of copy that only the build and a reader of the finished HTML ever
 * see is about 1.6 kB on every page load for nothing. /app/ is the heaviest page on the
 * site and had 0.7 kB of gzipped headroom before this session started, which is what a
 * budget with no margin in it is for.
 *
 * The page can afford this because it is localized: one URL per language, and the language
 * switcher navigates rather than re-translating the DOM. What the browser writes at
 * runtime — the list, the trend, the undo strip — stays in the dictionary, under the same
 * `omat_` prefix, because those strings are chosen after the page has been served.
 *
 * ONE KEY IS NOT HERE, for the reason `convpage_title` is not in src/conv-copy.mjs:
 * `omatpage_title` is this route's `footer.key` in src/ia.mjs, so the footer of all 393
 * pages takes its label from the dictionary. Moving it here would print the literal word
 * "omatpage_title" in every footer, in every language, with every suite still green —
 * session 41's defect, and session 57 walked into it a second time with a different key.
 *
 * WHAT IS COPIED AND WHAT IS WRITTEN. The five `omat_app_*` labels are the app's own
 * `MaterialApplication.labelPl` and its nine translations: one concept may not be called
 * two things on the two products, which is the rule session 53 wrote down when the app
 * took this site's `cal_*` strings. The measurement labels are the field labels the
 * calculators already use. The rest — the lead, the meta description, and the two notes
 * saying what the history does and does not record — is written here, because the app has
 * no page to say it on.
 *
 * scripts/test-copy.mjs reads this file alongside the dictionaries, so the six stop-slop
 * rules cover it exactly as they cover everything else a visitor can read.
 */

export const OMAT_COPY = {
  pl: {
    omatpage_lead: "Zapisz materiał, którego nie ma w katalogu, razem z ceną u twojego dostawcy. Każda kolejna cena zostaje w historii.",
    omatpage_meta: "Własne materiały budowlane z ceną i historią zmian. Zapisz wymiary i wydajność raz, potem licz nimi w kalkulatorze. Bez konta.",
    omat_add_t: "Nowy materiał",
    omat_name: "Nazwa",
    omat_name_ph: "np. Gres od Kowalskiego 60×60",
    omat_cat: "Kategoria",
    omat_app: "Do czego służy",
    omat_app_WALL_FLOOR_COVERING: "Okładziny ścian i podłóg",
    omat_app_DRYWALL_BOARDING: "Zabudowa płytami G-K",
    omat_app_COATING: "Materiały kryjące",
    omat_app_PANEL_CUTTING: "Rozkrój płyt i arkuszy",
    omat_app_LINEAR_STOCK: "Profile, listwy, rury, pręty",
    omat_f_widthMm: "Szerokość (mm)",
    omat_f_lengthMm: "Długość (mm)",
    omat_f_kerfMm: "Szerokość cięcia (mm)",
    omat_f_coveragePerUnitM2: "Wydajność opakowania (m²)",
    omat_f_packageAreaM2: "Powierzchnia opakowania (m²)",
    omat_f_wastePercent: "Zapas (%)",
    omat_price: "Cena za opakowanie",
    omat_save: "Zapisz materiał",
    omat_list_t: "Twoje materiały",
    omat_hist_t: "Historia cen",
    omat_hist_note: "Zapisujemy każdą wpisaną cenę i jej datę. Zmiana nazwy albo wymiarów nie zostawia śladu — wiersz ma jedną datę zmiany.",
    omat_sync_note: "Materiały zostają w tej przeglądarce. Po zalogowaniu są częścią konta i widzi je też aplikacja.",
    omat_use_note: "Materiał z tej listy wybierzesz w kalkulatorze tak samo jak pozycję z katalogu.",
    omat_cur_note: "Cena trzyma walutę, w której ją wpisano. Nic nie jest przeliczane po kursie.",
  },
  en: {
    omatpage_lead: "Save a material the catalogue does not have, with the price your own supplier charges. Every later price stays in the history.",
    omatpage_meta: "Your own building materials with a price and a change history. Enter the dimensions and coverage once, then calculate with them. No account.",
    omat_add_t: "New material",
    omat_name: "Name",
    omat_name_ph: "e.g. Porcelain tile 60×60 from my supplier",
    omat_cat: "Category",
    omat_app: "What it is for",
    omat_app_WALL_FLOOR_COVERING: "Wall and floor coverings",
    omat_app_DRYWALL_BOARDING: "Plasterboard construction",
    omat_app_COATING: "Coating materials",
    omat_app_PANEL_CUTTING: "Cutting boards and sheets",
    omat_app_LINEAR_STOCK: "Profiles, trims, pipes, rods",
    omat_f_widthMm: "Width (mm)",
    omat_f_lengthMm: "Length (mm)",
    omat_f_kerfMm: "Kerf (mm)",
    omat_f_coveragePerUnitM2: "Coverage per package (m²)",
    omat_f_packageAreaM2: "Area per package (m²)",
    omat_f_wastePercent: "Allowance (%)",
    omat_price: "Price per package",
    omat_save: "Save material",
    omat_list_t: "Your materials",
    omat_hist_t: "Price history",
    omat_hist_note: "Every price you enter is kept with its date. A changed name or dimension leaves no trace — a row carries one date of change.",
    omat_sync_note: "Materials stay in this browser. Once you sign in they are part of the account and the app sees them too.",
    omat_use_note: "A material from this list is picked in a calculator exactly like a catalogue entry.",
    omat_cur_note: "A price keeps the currency it was entered in. Nothing is converted at a rate.",
  },
  de: {
    omatpage_lead: "Speichern Sie ein Material, das der Katalog nicht hat, mit dem Preis Ihres Lieferanten. Jeder spätere Preis bleibt in der Historie.",
    omatpage_meta: "Eigene Baumaterialien mit Preis und Änderungshistorie. Maße und Ergiebigkeit einmal eintragen, dann damit rechnen. Ohne Konto.",
    omat_add_t: "Neues Material",
    omat_name: "Name",
    omat_name_ph: "z. B. Feinsteinzeug 60×60 vom Händler",
    omat_cat: "Kategorie",
    omat_app: "Wofür es ist",
    omat_app_WALL_FLOOR_COVERING: "Wand- und Bodenbeläge",
    omat_app_DRYWALL_BOARDING: "Trockenbau mit Gipsplatten",
    omat_app_COATING: "Deckende Materialien",
    omat_app_PANEL_CUTTING: "Zuschnitt von Platten",
    omat_app_LINEAR_STOCK: "Profile, Leisten, Rohre, Stäbe",
    omat_f_widthMm: "Breite (mm)",
    omat_f_lengthMm: "Länge (mm)",
    omat_f_kerfMm: "Schnittbreite (mm)",
    omat_f_coveragePerUnitM2: "Ergiebigkeit je Gebinde (m²)",
    omat_f_packageAreaM2: "Fläche je Gebinde (m²)",
    omat_f_wastePercent: "Zuschlag (%)",
    omat_price: "Preis je Gebinde",
    omat_save: "Material speichern",
    omat_list_t: "Ihre Materialien",
    omat_hist_t: "Preisverlauf",
    omat_hist_note: "Jeder eingetragene Preis wird mit Datum gespeichert. Ein geänderter Name hinterlässt keine Spur — die Zeile trägt ein Änderungsdatum.",
    omat_sync_note: "Die Materialien bleiben in diesem Browser. Nach der Anmeldung gehören sie zum Konto und die App sieht sie ebenfalls.",
    omat_use_note: "Ein Material aus dieser Liste wählen Sie im Rechner genauso wie einen Katalogeintrag.",
    omat_cur_note: "Ein Preis behält die Währung, in der er eingetragen wurde. Nichts wird zum Kurs umgerechnet.",
  },
  uk: {
    omatpage_lead: "Збережіть матеріал, якого немає в каталозі, разом із ціною вашого постачальника. Кожна наступна ціна лишається в історії.",
    omatpage_meta: "Власні будівельні матеріали з ціною та історією змін. Внесіть розміри й витрату один раз, далі рахуйте ними. Без облікового запису.",
    omat_add_t: "Новий матеріал",
    omat_name: "Назва",
    omat_name_ph: "напр. Керамограніт 60×60 від постачальника",
    omat_cat: "Категорія",
    omat_app: "Для чого він",
    omat_app_WALL_FLOOR_COVERING: "Покриття стін і підлог",
    omat_app_DRYWALL_BOARDING: "Зашивка гіпсокартоном",
    omat_app_COATING: "Покривні матеріали",
    omat_app_PANEL_CUTTING: "Розкрій плит і аркушів",
    omat_app_LINEAR_STOCK: "Профілі, планки, труби, прути",
    omat_f_widthMm: "Ширина (мм)",
    omat_f_lengthMm: "Довжина (мм)",
    omat_f_kerfMm: "Ширина різу (мм)",
    omat_f_coveragePerUnitM2: "Витрата на упаковку (м²)",
    omat_f_packageAreaM2: "Площа упаковки (м²)",
    omat_f_wastePercent: "Запас (%)",
    omat_price: "Ціна за упаковку",
    omat_save: "Зберегти матеріал",
    omat_list_t: "Ваші матеріали",
    omat_hist_t: "Історія цін",
    omat_hist_note: "Кожну внесену ціну зберігаємо з датою. Змінена назва чи розмір сліду не лишає — рядок має одну дату зміни.",
    omat_sync_note: "Матеріали лишаються в цьому браузері. Після входу вони частина облікового запису, і застосунок їх теж бачить.",
    omat_use_note: "Матеріал із цього списку обирають у калькуляторі так само, як позицію з каталогу.",
    omat_cur_note: "Ціна тримає валюту, у якій її внесли. Нічого не перераховується за курсом.",
  },
  cs: {
    omatpage_lead: "Uložte materiál, který katalog nemá, i s cenou vašeho dodavatele. Každá další cena zůstane v historii.",
    omatpage_meta: "Vlastní stavební materiály s cenou a historií změn. Rozměry a vydatnost zadáte jednou, pak s nimi počítáte. Bez účtu.",
    omat_add_t: "Nový materiál",
    omat_name: "Název",
    omat_name_ph: "např. Dlažba 60×60 od dodavatele",
    omat_cat: "Kategorie",
    omat_app: "K čemu slouží",
    omat_app_WALL_FLOOR_COVERING: "Obklady stěn a podlah",
    omat_app_DRYWALL_BOARDING: "Sádrokartonové konstrukce",
    omat_app_COATING: "Krycí materiály",
    omat_app_PANEL_CUTTING: "Nářez desek a archů",
    omat_app_LINEAR_STOCK: "Profily, lišty, trubky, tyče",
    omat_f_widthMm: "Šířka (mm)",
    omat_f_lengthMm: "Délka (mm)",
    omat_f_kerfMm: "Šířka řezu (mm)",
    omat_f_coveragePerUnitM2: "Vydatnost balení (m²)",
    omat_f_packageAreaM2: "Plocha balení (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cena za balení",
    omat_save: "Uložit materiál",
    omat_list_t: "Vaše materiály",
    omat_hist_t: "Historie cen",
    omat_hist_note: "Každou zadanou cenu ukládáme s datem. Změněný název ani rozměr stopu nenechá — řádek nese jedno datum změny.",
    omat_sync_note: "Materiály zůstávají v tomto prohlížeči. Po přihlášení patří k účtu a vidí je i aplikace.",
    omat_use_note: "Materiál z tohoto seznamu vyberete v kalkulačce stejně jako položku z katalogu.",
    omat_cur_note: "Cena si drží měnu, ve které byla zadána. Nic se nepřepočítává kurzem.",
  },
  sk: {
    omatpage_lead: "Uložte materiál, ktorý katalóg nemá, aj s cenou vášho dodávateľa. Každá ďalšia cena zostane v histórii.",
    omatpage_meta: "Vlastné stavebné materiály s cenou a históriou zmien. Rozmery a výdatnosť zadáte raz, potom s nimi počítate. Bez účtu.",
    omat_add_t: "Nový materiál",
    omat_name: "Názov",
    omat_name_ph: "napr. Dlažba 60×60 od dodávateľa",
    omat_cat: "Kategória",
    omat_app: "Na čo slúži",
    omat_app_WALL_FLOOR_COVERING: "Obklady stien a podláh",
    omat_app_DRYWALL_BOARDING: "Sadrokartónové konštrukcie",
    omat_app_COATING: "Krycie materiály",
    omat_app_PANEL_CUTTING: "Rezanie dosiek a hárkov",
    omat_app_LINEAR_STOCK: "Profily, lišty, rúrky, tyče",
    omat_f_widthMm: "Šírka (mm)",
    omat_f_lengthMm: "Dĺžka (mm)",
    omat_f_kerfMm: "Šírka rezu (mm)",
    omat_f_coveragePerUnitM2: "Výdatnosť balenia (m²)",
    omat_f_packageAreaM2: "Plocha balenia (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cena za balenie",
    omat_save: "Uložiť materiál",
    omat_list_t: "Vaše materiály",
    omat_hist_t: "História cien",
    omat_hist_note: "Každú zadanú cenu ukladáme s dátumom. Zmenený názov ani rozmer stopu nenechá — riadok nesie jeden dátum zmeny.",
    omat_sync_note: "Materiály zostávajú v tomto prehliadači. Po prihlásení patria k účtu a vidí ich aj aplikácia.",
    omat_use_note: "Materiál z tohto zoznamu vyberiete v kalkulačke rovnako ako položku z katalógu.",
    omat_cur_note: "Cena si drží menu, v ktorej bola zadaná. Nič sa neprepočítava kurzom.",
  },
  ro: {
    omatpage_lead: "Salvați un material pe care catalogul nu îl are, cu prețul furnizorului dumneavoastră. Fiecare preț ulterior rămâne în istoric.",
    omatpage_meta: "Materiale de construcții proprii, cu preț și istoric de modificări. Introduceți dimensiunile și randamentul o dată, apoi calculați cu ele.",
    omat_add_t: "Material nou",
    omat_name: "Denumire",
    omat_name_ph: "ex. Gresie 60×60 de la furnizor",
    omat_cat: "Categorie",
    omat_app: "La ce folosește",
    omat_app_WALL_FLOOR_COVERING: "Placări de pereți și pardoseli",
    omat_app_DRYWALL_BOARDING: "Construcții din gips-carton",
    omat_app_COATING: "Materiale de acoperire",
    omat_app_PANEL_CUTTING: "Debitare de plăci și coli",
    omat_app_LINEAR_STOCK: "Profile, baghete, țevi, bare",
    omat_f_widthMm: "Lățime (mm)",
    omat_f_lengthMm: "Lungime (mm)",
    omat_f_kerfMm: "Lățimea tăieturii (mm)",
    omat_f_coveragePerUnitM2: "Randament pe ambalaj (m²)",
    omat_f_packageAreaM2: "Suprafață pe ambalaj (m²)",
    omat_f_wastePercent: "Rezervă (%)",
    omat_price: "Preț pe ambalaj",
    omat_save: "Salvează materialul",
    omat_list_t: "Materialele dumneavoastră",
    omat_hist_t: "Istoricul prețurilor",
    omat_hist_note: "Fiecare preț introdus este păstrat cu data lui. Un nume schimbat nu lasă urmă — rândul poartă o singură dată a modificării.",
    omat_sync_note: "Materialele rămân în acest browser. După autentificare fac parte din cont, iar aplicația le vede și ea.",
    omat_use_note: "Un material din această listă se alege în calculator exact ca o intrare din catalog.",
    omat_cur_note: "Un preț păstrează moneda în care a fost introdus. Nimic nu este convertit la cursul zilei.",
  },
  hr: {
    omatpage_lead: "Spremite materijal kojega nema u katalogu, zajedno s cijenom vašeg dobavljača. Svaka sljedeća cijena ostaje u povijesti.",
    omatpage_meta: "Vlastiti građevinski materijali s cijenom i poviješću promjena. Dimenzije i izdašnost unesete jednom, zatim njima računate. Bez računa.",
    omat_add_t: "Novi materijal",
    omat_name: "Naziv",
    omat_name_ph: "npr. Gres 60×60 od dobavljača",
    omat_cat: "Kategorija",
    omat_app: "Čemu služi",
    omat_app_WALL_FLOOR_COVERING: "Obloge zidova i podova",
    omat_app_DRYWALL_BOARDING: "Gipsane konstrukcije",
    omat_app_COATING: "Pokrivni materijali",
    omat_app_PANEL_CUTTING: "Rezanje ploča i araka",
    omat_app_LINEAR_STOCK: "Profili, letvice, cijevi, šipke",
    omat_f_widthMm: "Širina (mm)",
    omat_f_lengthMm: "Duljina (mm)",
    omat_f_kerfMm: "Širina reza (mm)",
    omat_f_coveragePerUnitM2: "Izdašnost pakiranja (m²)",
    omat_f_packageAreaM2: "Površina pakiranja (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cijena po pakiranju",
    omat_save: "Spremi materijal",
    omat_list_t: "Vaši materijali",
    omat_hist_t: "Povijest cijena",
    omat_hist_note: "Svaku unesenu cijenu čuvamo s datumom. Promijenjen naziv ili dimenzija ne ostavlja trag — redak nosi jedan datum promjene.",
    omat_sync_note: "Materijali ostaju u ovom pregledniku. Nakon prijave dio su računa i vidi ih i aplikacija.",
    omat_use_note: "Materijal s ovog popisa bira se u kalkulatoru jednako kao stavka iz kataloga.",
    omat_cur_note: "Cijena zadržava valutu u kojoj je unesena. Ništa se ne preračunava po tečaju.",
  },
  sr: {
    omatpage_lead: "Sačuvajte materijal kojeg nema u katalogu, zajedno sa cenom vašeg dobavljača. Svaka sledeća cena ostaje u istoriji.",
    omatpage_meta: "Sopstveni građevinski materijali sa cenom i istorijom promena. Dimenzije i izdašnost unesete jednom, zatim njima računate. Bez naloga.",
    omat_add_t: "Novi materijal",
    omat_name: "Naziv",
    omat_name_ph: "npr. Gres 60×60 od dobavljača",
    omat_cat: "Kategorija",
    omat_app: "Čemu služi",
    omat_app_WALL_FLOOR_COVERING: "Obloge zidova i podova",
    omat_app_DRYWALL_BOARDING: "Gipsane konstrukcije",
    omat_app_COATING: "Pokrivni materijali",
    omat_app_PANEL_CUTTING: "Sečenje ploča i tabli",
    omat_app_LINEAR_STOCK: "Profili, lajsne, cevi, šipke",
    omat_f_widthMm: "Širina (mm)",
    omat_f_lengthMm: "Dužina (mm)",
    omat_f_kerfMm: "Širina reza (mm)",
    omat_f_coveragePerUnitM2: "Izdašnost pakovanja (m²)",
    omat_f_packageAreaM2: "Površina pakovanja (m²)",
    omat_f_wastePercent: "Rezerva (%)",
    omat_price: "Cena po pakovanju",
    omat_save: "Sačuvaj materijal",
    omat_list_t: "Vaši materijali",
    omat_hist_t: "Istorija cena",
    omat_hist_note: "Svaku unetu cenu čuvamo sa datumom. Promenjen naziv ili dimenzija ne ostavlja trag — red nosi jedan datum promene.",
    omat_sync_note: "Materijali ostaju u ovom pregledaču. Nakon prijave deo su naloga i vidi ih i aplikacija.",
    omat_use_note: "Materijal sa ovog spiska bira se u kalkulatoru isto kao stavka iz kataloga.",
    omat_cur_note: "Cena zadržava valutu u kojoj je uneta. Ništa se ne preračunava po kursu.",
  },
  it: {
    omatpage_lead: "Salva un materiale che il catalogo non ha, con il prezzo che ti fa il tuo fornitore. Ogni prezzo successivo resta nella storia.",
    omatpage_meta: "I tuoi materiali edili con un prezzo e una storia delle variazioni. Inserisci una volta misure e resa, poi calcola con quelle. Senza account.",
    omat_add_t: "Nuovo materiale",
    omat_name: "Nome",
    omat_name_ph: "es. Gres 60×60 del mio fornitore",
    omat_cat: "Categoria",
    omat_app: "A che cosa serve",
    omat_app_WALL_FLOOR_COVERING: "Rivestimenti di pareti e pavimenti",
    omat_app_DRYWALL_BOARDING: "Costruzione in cartongesso",
    omat_app_COATING: "Materiali da stendere",
    omat_app_PANEL_CUTTING: "Taglio di pannelli e lastre",
    omat_app_LINEAR_STOCK: "Profili, listelli, tubi, tondini",
    omat_f_widthMm: "Larghezza (mm)",
    omat_f_lengthMm: "Lunghezza (mm)",
    omat_f_kerfMm: "Spessore di taglio (mm)",
    omat_f_coveragePerUnitM2: "Resa per confezione (m²)",
    omat_f_packageAreaM2: "Superficie per confezione (m²)",
    omat_f_wastePercent: "Scorta (%)",
    omat_price: "Prezzo per confezione",
    omat_save: "Salva il materiale",
    omat_list_t: "I tuoi materiali",
    omat_hist_t: "Storia dei prezzi",
    omat_hist_note: "Ogni prezzo che inserisci resta con la sua data. Un nome o una misura cambiati non lasciano traccia: una riga porta una sola data di modifica.",
    omat_sync_note: "I materiali restano in questo browser. Dopo l'accesso fanno parte dell'account e li vede anche l'app.",
    omat_use_note: "Un materiale di questo elenco si sceglie in un calcolatore come una voce del catalogo.",
    omat_cur_note: "Un prezzo mantiene la valuta in cui è stato inserito. Nulla viene convertito a un cambio.",
  },
  nl: {
    omatpage_lead: "Bewaar een materiaal dat de catalogus niet heeft, met de prijs die jouw leverancier rekent. Elke latere prijs blijft in de geschiedenis staan.",
    omatpage_meta: "Je eigen bouwmaterialen met een prijs en een wijzigingsgeschiedenis. Vul de maten en het rendement één keer in en reken er daarna mee. Zonder account.",
    omat_add_t: "Nieuw materiaal",
    omat_name: "Naam",
    omat_name_ph: "bv. Keramische tegel 60×60 van mijn leverancier",
    omat_cat: "Categorie",
    omat_app: "Waar het voor is",
    omat_app_WALL_FLOOR_COVERING: "Wand- en vloerbekleding",
    omat_app_DRYWALL_BOARDING: "Gipswandbouw",
    omat_app_COATING: "Materiaal dat je aanbrengt",
    omat_app_PANEL_CUTTING: "Platen en panelen zagen",
    omat_app_LINEAR_STOCK: "Profielen, lijsten, buizen, staven",
    omat_f_widthMm: "Breedte (mm)",
    omat_f_lengthMm: "Lengte (mm)",
    omat_f_kerfMm: "Zaagsnede (mm)",
    omat_f_coveragePerUnitM2: "Rendement per verpakking (m²)",
    omat_f_packageAreaM2: "Oppervlak per verpakking (m²)",
    omat_f_wastePercent: "Marge (%)",
    omat_price: "Prijs per verpakking",
    omat_save: "Materiaal opslaan",
    omat_list_t: "Jouw materialen",
    omat_hist_t: "Prijsgeschiedenis",
    omat_hist_note: "Elke prijs die je invult wordt met zijn datum bewaard. Een gewijzigde naam of maat laat geen spoor na — een regel draagt één wijzigingsdatum.",
    omat_sync_note: "Materialen blijven in deze browser. Zodra je inlogt horen ze bij het account en ziet de app ze ook.",
    omat_use_note: "Een materiaal uit deze lijst kies je in een rekenmachine net als een regel uit de catalogus.",
    omat_cur_note: "Een prijs houdt de valuta waarin hij is ingevuld. Er wordt niets tegen een koers omgerekend.",
  },
  es: {
    omatpage_lead: "Guarda un material que el catálogo no tiene, con el precio que te hace tu proveedor. Cada precio posterior se queda en el historial.",
    omatpage_meta: "Tus propios materiales de construcción con un precio y un historial de cambios. Escribe una vez las medidas y el rendimiento y calcula con ellos. Sin cuenta.",
    omat_add_t: "Material nuevo",
    omat_name: "Nombre",
    omat_name_ph: "p. ej. Porcelánico 60×60 de mi proveedor",
    omat_cat: "Categoría",
    omat_app: "Para qué sirve",
    omat_app_WALL_FLOOR_COVERING: "Revestimientos de paredes y suelos",
    omat_app_DRYWALL_BOARDING: "Construcción con pladur",
    omat_app_COATING: "Materiales que se aplican",
    omat_app_PANEL_CUTTING: "Corte de tableros y planchas",
    omat_app_LINEAR_STOCK: "Perfiles, molduras, tubos, barras",
    omat_f_widthMm: "Anchura (mm)",
    omat_f_lengthMm: "Longitud (mm)",
    omat_f_kerfMm: "Grosor de corte (mm)",
    omat_f_coveragePerUnitM2: "Rendimiento por envase (m²)",
    omat_f_packageAreaM2: "Superficie por envase (m²)",
    omat_f_wastePercent: "Merma (%)",
    omat_price: "Precio por envase",
    omat_save: "Guardar el material",
    omat_list_t: "Tus materiales",
    omat_hist_t: "Historial de precios",
    omat_hist_note: "Cada precio que escribes se guarda con su fecha. Un nombre o una medida cambiados no dejan rastro: una fila lleva una sola fecha de cambio.",
    omat_sync_note: "Los materiales se quedan en este navegador. Al iniciar sesión forman parte de la cuenta y la app también los ve.",
    omat_use_note: "Un material de esta lista se elige en una calculadora igual que una entrada del catálogo.",
    omat_cur_note: "Un precio mantiene la moneda en la que se escribió. No se convierte nada a ningún cambio.",
  },
  fr: {
    omatpage_lead: "Enregistre un matériau que le catalogue n'a pas, au prix que pratique ton fournisseur. Chaque prix suivant reste dans l'historique.",
    omatpage_meta: "Tes propres matériaux de construction avec un prix et un historique. Saisis une fois les dimensions et le rendement, puis calcule avec. Sans compte.",
    omat_add_t: "Nouveau matériau",
    omat_name: "Nom",
    omat_name_ph: "p. ex. Grès 60×60 de mon fournisseur",
    omat_cat: "Catégorie",
    omat_app: "À quoi il sert",
    omat_app_WALL_FLOOR_COVERING: "Revêtements de murs et de sols",
    omat_app_DRYWALL_BOARDING: "Construction en placo",
    omat_app_COATING: "Matériaux que l'on applique",
    omat_app_PANEL_CUTTING: "Découpe de panneaux et de plaques",
    omat_app_LINEAR_STOCK: "Profilés, moulures, tubes, barres",
    omat_f_widthMm: "Largeur (mm)",
    omat_f_lengthMm: "Longueur (mm)",
    omat_f_kerfMm: "Trait de scie (mm)",
    omat_f_coveragePerUnitM2: "Rendement par emballage (m²)",
    omat_f_packageAreaM2: "Surface par emballage (m²)",
    omat_f_wastePercent: "Marge (%)",
    omat_price: "Prix par emballage",
    omat_save: "Enregistrer le matériau",
    omat_list_t: "Tes matériaux",
    omat_hist_t: "Historique des prix",
    omat_hist_note: "Chaque prix que tu saisis est gardé avec sa date. Un nom ou une dimension modifiés ne laissent pas de trace — une ligne porte une seule date de modification.",
    omat_sync_note: "Les matériaux restent dans ce navigateur. Une fois connecté, ils font partie du compte et l'application les voit aussi.",
    omat_use_note: "Un matériau de cette liste se choisit dans un calculateur comme une entrée du catalogue.",
    omat_cur_note: "Un prix garde la devise dans laquelle il a été saisi. Rien n'est converti à un taux.",
  },
};

/** Every key the page needs, so validate() can fail on a language missing one. */
export const OMAT_COPY_KEYS = Object.keys(OMAT_COPY.pl);
