/* LiczMat website — the words on the PDF export, in ten languages.
 *
 * Session 59, the second half of item **C6** of the parity audit: "Eksport PDF i własne
 * materiały — tylko w aplikacji." The app has had `PdfConfigScreen` and
 * `AndroidProjectPdfExporter` since long before this site existed.
 *
 * **Every string here is the app's own**, copied out of `app/src/main/res/values-<lang>/strings.xml`
 * in `3d-polednia/Materio` — the `pdf_*` keys of the configurator and the `pdfdoc_*` keys of
 * the document. Nothing was invented and nothing was translated: one module may not be
 * called two different things on the two products, which is the rule session 53 wrote down
 * when the app took this site's `cal_*` strings, and session 57 followed the other way for
 * the converter. All ten languages already existed there, which is also why this half of
 * C6 needed no translator.
 *
 * It sits in src/ rather than in assets/i18n-pages.js for the reason src/conv-copy.mjs
 * does: every page on this site downloads assets/i18n.<lang>.js, and 51 keys per language
 * that only the build and a reader of a printed page ever see is about 3 kB on every page
 * load for nothing. The whole document is server-rendered into /projekty/ and hidden, and
 * the browser fills in numbers rather than words — so there is no runtime half at all.
 *
 * Three strings carry Android's `%1$s`. The build splits each one at the token and puts a
 * <span> the script fills between the halves, so the sentence keeps its word order in
 * every language — "Projekt: X" and "Проект: X" are not the same shape as a label glued
 * to a value, and neither is Romanian's.
 *
 * scripts/test-copy.mjs reads this file alongside the dictionaries, so the six stop-slop
 * rules cover it exactly as they cover everything else a visitor can read.
 */

export const PDF_COPY = {
  pl: {
    pdf_title: "Eksport wyceny",
    pdf_doc_type: "Typ dokumentu",
    pdf_technical: "Raport techniczny",
    pdf_investor: "Wycena dla inwestora",
    pdf_project_data: "Dane projektu",
    pdf_project_name: "Nazwa projektu",
    pdf_date: "Data",
    pdf_contractor_data: "Dane wykonawcy",
    pdf_scope: "Zakres",
    pdf_materials: "Materiały",
    pdf_quantities: "Ilości",
    pdf_prices: "Ceny",
    pdf_total: "Łączny koszt",
    pdf_pricing: "Wycena inwestorska",
    pdf_labor: "Robocizna",
    pdf_labor_hours: "Liczba godzin",
    pdf_labor_rate: "Stawka za godzinę",
    pdf_margin: "Marża",
    pdf_margin_percent: "Marża (%)",
    pdf_vat: "VAT",
    pdf_vat_percent: "VAT (%)",
    pdf_optional: "Opcjonalne",
    pdf_notes: "Uwagi",
    pdf_notes_hint: "Treść uwag",
    pdf_estimate_number: "Numer wyceny",
    pdf_company: "Nazwa firmy",
    pdf_phone: "Telefon",
    pdf_email: "E-mail",
    pdf_generate: "Generuj i udostępnij",
    pdfdoc_subtitle_technical: "RAPORT TECHNICZNY",
    pdfdoc_subtitle_investor: "WYCENA MATERIAŁÓW",
    pdfdoc_project: "Projekt: %1$s",
    pdfdoc_date: "Data: %1$s",
    pdfdoc_estimate_no: "Wycena nr: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIAŁ",
    pdfdoc_col_qty: "ILOŚĆ",
    pdfdoc_col_value: "WARTOŚĆ",
    pdfdoc_no_estimations: "Brak wyliczeń.",
    pdfdoc_grand_total: "ŁĄCZNY KOSZT MATERIAŁÓW",
    pdfdoc_waste_total: "Łączny koszt odpadu: %1$s",
    pdfdoc_pricing_header: "WYCENA INWESTORSKA",
    pdfdoc_materials_net: "Materiały (netto)",
    pdfdoc_labor: "Robocizna",
    pdfdoc_margin: "Marża",
    pdfdoc_net_total: "Suma netto",
    pdfdoc_vat: "VAT",
    pdfdoc_gross_total: "Suma brutto",
    pdfdoc_notes: "Uwagi:",
    pdfdoc_notes_default: "Wycena obejmuje szacunkowe zapotrzebowanie na materiały.",
    pdfdoc_footer: "LiczMat — Policz. Zaplanuj. Zrealizuj.",
  },
  en: {
    pdf_title: "Export estimate",
    pdf_doc_type: "Document type",
    pdf_technical: "Technical report",
    pdf_investor: "Investor estimate",
    pdf_project_data: "Project data",
    pdf_project_name: "Project name",
    pdf_date: "Date",
    pdf_contractor_data: "Contractor data",
    pdf_scope: "Scope",
    pdf_materials: "Materials",
    pdf_quantities: "Quantities",
    pdf_prices: "Prices",
    pdf_total: "Total cost",
    pdf_pricing: "Investor pricing",
    pdf_labor: "Labour",
    pdf_labor_hours: "Hours",
    pdf_labor_rate: "Hourly rate",
    pdf_margin: "Margin",
    pdf_margin_percent: "Margin (%)",
    pdf_vat: "VAT",
    pdf_vat_percent: "VAT (%)",
    pdf_optional: "Optional",
    pdf_notes: "Notes",
    pdf_notes_hint: "Note text",
    pdf_estimate_number: "Estimate number",
    pdf_company: "Company name",
    pdf_phone: "Phone",
    pdf_email: "Email",
    pdf_generate: "Generate and share",
    pdfdoc_subtitle_technical: "TECHNICAL REPORT",
    pdfdoc_subtitle_investor: "MATERIAL ESTIMATE",
    pdfdoc_project: "Project: %1$s",
    pdfdoc_date: "Date: %1$s",
    pdfdoc_estimate_no: "Estimate no.: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIAL",
    pdfdoc_col_qty: "QTY",
    pdfdoc_col_value: "VALUE",
    pdfdoc_no_estimations: "No calculations.",
    pdfdoc_grand_total: "TOTAL MATERIAL COST",
    pdfdoc_waste_total: "Total waste cost: %1$s",
    pdfdoc_pricing_header: "INVESTOR PRICING",
    pdfdoc_materials_net: "Materials (net)",
    pdfdoc_labor: "Labour",
    pdfdoc_margin: "Margin",
    pdfdoc_net_total: "Net total",
    pdfdoc_vat: "VAT",
    pdfdoc_gross_total: "Gross total",
    pdfdoc_notes: "Notes:",
    pdfdoc_notes_default: "The estimate covers approximate material requirements.",
    pdfdoc_footer: "LiczMat — Count. Plan. Build.",
  },
  de: {
    pdf_title: "Angebot exportieren",
    pdf_doc_type: "Dokumenttyp",
    pdf_technical: "Technischer Bericht",
    pdf_investor: "Angebot für den Auftraggeber",
    pdf_project_data: "Projektdaten",
    pdf_project_name: "Projektname",
    pdf_date: "Datum",
    pdf_contractor_data: "Auftragnehmerdaten",
    pdf_scope: "Umfang",
    pdf_materials: "Materialien",
    pdf_quantities: "Mengen",
    pdf_prices: "Preise",
    pdf_total: "Gesamtkosten",
    pdf_pricing: "Investoren-Kalkulation",
    pdf_labor: "Arbeitslohn",
    pdf_labor_hours: "Stunden",
    pdf_labor_rate: "Stundensatz",
    pdf_margin: "Marge",
    pdf_margin_percent: "Marge (%)",
    pdf_vat: "MwSt.",
    pdf_vat_percent: "MwSt. (%)",
    pdf_optional: "Optional",
    pdf_notes: "Anmerkungen",
    pdf_notes_hint: "Anmerkungstext",
    pdf_estimate_number: "Angebotsnummer",
    pdf_company: "Firmenname",
    pdf_phone: "Telefon",
    pdf_email: "E-Mail",
    pdf_generate: "Erstellen und teilen",
    pdfdoc_subtitle_technical: "TECHNISCHER BERICHT",
    pdfdoc_subtitle_investor: "MATERIALKOSTENSCHÄTZUNG",
    pdfdoc_project: "Projekt: %1$s",
    pdfdoc_date: "Datum: %1$s",
    pdfdoc_estimate_no: "Angebot Nr.: %1$s",
    pdfdoc_phone: "Tel. %1$s",
    pdfdoc_col_material: "MATERIAL",
    pdfdoc_col_qty: "MENGE",
    pdfdoc_col_value: "WERT",
    pdfdoc_no_estimations: "Keine Berechnungen.",
    pdfdoc_grand_total: "GESAMTKOSTEN MATERIAL",
    pdfdoc_waste_total: "Gesamtverschnittkosten: %1$s",
    pdfdoc_pricing_header: "INVESTOREN-KALKULATION",
    pdfdoc_materials_net: "Material (netto)",
    pdfdoc_labor: "Arbeitslohn",
    pdfdoc_margin: "Marge",
    pdfdoc_net_total: "Nettosumme",
    pdfdoc_vat: "MwSt.",
    pdfdoc_gross_total: "Bruttosumme",
    pdfdoc_notes: "Anmerkungen:",
    pdfdoc_notes_default: "Die Schätzung umfasst den ungefähren Materialbedarf.",
    pdfdoc_footer: "LiczMat — Rechnen. Planen. Umsetzen.",
  },
  uk: {
    pdf_title: "Експортувати кошторис",
    pdf_doc_type: "Тип документа",
    pdf_technical: "Технічний звіт",
    pdf_investor: "Інвесторський кошторис",
    pdf_project_data: "Дані проєкту",
    pdf_project_name: "Назва проєкту",
    pdf_date: "Дата",
    pdf_contractor_data: "Дані підрядника",
    pdf_scope: "Обсяг",
    pdf_materials: "Матеріали",
    pdf_quantities: "Кількості",
    pdf_prices: "Ціни",
    pdf_total: "Загальна вартість",
    pdf_pricing: "Інвесторські ціни",
    pdf_labor: "Робота",
    pdf_labor_hours: "Години",
    pdf_labor_rate: "Погодинна ставка",
    pdf_margin: "Націнка",
    pdf_margin_percent: "Націнка (%)",
    pdf_vat: "ПДВ",
    pdf_vat_percent: "ПДВ (%)",
    pdf_optional: "Необов’язково",
    pdf_notes: "Примітки",
    pdf_notes_hint: "Текст примітки",
    pdf_estimate_number: "Номер кошторису",
    pdf_company: "Назва компанії",
    pdf_phone: "Телефон",
    pdf_email: "Ел. пошта",
    pdf_generate: "Створити й поділитися",
    pdfdoc_subtitle_technical: "ТЕХНІЧНИЙ ЗВІТ",
    pdfdoc_subtitle_investor: "КОШТОРИС МАТЕРІАЛІВ",
    pdfdoc_project: "Проєкт: %1$s",
    pdfdoc_date: "Дата: %1$s",
    pdfdoc_estimate_no: "№ кошторису: %1$s",
    pdfdoc_phone: "тел. %1$s",
    pdfdoc_col_material: "МАТЕРІАЛ",
    pdfdoc_col_qty: "К-СТЬ",
    pdfdoc_col_value: "ВАРТІСТЬ",
    pdfdoc_no_estimations: "Немає обчислень.",
    pdfdoc_grand_total: "ЗАГАЛЬНА ВАРТІСТЬ МАТЕРІАЛІВ",
    pdfdoc_waste_total: "Загальна вартість відходів: %1$s",
    pdfdoc_pricing_header: "ІНВЕСТОРСЬКІ ЦІНИ",
    pdfdoc_materials_net: "Матеріали (без ПДВ)",
    pdfdoc_labor: "Робота",
    pdfdoc_margin: "Націнка",
    pdfdoc_net_total: "Разом без ПДВ",
    pdfdoc_vat: "ПДВ",
    pdfdoc_gross_total: "Разом з ПДВ",
    pdfdoc_notes: "Примітки:",
    pdfdoc_notes_default: "Кошторис охоплює приблизну потребу в матеріалі.",
    pdfdoc_footer: "LiczMat — Порахуй. Сплануй. Зроби.",
  },
  cs: {
    pdf_title: "Exportovat rozpočet",
    pdf_doc_type: "Typ dokumentu",
    pdf_technical: "Technický protokol",
    pdf_investor: "Investorský rozpočet",
    pdf_project_data: "Údaje o projektu",
    pdf_project_name: "Název projektu",
    pdf_date: "Datum",
    pdf_contractor_data: "Údaje o zhotoviteli",
    pdf_scope: "Rozsah",
    pdf_materials: "Materiály",
    pdf_quantities: "Množství",
    pdf_prices: "Ceny",
    pdf_total: "Celkové náklady",
    pdf_pricing: "Investorské ceny",
    pdf_labor: "Práce",
    pdf_labor_hours: "Hodiny",
    pdf_labor_rate: "Hodinová sazba",
    pdf_margin: "Marže",
    pdf_margin_percent: "Marže (%)",
    pdf_vat: "DPH",
    pdf_vat_percent: "DPH (%)",
    pdf_optional: "Volitelné",
    pdf_notes: "Poznámky",
    pdf_notes_hint: "Text poznámky",
    pdf_estimate_number: "Číslo rozpočtu",
    pdf_company: "Název firmy",
    pdf_phone: "Telefon",
    pdf_email: "E-mail",
    pdf_generate: "Vytvořit a sdílet",
    pdfdoc_subtitle_technical: "TECHNICKÝ PROTOKOL",
    pdfdoc_subtitle_investor: "ROZPOČET MATERIÁLU",
    pdfdoc_project: "Projekt: %1$s",
    pdfdoc_date: "Datum: %1$s",
    pdfdoc_estimate_no: "Číslo rozpočtu: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIÁL",
    pdfdoc_col_qty: "MNOŽ.",
    pdfdoc_col_value: "HODNOTA",
    pdfdoc_no_estimations: "Žádné výpočty.",
    pdfdoc_grand_total: "CELKOVÉ NÁKLADY NA MATERIÁL",
    pdfdoc_waste_total: "Celkové náklady na odpad: %1$s",
    pdfdoc_pricing_header: "INVESTORSKÉ CENY",
    pdfdoc_materials_net: "Materiály (bez DPH)",
    pdfdoc_labor: "Práce",
    pdfdoc_margin: "Marže",
    pdfdoc_net_total: "Celkem bez DPH",
    pdfdoc_vat: "DPH",
    pdfdoc_gross_total: "Celkem s DPH",
    pdfdoc_notes: "Poznámky:",
    pdfdoc_notes_default: "Rozpočet zahrnuje přibližnou potřebu materiálu.",
    pdfdoc_footer: "LiczMat — Spočítej. Naplánuj. Realizuj.",
  },
  sk: {
    pdf_title: "Exportovať rozpočet",
    pdf_doc_type: "Typ dokumentu",
    pdf_technical: "Technický protokol",
    pdf_investor: "Investorský rozpočet",
    pdf_project_data: "Údaje o projekte",
    pdf_project_name: "Názov projektu",
    pdf_date: "Dátum",
    pdf_contractor_data: "Údaje o zhotoviteľovi",
    pdf_scope: "Rozsah",
    pdf_materials: "Materiály",
    pdf_quantities: "Množstvá",
    pdf_prices: "Ceny",
    pdf_total: "Celkové náklady",
    pdf_pricing: "Investorské ceny",
    pdf_labor: "Práca",
    pdf_labor_hours: "Hodiny",
    pdf_labor_rate: "Hodinová sadzba",
    pdf_margin: "Marža",
    pdf_margin_percent: "Marža (%)",
    pdf_vat: "DPH",
    pdf_vat_percent: "DPH (%)",
    pdf_optional: "Voliteľné",
    pdf_notes: "Poznámky",
    pdf_notes_hint: "Text poznámky",
    pdf_estimate_number: "Číslo rozpočtu",
    pdf_company: "Názov firmy",
    pdf_phone: "Telefón",
    pdf_email: "E-mail",
    pdf_generate: "Vytvoriť a zdieľať",
    pdfdoc_subtitle_technical: "TECHNICKÝ PROTOKOL",
    pdfdoc_subtitle_investor: "ROZPOČET MATERIÁLU",
    pdfdoc_project: "Projekt: %1$s",
    pdfdoc_date: "Dátum: %1$s",
    pdfdoc_estimate_no: "Číslo rozpočtu: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIÁL",
    pdfdoc_col_qty: "MNOŽ.",
    pdfdoc_col_value: "HODNOTA",
    pdfdoc_no_estimations: "Žiadne výpočty.",
    pdfdoc_grand_total: "CELKOVÉ NÁKLADY NA MATERIÁL",
    pdfdoc_waste_total: "Celkové náklady na odpad: %1$s",
    pdfdoc_pricing_header: "INVESTORSKÉ CENY",
    pdfdoc_materials_net: "Materiály (bez DPH)",
    pdfdoc_labor: "Práca",
    pdfdoc_margin: "Marža",
    pdfdoc_net_total: "Spolu bez DPH",
    pdfdoc_vat: "DPH",
    pdfdoc_gross_total: "Spolu s DPH",
    pdfdoc_notes: "Poznámky:",
    pdfdoc_notes_default: "Rozpočet zahŕňa približnú potrebu materiálu.",
    pdfdoc_footer: "LiczMat — Spočítaj. Naplánuj. Realizuj.",
  },
  ro: {
    pdf_title: "Exportă devizul",
    pdf_doc_type: "Tip de document",
    pdf_technical: "Raport tehnic",
    pdf_investor: "Deviz pentru investitor",
    pdf_project_data: "Date despre proiect",
    pdf_project_name: "Numele proiectului",
    pdf_date: "Data",
    pdf_contractor_data: "Date despre executant",
    pdf_scope: "Domeniu",
    pdf_materials: "Materiale",
    pdf_quantities: "Cantități",
    pdf_prices: "Prețuri",
    pdf_total: "Cost total",
    pdf_pricing: "Prețuri pentru investitor",
    pdf_labor: "Manoperă",
    pdf_labor_hours: "Ore",
    pdf_labor_rate: "Tarif orar",
    pdf_margin: "Marjă",
    pdf_margin_percent: "Marjă (%)",
    pdf_vat: "TVA",
    pdf_vat_percent: "TVA (%)",
    pdf_optional: "Opțional",
    pdf_notes: "Note",
    pdf_notes_hint: "Textul notei",
    pdf_estimate_number: "Numărul devizului",
    pdf_company: "Numele firmei",
    pdf_phone: "Telefon",
    pdf_email: "E-mail",
    pdf_generate: "Generează și distribuie",
    pdfdoc_subtitle_technical: "RAPORT TEHNIC",
    pdfdoc_subtitle_investor: "DEVIZ DE MATERIALE",
    pdfdoc_project: "Proiect: %1$s",
    pdfdoc_date: "Data: %1$s",
    pdfdoc_estimate_no: "Nr. deviz: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIAL",
    pdfdoc_col_qty: "CANT.",
    pdfdoc_col_value: "VALOARE",
    pdfdoc_no_estimations: "Niciun calcul.",
    pdfdoc_grand_total: "COST TOTAL AL MATERIALELOR",
    pdfdoc_waste_total: "Cost total al pierderilor: %1$s",
    pdfdoc_pricing_header: "PREȚURI PENTRU INVESTITOR",
    pdfdoc_materials_net: "Materiale (fără TVA)",
    pdfdoc_labor: "Manoperă",
    pdfdoc_margin: "Marjă",
    pdfdoc_net_total: "Total fără TVA",
    pdfdoc_vat: "TVA",
    pdfdoc_gross_total: "Total cu TVA",
    pdfdoc_notes: "Note:",
    pdfdoc_notes_default: "Devizul acoperă necesarul aproximativ de material.",
    pdfdoc_footer: "LiczMat — Calculează. Planifică. Realizează.",
  },
  hr: {
    pdf_title: "Izvezi troškovnik",
    pdf_doc_type: "Vrsta dokumenta",
    pdf_technical: "Tehnički izvještaj",
    pdf_investor: "Investitorski troškovnik",
    pdf_project_data: "Podaci o projektu",
    pdf_project_name: "Naziv projekta",
    pdf_date: "Datum",
    pdf_contractor_data: "Podaci o izvođaču",
    pdf_scope: "Opseg",
    pdf_materials: "Materijali",
    pdf_quantities: "Količine",
    pdf_prices: "Cijene",
    pdf_total: "Ukupni trošak",
    pdf_pricing: "Investitorske cijene",
    pdf_labor: "Rad",
    pdf_labor_hours: "Sati",
    pdf_labor_rate: "Satnica",
    pdf_margin: "Marža",
    pdf_margin_percent: "Marža (%)",
    pdf_vat: "PDV",
    pdf_vat_percent: "PDV (%)",
    pdf_optional: "Neobavezno",
    pdf_notes: "Napomene",
    pdf_notes_hint: "Tekst napomene",
    pdf_estimate_number: "Broj troškovnika",
    pdf_company: "Naziv tvrtke",
    pdf_phone: "Telefon",
    pdf_email: "E-pošta",
    pdf_generate: "Generiraj i podijeli",
    pdfdoc_subtitle_technical: "TEHNIČKI IZVJEŠTAJ",
    pdfdoc_subtitle_investor: "TROŠKOVNIK MATERIJALA",
    pdfdoc_project: "Projekt: %1$s",
    pdfdoc_date: "Datum: %1$s",
    pdfdoc_estimate_no: "Br. troškovnika: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIJAL",
    pdfdoc_col_qty: "KOL.",
    pdfdoc_col_value: "VRIJEDNOST",
    pdfdoc_no_estimations: "Nema izračuna.",
    pdfdoc_grand_total: "UKUPNI TROŠAK MATERIJALA",
    pdfdoc_waste_total: "Ukupni trošak otpada: %1$s",
    pdfdoc_pricing_header: "INVESTITORSKE CIJENE",
    pdfdoc_materials_net: "Materijali (bez PDV-a)",
    pdfdoc_labor: "Rad",
    pdfdoc_margin: "Marža",
    pdfdoc_net_total: "Ukupno bez PDV-a",
    pdfdoc_vat: "PDV",
    pdfdoc_gross_total: "Ukupno s PDV-om",
    pdfdoc_notes: "Napomene:",
    pdfdoc_notes_default: "Troškovnik obuhvaća približnu potrebu za materijalom.",
    pdfdoc_footer: "LiczMat — Izračunaj. Isplaniraj. Izvedi.",
  },
  sr: {
    pdf_title: "Izvezi predračun",
    pdf_doc_type: "Vrsta dokumenta",
    pdf_technical: "Tehnički izveštaj",
    pdf_investor: "Investitorski predračun",
    pdf_project_data: "Podaci o projektu",
    pdf_project_name: "Naziv projekta",
    pdf_date: "Datum",
    pdf_contractor_data: "Podaci o izvođaču",
    pdf_scope: "Obim",
    pdf_materials: "Materijali",
    pdf_quantities: "Količine",
    pdf_prices: "Cene",
    pdf_total: "Ukupni trošak",
    pdf_pricing: "Investitorske cene",
    pdf_labor: "Rad",
    pdf_labor_hours: "Sati",
    pdf_labor_rate: "Satnica",
    pdf_margin: "Marža",
    pdf_margin_percent: "Marža (%)",
    pdf_vat: "PDV",
    pdf_vat_percent: "PDV (%)",
    pdf_optional: "Opciono",
    pdf_notes: "Napomene",
    pdf_notes_hint: "Tekst napomene",
    pdf_estimate_number: "Broj predračuna",
    pdf_company: "Naziv firme",
    pdf_phone: "Telefon",
    pdf_email: "E-pošta",
    pdf_generate: "Generiši i podeli",
    pdfdoc_subtitle_technical: "TEHNIČKI IZVEŠTAJ",
    pdfdoc_subtitle_investor: "PREDRAČUN MATERIJALA",
    pdfdoc_project: "Projekat: %1$s",
    pdfdoc_date: "Datum: %1$s",
    pdfdoc_estimate_no: "Br. predračuna: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIJAL",
    pdfdoc_col_qty: "KOL.",
    pdfdoc_col_value: "VREDNOST",
    pdfdoc_no_estimations: "Nema izračuna.",
    pdfdoc_grand_total: "UKUPNI TROŠAK MATERIJALA",
    pdfdoc_waste_total: "Ukupni trošak otpada: %1$s",
    pdfdoc_pricing_header: "INVESTITORSKE CENE",
    pdfdoc_materials_net: "Materijali (bez PDV-a)",
    pdfdoc_labor: "Rad",
    pdfdoc_margin: "Marža",
    pdfdoc_net_total: "Ukupno bez PDV-a",
    pdfdoc_vat: "PDV",
    pdfdoc_gross_total: "Ukupno sa PDV-om",
    pdfdoc_notes: "Napomene:",
    pdfdoc_notes_default: "Predračun obuhvata približnu potrebu za materijalom.",
    pdfdoc_footer: "LiczMat — Izračunaj. Isplaniraj. Izvedi.",
  },
  it: {
    pdf_title: "Esporta il preventivo",
    pdf_doc_type: "Tipo di documento",
    pdf_technical: "Relazione tecnica",
    pdf_investor: "Preventivo per il committente",
    pdf_project_data: "Dati del progetto",
    pdf_project_name: "Nome del progetto",
    pdf_date: "Data",
    pdf_contractor_data: "Dati dell'impresa",
    pdf_scope: "Contenuto",
    pdf_materials: "Materiali",
    pdf_quantities: "Quantità",
    pdf_prices: "Prezzi",
    pdf_total: "Costo totale",
    pdf_pricing: "Calcolo per il committente",
    pdf_labor: "Manodopera",
    pdf_labor_hours: "Ore",
    pdf_labor_rate: "Tariffa oraria",
    pdf_margin: "Margine",
    pdf_margin_percent: "Margine (%)",
    pdf_vat: "IVA",
    pdf_vat_percent: "IVA (%)",
    pdf_optional: "Facoltativo",
    pdf_notes: "Note",
    pdf_notes_hint: "Testo della nota",
    pdf_estimate_number: "Numero del preventivo",
    pdf_company: "Nome dell'impresa",
    pdf_phone: "Telefono",
    pdf_email: "E-mail",
    pdf_generate: "Genera e condividi",
    pdfdoc_subtitle_technical: "RELAZIONE TECNICA",
    pdfdoc_subtitle_investor: "PREVENTIVO DEI MATERIALI",
    pdfdoc_project: "Progetto: %1$s",
    pdfdoc_date: "Data: %1$s",
    pdfdoc_estimate_no: "Preventivo n.: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIALE",
    pdfdoc_col_qty: "Q.TÀ",
    pdfdoc_col_value: "IMPORTO",
    pdfdoc_no_estimations: "Nessun calcolo.",
    pdfdoc_grand_total: "COSTO TOTALE DEI MATERIALI",
    pdfdoc_waste_total: "Costo totale dello scarto: %1$s",
    pdfdoc_pricing_header: "CALCOLO PER IL COMMITTENTE",
    pdfdoc_materials_net: "Materiali (netto)",
    pdfdoc_labor: "Manodopera",
    pdfdoc_margin: "Margine",
    pdfdoc_net_total: "Totale netto",
    pdfdoc_vat: "IVA",
    pdfdoc_gross_total: "Totale lordo",
    pdfdoc_notes: "Note:",
    pdfdoc_notes_default: "Il preventivo copre il fabbisogno approssimativo di materiale.",
    pdfdoc_footer: "LiczMat — Calcola. Pianifica. Realizza.",
  },
  nl: {
    pdf_title: "Raming exporteren",
    pdf_doc_type: "Soort document",
    pdf_technical: "Technisch rapport",
    pdf_investor: "Raming voor de opdrachtgever",
    pdf_project_data: "Projectgegevens",
    pdf_project_name: "Naam van het project",
    pdf_date: "Datum",
    pdf_contractor_data: "Gegevens van de aannemer",
    pdf_scope: "Inhoud",
    pdf_materials: "Materialen",
    pdf_quantities: "Aantallen",
    pdf_prices: "Prijzen",
    pdf_total: "Totale kosten",
    pdf_pricing: "Berekening voor de opdrachtgever",
    pdf_labor: "Arbeid",
    pdf_labor_hours: "Uren",
    pdf_labor_rate: "Uurtarief",
    pdf_margin: "Marge",
    pdf_margin_percent: "Marge (%)",
    pdf_vat: "Btw",
    pdf_vat_percent: "Btw (%)",
    pdf_optional: "Optioneel",
    pdf_notes: "Notities",
    pdf_notes_hint: "Tekst van de notitie",
    pdf_estimate_number: "Nummer van de raming",
    pdf_company: "Naam van het bedrijf",
    pdf_phone: "Telefoon",
    pdf_email: "E-mail",
    pdf_generate: "Maken en delen",
    pdfdoc_subtitle_technical: "TECHNISCH RAPPORT",
    pdfdoc_subtitle_investor: "MATERIAALRAMING",
    pdfdoc_project: "Project: %1$s",
    pdfdoc_date: "Datum: %1$s",
    pdfdoc_estimate_no: "Raming nr.: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIAAL",
    pdfdoc_col_qty: "AANTAL",
    pdfdoc_col_value: "BEDRAG",
    pdfdoc_no_estimations: "Geen berekeningen.",
    pdfdoc_grand_total: "TOTALE MATERIAALKOSTEN",
    pdfdoc_waste_total: "Totale kosten van het afval: %1$s",
    pdfdoc_pricing_header: "BEREKENING VOOR DE OPDRACHTGEVER",
    pdfdoc_materials_net: "Materialen (netto)",
    pdfdoc_labor: "Arbeid",
    pdfdoc_margin: "Marge",
    pdfdoc_net_total: "Totaal netto",
    pdfdoc_vat: "Btw",
    pdfdoc_gross_total: "Totaal bruto",
    pdfdoc_notes: "Notities:",
    pdfdoc_notes_default: "De raming dekt de globale materiaalbehoefte.",
    pdfdoc_footer: "LiczMat — Reken. Plan. Bouw.",
  },
  es: {
    pdf_title: "Exportar el presupuesto",
    pdf_doc_type: "Tipo de documento",
    pdf_technical: "Informe técnico",
    pdf_investor: "Presupuesto para el cliente",
    pdf_project_data: "Datos del proyecto",
    pdf_project_name: "Nombre del proyecto",
    pdf_date: "Fecha",
    pdf_contractor_data: "Datos de la empresa",
    pdf_scope: "Contenido",
    pdf_materials: "Materiales",
    pdf_quantities: "Cantidades",
    pdf_prices: "Precios",
    pdf_total: "Coste total",
    pdf_pricing: "Cálculo para el cliente",
    pdf_labor: "Mano de obra",
    pdf_labor_hours: "Horas",
    pdf_labor_rate: "Precio por hora",
    pdf_margin: "Margen",
    pdf_margin_percent: "Margen (%)",
    pdf_vat: "IVA",
    pdf_vat_percent: "IVA (%)",
    pdf_optional: "Opcional",
    pdf_notes: "Notas",
    pdf_notes_hint: "Texto de la nota",
    pdf_estimate_number: "Número del presupuesto",
    pdf_company: "Nombre de la empresa",
    pdf_phone: "Teléfono",
    pdf_email: "Correo",
    pdf_generate: "Generar y compartir",
    pdfdoc_subtitle_technical: "INFORME TÉCNICO",
    pdfdoc_subtitle_investor: "PRESUPUESTO DE MATERIALES",
    pdfdoc_project: "Proyecto: %1$s",
    pdfdoc_date: "Fecha: %1$s",
    pdfdoc_estimate_no: "Presupuesto n.º: %1$s",
    pdfdoc_phone: "tel. %1$s",
    pdfdoc_col_material: "MATERIAL",
    pdfdoc_col_qty: "CANT.",
    pdfdoc_col_value: "IMPORTE",
    pdfdoc_no_estimations: "Sin cálculos.",
    pdfdoc_grand_total: "COSTE TOTAL DE LOS MATERIALES",
    pdfdoc_waste_total: "Coste total del desperdicio: %1$s",
    pdfdoc_pricing_header: "CÁLCULO PARA EL CLIENTE",
    pdfdoc_materials_net: "Materiales (neto)",
    pdfdoc_labor: "Mano de obra",
    pdfdoc_margin: "Margen",
    pdfdoc_net_total: "Total neto",
    pdfdoc_vat: "IVA",
    pdfdoc_gross_total: "Total bruto",
    pdfdoc_notes: "Notas:",
    pdfdoc_notes_default: "El presupuesto cubre la necesidad aproximada de material.",
    pdfdoc_footer: "LiczMat — Calcula. Planifica. Construye.",
  },
  fr: {
    pdf_title: "Exporter le devis",
    pdf_doc_type: "Type de document",
    pdf_technical: "Rapport technique",
    pdf_investor: "Devis pour le client",
    pdf_project_data: "Données du projet",
    pdf_project_name: "Nom du projet",
    pdf_date: "Date",
    pdf_contractor_data: "Données de l'entreprise",
    pdf_scope: "Contenu",
    pdf_materials: "Matériaux",
    pdf_quantities: "Quantités",
    pdf_prices: "Prix",
    pdf_total: "Coût total",
    pdf_pricing: "Chiffrage pour le client",
    pdf_labor: "Main-d'œuvre",
    pdf_labor_hours: "Heures",
    pdf_labor_rate: "Taux horaire",
    pdf_margin: "Marge",
    pdf_margin_percent: "Marge (%)",
    pdf_vat: "TVA",
    pdf_vat_percent: "TVA (%)",
    pdf_optional: "Facultatif",
    pdf_notes: "Notes",
    pdf_notes_hint: "Texte de la note",
    pdf_estimate_number: "Numéro du devis",
    pdf_company: "Nom de l'entreprise",
    pdf_phone: "Téléphone",
    pdf_email: "E-mail",
    pdf_generate: "Générer et partager",
    pdfdoc_subtitle_technical: "RAPPORT TECHNIQUE",
    pdfdoc_subtitle_investor: "DEVIS DES MATÉRIAUX",
    pdfdoc_project: "Projet : %1$s",
    pdfdoc_date: "Date : %1$s",
    pdfdoc_estimate_no: "Devis n° : %1$s",
    pdfdoc_phone: "tél. %1$s",
    pdfdoc_col_material: "MATÉRIAU",
    pdfdoc_col_qty: "QTÉ",
    pdfdoc_col_value: "MONTANT",
    pdfdoc_no_estimations: "Aucun calcul.",
    pdfdoc_grand_total: "COÛT TOTAL DES MATÉRIAUX",
    pdfdoc_waste_total: "Coût total des chutes : %1$s",
    pdfdoc_pricing_header: "CHIFFRAGE POUR LE CLIENT",
    pdfdoc_materials_net: "Matériaux (net)",
    pdfdoc_labor: "Main-d'œuvre",
    pdfdoc_margin: "Marge",
    pdfdoc_net_total: "Total net",
    pdfdoc_vat: "TVA",
    pdfdoc_gross_total: "Total TTC",
    pdfdoc_notes: "Notes :",
    pdfdoc_notes_default: "Le devis couvre le besoin approximatif en matériaux.",
    pdfdoc_footer: "LiczMat — Calcule. Planifie. Réalise.",
  },
};

/** Every key the page needs, so validate() can fail on a language missing one. */
export const PDF_COPY_KEYS = Object.keys(PDF_COPY.pl);

/**
 * Android's `%1$s` split into the halves either side of it.
 *
 * "Projekt: %1$s" is a sentence with a hole in it, and the hole is not always at the end:
 * gluing a label to a value would put the Romanian and Ukrainian words in the wrong order.
 * The build writes `before` + a <span> the script fills + `after`.
 */
export function pdfSplit(text) {
  const i = String(text).indexOf("%1$s");
  if (i < 0) return { before: String(text), after: "" };
  return { before: String(text).slice(0, i), after: String(text).slice(i + 4) };
}
