/* LiczMat website: the words on the LiczMat Pro page, in thirteen languages.
 *
 * 2026-10-04, the page the owner picked from three proposals (variant B, with the
 * three-tier comparison of variant C). It sits in src/ for the reason src/conv-copy.mjs
 * does: the page is localized, one URL per language, so nothing on it is re-translated in
 * the browser, and copy only the build reads has no business in assets/i18n.<lang>.js,
 * which every page on the site downloads.
 *
 * Keys still read from the dictionary on purpose: `pro_t` (the header and footer label of
 * the route), `pay_monthly_per`, `pay_yearly_per` and `pay_soon` (assets/paywall.js and
 * /app/ print the same words), `cli_pro_yours`.
 *
 * The `x_*` keys are the sample job the three product fragments show (the quote PDF, the
 * quote editor and the calendar). scripts/pro-samples.mjs renders those fragments with our
 * own code from these values; they are an example, and the page labels them as one only
 * through the job itself: a client, a bathroom, a date.
 */

export const PRO_COPY = {
  pl: {
    meta: "LiczMat Pro: wyceny z wyników kalkulatora, klienci, terminarz, PDF z logo firmy i link do wyceny dla klienta. Każde nowe konto ma 14 dni za darmo.",
    lead: "Wyceny, klienci i terminy na projektach, które liczysz w kalkulatorach.",
    buy: "Wykup LiczMat Pro",
    trial: "14 dni za darmo",
    f1_t: "Wycena z kalkulatora",
    f1_d: "Materiały z projektu trafiają do wyceny same.",
    f2_t: "PDF z logo firmy",
    f2_d: "Dane firmy wpisujesz raz, w zakładce Moja firma.",
    f3_t: "Link dla klienta",
    f3_d: "Klient otwiera wycenę w przeglądarce, bez konta.",
    f4_t: "Także na Androidzie",
    f4_d: "Klienci i wyceny są na koncie, więc widzisz je też w aplikacji.",
    k_client: "Klient",
    k_date: "Termin",
    s1_t: "Klient",
    s1_d: "Dane kontaktowe i notatki przy kliencie.",
    s2_t: "Projekt",
    s2_d: "Wyniki z kalkulatorów są już w projekcie.",
    s3_t: "Wycena",
    s3_d: "Dopisujesz robociznę, koszty, marżę i VAT.",
    s4_t: "PDF albo link",
    s4_d: "Klient dostaje gotową wycenę.",
    q_h: "Wycena liczy się z projektu",
    q_d: "Materiały i koszty przychodzą z projektu. Ty dopisujesz robociznę, marżę i VAT, a suma liczy się sama.",
    q_1: "Ceny jednostkowe i wartości pozycji",
    q_2: "Robocizna i dodatkowe koszty",
    q_3: "Marża i VAT",
    q_4: "PDF z danymi firmy i logo",
    c_h: "Klienci, historia i terminarz",
    c_d: "Przy kliencie widzisz jego projekty, wyceny i historię. Termin projektu od razu stoi w terminarzu.",
    c_1: "Dane kontaktowe i notatki",
    c_2: "Projekty i wyceny klienta",
    c_3: "Historia współpracy",
    c_4: "Terminy projektów w kalendarzu",
    p_h: "Ile kosztuje",
    p_month: "Miesięcznie",
    p_year: "Rocznie",
    p_guest: "Bez konta",
    p_free: "Darmowe konto",
    p_nofee: "bez opłat",
    p_guest_1: "Wszystkie kalkulatory",
    p_guest_2: "Katalog materiałów",
    p_guest_3: "Konwerter jednostek",
    p_free_1: "Wszystko, co bez konta",
    p_free_2: "Projekty i pomieszczenia",
    p_free_3: "Zapisane kalkulacje",
    p_free_4: "Lista zakupów bez cen",
    p_free_5: "Synchronizacja z telefonem",
    p_pro_1: "Wszystko z darmowego konta",
    p_pro_2: "Klienci i historia współpracy",
    p_pro_3: "Wyceny z robocizną, marżą i VAT",
    p_pro_4: "PDF z logo firmy",
    p_pro_5: "Link do wyceny online",
    p_pro_6: "Ceny i koszty w projektach",
    p_pro_7: "Terminarz",
    p_open_calc: "Otwórz kalkulatory",
    p_signup: "Załóż konto",
    p_trial_line: "albo 14 dni za darmo, bez karty",
    p_pay_line: "Płatność przez Stripe: karta, Apple Pay, Link albo Klarna. Anulujesz kiedy chcesz, a Pro działa do końca opłaconego okresu.",
    p_yours: "Masz LiczMat Pro. Plan i płatności są w Twoim koncie.",
    p_account: "Moje konto",
    t_h: "Porównanie szczegółowe",
    t_feature: "Funkcja",
    g_count: "Liczenie",
    g_projects: "Projekty",
    g_money: "Pieniądze",
    g_work: "Klienci i praca",
    g_docs: "Dokumenty",
    r_calcs: "Wszystkie kalkulatory",
    r_materials: "Katalog materiałów",
    r_converter: "Konwerter jednostek",
    r_projects: "Projekty i pomieszczenia",
    r_saved: "Zapisane kalkulacje",
    r_shopping: "Lista zakupów bez cen",
    r_sync: "Synchronizacja z telefonem",
    r_prices: "Ceny jednostkowe i wartości",
    r_waste: "Koszt odpadu i sumy",
    r_quotes: "Wyceny z marżą i robocizną",
    r_vat: "VAT w wycenie",
    r_clients: "Klienci i dane kontaktowe",
    r_calendar: "Terminarz projektów",
    r_history: "Historia współpracy",
    r_pdf: "PDF z logo firmy",
    r_link: "Link do wyceny online",
    t_yes: "jest",
    t_no: "nie ma",
    b_h: "Zanim kupisz",
    b_1: "Anulujesz kiedy chcesz. Pro działa do końca opłaconego okresu.",
    b_2: "Gdy Pro wygaśnie, nic nie ginie: klienci, wyceny i kwoty zostają na koncie i wracają po wznowieniu.",
    b_3: "Ceny są w siedmiu walutach. Walutę płatności Stripe dobiera do kraju, z którego płacisz.",
    b_4: "Pro nie wystawia faktur i nie prowadzi magazynu ani kadr. Terminarz nie wysyła powiadomień.",
    x_firm: "Remonty Nowicki",
    x_firm_street: "ul. Zielna 4",
    x_firm_postal: "30-001",
    x_firm_city: "Kraków",
    x_firm_phone: "600 418 220",
    x_firm_email: "biuro@remontynowicki.pl",
    x_client: "Anna Nowak",
    x_street: "ul. Długa 12",
    x_postal: "31-147",
    x_city: "Kraków",
    x_phone: "512 304 118",
    x_project: "Łazienka, ul. Długa 12",
    x_project2: "Malowanie salonu",
    x_project3: "Kuchnia, płytki nad blatem",
    x_project4: "Taras",
    x_client2: "Piotr Kowalski",
    x_client3: "Marta Zielińska",
    x_quote: "Łazienka, wycena",
    x_room: "Łazienka",
    x_mat1: "Gres 60×60 cm",
    x_mat2: "Klej do płytek",
    x_mat3: "Fuga",
    x_other: "Transport",
    x_labour: "Układanie płytek",
    x_unit_pack: "opak.",
    x_unit_bag: "op.",
  },
  uk: {
    meta: "LiczMat Pro: кошториси з результатів калькулятора, клієнти, календар, PDF з логотипом фірми та посилання на кошторис для клієнта. Кожен новий акаунт має 14 днів безкоштовно.",
    lead: "Кошториси, клієнти та терміни в проєктах, які ти рахуєш у калькуляторах.",
    buy: "Купити LiczMat Pro",
    trial: "14 днів безкоштовно",
    f1_t: "Кошторис з калькулятора",
    f1_d: "Матеріали з проєкту потрапляють у кошторис самі.",
    f2_t: "PDF з логотипом фірми",
    f2_d: "Дані фірми ти вписуєш один раз, у вкладці Моя фірма.",
    f3_t: "Посилання для клієнта",
    f3_d: "Клієнт відкриває кошторис у браузері, без акаунта.",
    f4_t: "Також на Android",
    f4_d: "Клієнти та кошториси є на акаунті, тому ти бачиш їх також у додатку.",
    k_client: "Клієнт",
    k_date: "Термін",
    s1_t: "Клієнт",
    s1_d: "Контактні дані та нотатки при клієнті.",
    s2_t: "Проєкт",
    s2_d: "Результати з калькуляторів вже є у проєкті.",
    s3_t: "Кошторис",
    s3_d: "Дописуєш роботу, витрати, маржу та ПДВ.",
    s4_t: "PDF або посилання",
    s4_d: "Клієнт отримує готовий кошторис.",
    q_h: "Кошторис рахується з проєкту",
    q_d: "Матеріали та витрати приходять з проєкту. Ти дописуєш роботу, маржу та ПДВ, а сума рахується сама.",
    q_1: "Одиничні ціни та вартість позицій",
    q_2: "Робота та додаткові витрати",
    q_3: "Маржа та ПДВ",
    q_4: "PDF з даними фірми та логотипом",
    c_h: "Клієнти, історія та календар",
    c_d: "При клієнті ти бачиш його проєкти, кошториси та історію. Термін проєкту одразу стоїть у календарі.",
    c_1: "Контактні дані та нотатки",
    c_2: "Проєкти та кошториси клієнта",
    c_3: "Історія співпраці",
    c_4: "Терміни проєктів у календарі",
    p_h: "Скільки коштує",
    p_month: "Щомісяця",
    p_year: "Щорічно",
    p_guest: "Без акаунта",
    p_free: "Безкоштовний акаунт",
    p_nofee: "без оплат",
    p_guest_1: "Усі калькулятори",
    p_guest_2: "Каталог матеріалів",
    p_guest_3: "Конвертер одиниць",
    p_free_1: "Усе, що без акаунта",
    p_free_2: "Проєкти та приміщення",
    p_free_3: "Збережені розрахунки",
    p_free_4: "Список покупок без цін",
    p_free_5: "Синхронізація з телефоном",
    p_pro_1: "Усе з безкоштовного акаунта",
    p_pro_2: "Клієнти та історія співпраці",
    p_pro_3: "Кошториси з роботою, маржею та ПДВ",
    p_pro_4: "PDF з логотипом фірми",
    p_pro_5: "Посилання на онлайн кошторис",
    p_pro_6: "Ціни та витрати в проєктах",
    p_pro_7: "Календар",
    p_open_calc: "Відкрити калькулятори",
    p_signup: "Створити акаунт",
    p_trial_line: "або 14 днів безкоштовно, без картки",
    p_pay_line: "Оплата через Stripe: картка, Apple Pay, Link або Klarna. Скасовуєш коли хочеш, а Pro працює до кінця оплаченого періоду.",
    p_yours: "Маєш LiczMat Pro. План та оплати є у твоєму акаунті.",
    p_account: "Мій акаунт",
    t_h: "Детальне порівняння",
    t_feature: "Функція",
    g_count: "Рахування",
    g_projects: "Проєкти",
    g_money: "Гроші",
    g_work: "Клієнти та робота",
    g_docs: "Документи",
    r_calcs: "Усі калькулятори",
    r_materials: "Каталог матеріалів",
    r_converter: "Конвертер одиниць",
    r_projects: "Проєкти та приміщення",
    r_saved: "Збережені розрахунки",
    r_shopping: "Список покупок без цін",
    r_sync: "Синхронізація з телефоном",
    r_prices: "Одиничні ціни та вартості",
    r_waste: "Вартість відходів та суми",
    r_quotes: "Кошториси з маржею та роботою",
    r_vat: "ПДВ у кошторисі",
    r_clients: "Клієнти та контактні дані",
    r_calendar: "Календар проєктів",
    r_history: "Історія співпраці",
    r_pdf: "PDF з логотипом фірми",
    r_link: "Посилання на онлайн кошторис",
    t_yes: "є",
    t_no: "немає",
    b_h: "Перед покупкою",
    b_1: "Скасовуєш коли хочеш. Pro працює до кінця оплаченого періоду.",
    b_2: "Коли Pro закінчиться, нічого не зникає: клієнти, кошториси та суми залишаються на акаунті та повертаються після відновлення.",
    b_3: "Ціни вказані в 7 валютах. Stripe вибирає валюту оплати залежно від країни, з якої ти платиш.",
    b_4: "Pro не виставляє рахунки-фактури і не веде склад або кадри. Календар не надсилає сповіщення.",
    x_firm: "Ремонти Коваленко",
    x_firm_street: "вул. Шевченка 15",
    x_firm_postal: "01001",
    x_firm_city: "Київ",
    x_firm_phone: "050 123 4567",
    x_firm_email: "office@remonty-kovalenko.example",
    x_client: "Олена Шевченко",
    x_street: "вул. Франка 22",
    x_postal: "01030",
    x_city: "Київ",
    x_phone: "067 987 6543",
    x_project: "Ванна кімната, вул. Франка 22",
    x_project2: "Фарбування вітальні",
    x_project3: "Кухня, плитка над стільницею",
    x_project4: "Тераса",
    x_client2: "Іван Мельник",
    x_client3: "Марія Бойко",
    x_quote: "Ванна кімната, кошторис",
    x_room: "Ванна кімната",
    x_mat1: "Керамограніт 60×60 cm",
    x_mat2: "Клей для плитки",
    x_mat3: "Фуга",
    x_other: "Транспорт",
    x_labour: "Укладання плитки",
    x_unit_pack: "упак.",
    x_unit_bag: "міш.",
  },
  de: {
    meta: "LiczMat Pro: Angebote aus Rechnerergebnissen, Kunden, Kalender, PDF mit Firmenlogo und Angebotslink für den Kunden. Jedes neue Konto hat 14 Tage kostenlos.",
    lead: "Angebote, Kunden und Termine bei Projekten, die du im Rechner kalkulierst.",
    buy: "LiczMat Pro kaufen",
    trial: "14 Tage kostenlos",
    f1_t: "Angebot aus dem Rechner",
    f1_d: "Materialien aus dem Projekt landen direkt im Angebot.",
    f2_t: "PDF mit Firmenlogo",
    f2_d: "Firmendaten trägst du einmal ein, im Reiter Meine Firma.",
    f3_t: "Link für den Kunden",
    f3_d: "Der Kunde öffnet das Angebot im Browser, ohne Konto.",
    f4_t: "Auch auf Android",
    f4_d: "Kunden und Angebote sind im Konto, du siehst sie also auch in der App.",
    k_client: "Kunde",
    k_date: "Termin",
    s1_t: "Kunde",
    s1_d: "Kontaktdaten und Notizen beim Kunden.",
    s2_t: "Projekt",
    s2_d: "Ergebnisse aus den Rechnern sind schon im Projekt.",
    s3_t: "Angebot",
    s3_d: "Du trägst Arbeitskosten, Ausgaben, Marge und MwSt. ein.",
    s4_t: "PDF oder Link",
    s4_d: "Der Kunde bekommt das fertige Angebot.",
    q_h: "Das Angebot wird aus dem Projekt berechnet",
    q_d: "Materialien und Kosten kommen aus dem Projekt. Du trägst Arbeitskosten, Marge und MwSt. ein, die Summe wird automatisch berechnet.",
    q_1: "Stückpreise und Positionswerte",
    q_2: "Arbeitskosten und zusätzliche Ausgaben",
    q_3: "Marge und MwSt.",
    q_4: "PDF mit Firmendaten und Logo",
    c_h: "Kunden, Historie und Termine",
    c_d: "Beim Kunden siehst du seine Projekte, Angebote und Historie. Der Projekttermin steht direkt im Kalender.",
    c_1: "Kontaktdaten und Notizen",
    c_2: "Projekte und Angebote des Kunden",
    c_3: "Bisherige Zusammenarbeit",
    c_4: "Projekttermine im Kalender",
    p_h: "Was es kostet",
    p_month: "Monatlich",
    p_year: "Jährlich",
    p_guest: "Ohne Konto",
    p_free: "Kostenloses Konto",
    p_nofee: "ohne Gebühren",
    p_guest_1: "Alle Rechner",
    p_guest_2: "Materialkatalog",
    p_guest_3: "Einheitenumrechner",
    p_free_1: "Alles ohne Konto",
    p_free_2: "Projekte und Räume",
    p_free_3: "Gespeicherte Kalkulationen",
    p_free_4: "Einkaufsliste ohne Preise",
    p_free_5: "Synchronisation mit dem Telefon",
    p_pro_1: "Alles aus dem kostenlosen Konto",
    p_pro_2: "Kunden und bisherige Zusammenarbeit",
    p_pro_3: "Angebote mit Arbeitskosten, Marge und MwSt.",
    p_pro_4: "PDF mit Firmenlogo",
    p_pro_5: "Link zum Online-Angebot",
    p_pro_6: "Preise und Kosten in Projekten",
    p_pro_7: "Termine",
    p_open_calc: "Rechner öffnen",
    p_signup: "Konto erstellen",
    p_trial_line: "oder 14 Tage kostenlos, ohne Karte",
    p_pay_line: "Zahlung über Stripe: Karte, Apple Pay, Link oder Klarna. Du kündigst wann du willst, Pro läuft bis zum Ende des bezahlten Zeitraums.",
    p_yours: "Du hast LiczMat Pro. Tarif und Zahlungen sind in deinem Konto.",
    p_account: "Mein Konto",
    t_h: "Detaillierter Vergleich",
    t_feature: "Funktion",
    g_count: "Rechnen",
    g_projects: "Projekte",
    g_money: "Geld",
    g_work: "Kunden und Arbeit",
    g_docs: "Dokumente",
    r_calcs: "Alle Rechner",
    r_materials: "Materialkatalog",
    r_converter: "Einheitenumrechner",
    r_projects: "Projekte und Räume",
    r_saved: "Gespeicherte Kalkulationen",
    r_shopping: "Einkaufsliste ohne Preise",
    r_sync: "Synchronisation mit dem Telefon",
    r_prices: "Stückpreise und Werte",
    r_waste: "Verschnittkosten und Summen",
    r_quotes: "Angebote mit Marge und Arbeitskosten",
    r_vat: "MwSt. im Angebot",
    r_clients: "Kunden und Kontaktdaten",
    r_calendar: "Projektkalender",
    r_history: "Bisherige Zusammenarbeit",
    r_pdf: "PDF mit Firmenlogo",
    r_link: "Link zum Online-Angebot",
    t_yes: "ist",
    t_no: "fehlt",
    b_h: "Bevor du kaufst",
    b_1: "Du kündigst wann du willst. Pro läuft bis zum Ende des bezahlten Zeitraums.",
    b_2: "Wenn Pro abläuft, geht nichts verloren: Kunden, Angebote und Beträge bleiben im Konto und kehren nach Verlängerung zurück.",
    b_3: "Preise sind in 7 Währungen. Stripe wählt die Zahlungswährung nach dem Land, aus dem du bezahlst.",
    b_4: "Pro stellt keine Rechnungen aus und führt kein Lager oder Personal. Der Kalender sendet keine Benachrichtigungen.",
    x_firm: "Sanierung Weber",
    x_firm_street: "Hauptstraße 45",
    x_firm_postal: "10115",
    x_firm_city: "Berlin",
    x_firm_phone: "0151 2345678",
    x_firm_email: "buero@sanierung-weber.example",
    x_client: "Anna Müller",
    x_street: "Bergstraße 12",
    x_postal: "10405",
    x_city: "Berlin",
    x_phone: "0172 9876543",
    x_project: "Badezimmer, Bergstraße 12",
    x_project2: "Wohnzimmer streichen",
    x_project3: "Küche, Fliesen über Arbeitsplatte",
    x_project4: "Terrasse",
    x_client2: "Peter Schmidt",
    x_client3: "Martha Klein",
    x_quote: "Badezimmer, Angebot",
    x_room: "Badezimmer",
    x_mat1: "Feinsteinzeug 60×60 cm",
    x_mat2: "Fliesenkleber",
    x_mat3: "Fugenmörtel",
    x_other: "Transport",
    x_labour: "Fliesenlegen",
    x_unit_pack: "Pak.",
    x_unit_bag: "Sack",
  },
  en: {
    meta: "LiczMat Pro: quotes from calculator results, clients, calendar, PDF with company logo and a quote link for the client. Every new account gets 14 days for free.",
    lead: "Quotes, clients and deadlines for projects you calculate materials for.",
    buy: "Buy LiczMat Pro",
    trial: "14 days for free",
    f1_t: "Quote from calculator",
    f1_d: "Materials from the project go into the quote automatically.",
    f2_t: "PDF with company logo",
    f2_d: "You enter company details once, in the My company tab.",
    f3_t: "Link for the client",
    f3_d: "The client opens the quote in a browser, without an account.",
    f4_t: "Also on Android",
    f4_d: "Clients and quotes are in the account, so you see them in the app too.",
    k_client: "Client",
    k_date: "Date",
    s1_t: "Client",
    s1_d: "Contact details and notes on the client.",
    s2_t: "Project",
    s2_d: "Calculator results are already in the project.",
    s3_t: "Quote",
    s3_d: "You add labor, costs, margin and VAT.",
    s4_t: "PDF or link",
    s4_d: "The client gets the finished quote.",
    q_h: "The quote is calculated from the project",
    q_d: "Materials and costs come from the project. You add labor, margin and VAT, and the total is calculated automatically.",
    q_1: "Unit prices and item values",
    q_2: "Labor and extra costs",
    q_3: "Margin and VAT",
    q_4: "PDF with company details and logo",
    c_h: "Clients, history and schedule",
    c_d: "Next to the client you see their projects, quotes and history. The project date goes straight into the calendar.",
    c_1: "Contact details and notes",
    c_2: "Client's projects and quotes",
    c_3: "Work history",
    c_4: "Project dates in the calendar",
    p_h: "How much it costs",
    p_month: "Monthly",
    p_year: "Yearly",
    p_guest: "Without an account",
    p_free: "Free account",
    p_nofee: "no fees",
    p_guest_1: "All calculators",
    p_guest_2: "Materials catalog",
    p_guest_3: "Unit converter",
    p_free_1: "Everything available without an account",
    p_free_2: "Projects and rooms",
    p_free_3: "Saved calculations",
    p_free_4: "Shopping list without prices",
    p_free_5: "Sync with phone",
    p_pro_1: "Everything from the free account",
    p_pro_2: "Clients and work history",
    p_pro_3: "Quotes with labor, margin and VAT",
    p_pro_4: "PDF with company logo",
    p_pro_5: "Link to online quote",
    p_pro_6: "Prices and costs in projects",
    p_pro_7: "Schedule",
    p_open_calc: "Open calculators",
    p_signup: "Create account",
    p_trial_line: "or 14 days for free, no card",
    p_pay_line: "Payment via Stripe: card, Apple Pay, Link or Klarna. Cancel whenever you want, and Pro works until the end of the paid period.",
    p_yours: "You have LiczMat Pro. Plan and payments are in your account.",
    p_account: "My account",
    t_h: "Detailed comparison",
    t_feature: "Feature",
    g_count: "Calculating",
    g_projects: "Projects",
    g_money: "Money",
    g_work: "Clients and work",
    g_docs: "Documents",
    r_calcs: "All calculators",
    r_materials: "Materials catalog",
    r_converter: "Unit converter",
    r_projects: "Projects and rooms",
    r_saved: "Saved calculations",
    r_shopping: "Shopping list without prices",
    r_sync: "Sync with phone",
    r_prices: "Unit prices and values",
    r_waste: "Waste cost and sums",
    r_quotes: "Quotes with margin and labor",
    r_vat: "VAT in quote",
    r_clients: "Clients and contact details",
    r_calendar: "Project calendar",
    r_history: "Work history",
    r_pdf: "PDF with company logo",
    r_link: "Link to online quote",
    t_yes: "yes",
    t_no: "no",
    b_h: "Before you buy",
    b_1: "Cancel whenever you want. Pro works until the end of the paid period.",
    b_2: "When Pro expires, nothing is lost: clients, quotes and amounts stay on the account and return after renewal.",
    b_3: "Prices are in 7 currencies. Stripe picks the payment currency based on the country you pay from.",
    b_4: "Pro does not issue invoices and does not manage inventory or HR. The calendar does not send notifications.",
    x_firm: "Smith Renovations",
    x_firm_street: "124 Main St",
    x_firm_postal: "10001",
    x_firm_city: "New York",
    x_firm_phone: "212 555 1234",
    x_firm_email: "office@smith-renovations.example",
    x_client: "Anna Johnson",
    x_street: "45 Park Ave",
    x_postal: "10016",
    x_city: "New York",
    x_phone: "917 555 9876",
    x_project: "Bathroom, 45 Park Ave",
    x_project2: "Living room painting",
    x_project3: "Kitchen, tiles above countertop",
    x_project4: "Terrace",
    x_client2: "Peter Brown",
    x_client3: "Martha Davis",
    x_quote: "Bathroom, quote",
    x_room: "Bathroom",
    x_mat1: "Porcelain tiles 60×60 cm",
    x_mat2: "Tile adhesive",
    x_mat3: "Grout",
    x_other: "Transport",
    x_labour: "Tile laying",
    x_unit_pack: "box",
    x_unit_bag: "bag",
  },
  cs: {
    meta: "LiczMat Pro: nabídky z výsledků kalkulačky, klienti, kalendář, PDF s logem firmy a odkaz na nabídku pro klienta. Každý nový účet má 14 dní zdarma.",
    lead: "Nabídky, klienti a termíny u projektů, které počítáš v kalkulačkách.",
    buy: "Koupit LiczMat Pro",
    trial: "14 dní zdarma",
    f1_t: "Nabídka z kalkulačky",
    f1_d: "Materiály z projektu se samy dostanou do nabídky.",
    f2_t: "PDF s logem firmy",
    f2_d: "Údaje firmy zapíšeš jednou, v záložce Moje firma.",
    f3_t: "Odkaz pro klienta",
    f3_d: "Klient otevře nabídku v prohlížeči, bez účtu.",
    f4_t: "Také na Androidu",
    f4_d: "Klienti a nabídky jsou na účtu, takže je vidíš i v aplikaci.",
    k_client: "Klient",
    k_date: "Termín",
    s1_t: "Klient",
    s1_d: "Kontaktní údaje a poznámky u klienta.",
    s2_t: "Projekt",
    s2_d: "Výsledky z kalkulaček už jsou v projektu.",
    s3_t: "Nabídka",
    s3_d: "Dopíšeš práci, náklady, marži a DPH.",
    s4_t: "PDF nebo odkaz",
    s4_d: "Klient dostane hotovou nabídku.",
    q_h: "Nabídka se počítá z projektu",
    q_d: "Materiály a náklady přijdou z projektu. Ty dopíšeš práci, marži a DPH a součet se spočítá sám.",
    q_1: "Jednotkové ceny a hodnoty položek",
    q_2: "Práce a dodatečné náklady",
    q_3: "Marže a DPH",
    q_4: "PDF s údaji firmy a logem",
    c_h: "Klienti, historie a termíny",
    c_d: "U klienta vidíš jeho projekty, nabídky a historii. Termín projektu je hned v kalendáři.",
    c_1: "Kontaktní údaje a poznámky",
    c_2: "Projekty a nabídky klienta",
    c_3: "Historie spolupráce",
    c_4: "Termíny projektů v kalendáři",
    p_h: "Kolik to stojí",
    p_month: "Měsíčně",
    p_year: "Ročně",
    p_guest: "Bez účtu",
    p_free: "Účet zdarma",
    p_nofee: "bez poplatků",
    p_guest_1: "Všechny kalkulačky",
    p_guest_2: "Katalog materiálů",
    p_guest_3: "Převodník jednotek",
    p_free_1: "Všechno bez účtu",
    p_free_2: "Projekty a místnosti",
    p_free_3: "Uložené kalkulace",
    p_free_4: "Nákupní seznam bez cen",
    p_free_5: "Synchronizace s telefonem",
    p_pro_1: "Všechno z bezplatného účtu",
    p_pro_2: "Klienti a historie spolupráce",
    p_pro_3: "Nabídky s prací, marží a DPH",
    p_pro_4: "PDF s logem firmy",
    p_pro_5: "Odkaz na online nabídku",
    p_pro_6: "Ceny a náklady v projektech",
    p_pro_7: "Termíny",
    p_open_calc: "Otevřít kalkulačky",
    p_signup: "Vytvořit účet",
    p_trial_line: "nebo 14 dní zdarma, bez karty",
    p_pay_line: "Platba přes Stripe: karta, Apple Pay, Link nebo Klarna. Zrušíš, kdy chceš, a Pro funguje do konce zaplaceného období.",
    p_yours: "Máš LiczMat Pro. Plán a platby jsou ve tvém účtu.",
    p_account: "Můj účet",
    t_h: "Detailní srovnání",
    t_feature: "Funkce",
    g_count: "Počítání",
    g_projects: "Projekty",
    g_money: "Peníze",
    g_work: "Klienti a práce",
    g_docs: "Dokumenty",
    r_calcs: "Všechny kalkulačky",
    r_materials: "Katalog materiálů",
    r_converter: "Převodník jednotek",
    r_projects: "Projekty a místnosti",
    r_saved: "Uložené kalkulace",
    r_shopping: "Nákupní seznam bez cen",
    r_sync: "Synchronizace s telefonem",
    r_prices: "Jednotkové ceny a hodnoty",
    r_waste: "Náklady na prořez a součty",
    r_quotes: "Nabídky s marží a prací",
    r_vat: "DPH v nabídce",
    r_clients: "Klienti a kontaktní údaje",
    r_calendar: "Kalendář projektů",
    r_history: "Historie spolupráce",
    r_pdf: "PDF s logem firmy",
    r_link: "Odkaz na online nabídku",
    t_yes: "je",
    t_no: "není",
    b_h: "Než koupíš",
    b_1: "Zrušíš, kdy chceš. Pro funguje do konce zaplaceného období.",
    b_2: "Když Pro vyprší, nic se neztratí: klienti, nabídky a částky zůstanou na účtu a po obnovení se vrátí.",
    b_3: "Ceny jsou v 7 měnách. Měnu platby Stripe vybírá podle země, ze které platíš.",
    b_4: "Pro nevystavuje faktury a nevede sklad ani personalistiku. Kalendář neposílá upozornění.",
    x_firm: "Rekonstrukce Novák",
    x_firm_street: "Husova 15",
    x_firm_postal: "11000",
    x_firm_city: "Praha",
    x_firm_phone: "602 123 456",
    x_firm_email: "kancelar@rekonstrukce-novak.example",
    x_client: "Anna Svobodová",
    x_street: "Dlouhá 22",
    x_postal: "11000",
    x_city: "Praha",
    x_phone: "777 987 654",
    x_project: "Koupelna, Dlouhá 22",
    x_project2: "Malování obýváku",
    x_project3: "Kuchyně, dlažba nad linkou",
    x_project4: "Terasa",
    x_client2: "Petr Dvořák",
    x_client3: "Marta Černá",
    x_quote: "Koupelna, nabídka",
    x_room: "Koupelna",
    x_mat1: "Dlažba 60×60 cm",
    x_mat2: "Lepidlo na dlažbu",
    x_mat3: "Spárovací hmota",
    x_other: "Doprava",
    x_labour: "Pokládka dlažby",
    x_unit_pack: "bal.",
    x_unit_bag: "pyt.",
  },
  sk: {
    meta: "LiczMat Pro: ponuky z výsledkov kalkulačky, klienti, kalendár, PDF s logom firmy a odkaz na ponuku pre klienta. Každý nový účet má 14 dní zadarmo.",
    lead: "Ponuky, klienti a termíny pri projektoch, ktoré počítaš v kalkulačkách.",
    buy: "Kúpiť LiczMat Pro",
    trial: "14 dní zadarmo",
    f1_t: "Ponuka z kalkulačky",
    f1_d: "Materiály z projektu sa do ponuky pridajú samé.",
    f2_t: "PDF s logom firmy",
    f2_d: "Údaje firmy zapíšeš raz, v záložke Moja firma.",
    f3_t: "Odkaz pre klienta",
    f3_d: "Klient otvorí ponuku v prehliadači, bez účtu.",
    f4_t: "Aj na Androide",
    f4_d: "Klienti a ponuky sú na účte, takže ich vidíš aj v aplikácii.",
    k_client: "Klient",
    k_date: "Termín",
    s1_t: "Klient",
    s1_d: "Kontaktné údaje a poznámky pri klientovi.",
    s2_t: "Projekt",
    s2_d: "Výsledky z kalkulačiek už sú v projekte.",
    s3_t: "Ponuka",
    s3_d: "Dopíšeš prácu, náklady, maržu a DPH.",
    s4_t: "PDF alebo odkaz",
    s4_d: "Klient dostane hotovú ponuku.",
    q_h: "Ponuka sa počíta z projektu",
    q_d: "Materiály a náklady prídu z projektu. Ty dopíšeš prácu, maržu a DPH a súčet sa spočíta sám.",
    q_1: "Jednotkové ceny a hodnoty položiek",
    q_2: "Práca a dodatočné náklady",
    q_3: "Marža a DPH",
    q_4: "PDF s údajmi firmy a logom",
    c_h: "Klienti, história a termíny",
    c_d: "Pri klientovi vidíš jeho projekty, ponuky a históriu. Termín projektu je hneď v kalendári.",
    c_1: "Kontaktné údaje a poznámky",
    c_2: "Projekty a ponuky klienta",
    c_3: "História spolupráce",
    c_4: "Termíny projektov v kalendári",
    p_h: "Koľko to stojí",
    p_month: "Mesačne",
    p_year: "Ročne",
    p_guest: "Bez účtu",
    p_free: "Účet zadarmo",
    p_nofee: "bez poplatkov",
    p_guest_1: "Všetky kalkulačky",
    p_guest_2: "Katalóg materiálov",
    p_guest_3: "Prevodník jednotiek",
    p_free_1: "Všetko bez účtu",
    p_free_2: "Projekty a miestnosti",
    p_free_3: "Uložené kalkulácie",
    p_free_4: "Nákupný zoznam bez cien",
    p_free_5: "Synchronizácia s telefónom",
    p_pro_1: "Všetko z bezplatného účtu",
    p_pro_2: "Klienti a história spolupráce",
    p_pro_3: "Ponuky s prácou, maržou a DPH",
    p_pro_4: "PDF s logom firmy",
    p_pro_5: "Odkaz na online ponuku",
    p_pro_6: "Ceny a náklady v projektoch",
    p_pro_7: "Termíny",
    p_open_calc: "Otvoriť kalkulačky",
    p_signup: "Vytvoriť účet",
    p_trial_line: "alebo 14 dní zadarmo, bez karty",
    p_pay_line: "Platba cez Stripe: karta, Apple Pay, Link alebo Klarna. Zrušíš kedy chceš a Pro funguje do konca zaplateného obdobia.",
    p_yours: "Máš LiczMat Pro. Plán a platby sú vo tvojom účte.",
    p_account: "Môj účet",
    t_h: "Detailné porovnanie",
    t_feature: "Funkcia",
    g_count: "Počítanie",
    g_projects: "Projekty",
    g_money: "Peniaze",
    g_work: "Klienti a práca",
    g_docs: "Dokumenty",
    r_calcs: "Všetky kalkulačky",
    r_materials: "Katalóg materiálov",
    r_converter: "Prevodník jednotiek",
    r_projects: "Projekty a miestnosti",
    r_saved: "Uložené kalkulácie",
    r_shopping: "Nákupný zoznam bez cien",
    r_sync: "Synchronizácia s telefónom",
    r_prices: "Jednotkové ceny a hodnoty",
    r_waste: "Náklady na prerez a súčty",
    r_quotes: "Ponuky s maržou a prácou",
    r_vat: "DPH v ponuke",
    r_clients: "Klienti a kontaktné údaje",
    r_calendar: "Kalendár projektov",
    r_history: "História spolupráce",
    r_pdf: "PDF s logom firmy",
    r_link: "Odkaz na online ponuku",
    t_yes: "je",
    t_no: "nie je",
    b_h: "Kým kúpiš",
    b_1: "Zrušíš kedy chceš. Pro funguje do konca zaplateného obdobia.",
    b_2: "Keď Pro vyprší, nič sa nestratí: klienti, ponuky a sumy ostanú na účte a vrátia sa po obnove.",
    b_3: "Ceny sú v 7 menách. Menu platby Stripe vyberá podľa krajiny, z ktorej platíš.",
    b_4: "Pro nevystavuje faktúry a nevedie sklad ani personalistiku. Kalendár neposiela upozornenia.",
    x_firm: "Rekonštrukcie Kováč",
    x_firm_street: "Hlavná 15",
    x_firm_postal: "81101",
    x_firm_city: "Bratislava",
    x_firm_phone: "0902 123 456",
    x_firm_email: "kancelaria@rekonstrukcie-kovac.example",
    x_client: "Anna Nováková",
    x_street: "Krížna 22",
    x_postal: "81107",
    x_city: "Bratislava",
    x_phone: "0911 987 654",
    x_project: "Kúpeľňa, Krížna 22",
    x_project2: "Maľovanie obývačky",
    x_project3: "Kuchyňa, dlažba nad linkou",
    x_project4: "Terasa",
    x_client2: "Peter Varga",
    x_client3: "Marta Balážová",
    x_quote: "Kúpeľňa, ponuka",
    x_room: "Kúpeľňa",
    x_mat1: "Dlažba 60×60 cm",
    x_mat2: "Lepidlo na dlažbu",
    x_mat3: "Škárovacia hmota",
    x_other: "Doprava",
    x_labour: "Pokládka dlažby",
    x_unit_pack: "bal.",
    x_unit_bag: "vrece",
  },
  ro: {
    meta: "LiczMat Pro: oferte din rezultatele calculatorului, clienți, calendar, PDF cu logoul firmei și link către ofertă pentru client. Fiecare cont nou are 14 zile gratuit.",
    lead: "Oferte, clienți și termene pentru proiectele pe care le calculezi în calculatoare.",
    buy: "Cumpără LiczMat Pro",
    trial: "14 zile gratuit",
    f1_t: "Ofertă din calculator",
    f1_d: "Materialele din proiect ajung singure în ofertă.",
    f2_t: "PDF cu logoul firmei",
    f2_d: "Datele firmei le introduci o dată, în tabul Compania mea.",
    f3_t: "Link pentru client",
    f3_d: "Clientul deschide oferta în browser, fără cont.",
    f4_t: "Și pe Android",
    f4_d: "Clienții și ofertele sunt în cont, deci le vezi și în aplicație.",
    k_client: "Client",
    k_date: "Termen",
    s1_t: "Client",
    s1_d: "Date de contact și notițe la client.",
    s2_t: "Proiect",
    s2_d: "Rezultatele din calculatoare sunt deja în proiect.",
    s3_t: "Ofertă",
    s3_d: "Adaugi manoperă, costuri, marjă și TVA.",
    s4_t: "PDF sau link",
    s4_d: "Clientul primește oferta gata făcută.",
    q_h: "Oferta se calculează din proiect",
    q_d: "Materialele și costurile vin din proiect. Tu adaugi manopera, marja și TVA, iar suma se calculează singură.",
    q_1: "Prețuri unitare și valorile pozițiilor",
    q_2: "Manoperă și costuri suplimentare",
    q_3: "Marjă și TVA",
    q_4: "PDF cu datele firmei și logoul acesteia",
    c_h: "Clienți, istoric și termene",
    c_d: "La client vezi proiectele, ofertele și istoricul lui. Termenul proiectului intră direct în calendar.",
    c_1: "Date de contact și notițe",
    c_2: "Proiectele și ofertele clientului",
    c_3: "Istoricul colaborării",
    c_4: "Termenele proiectelor în calendar",
    p_h: "Cât costă",
    p_month: "Lunar",
    p_year: "Anual",
    p_guest: "Fără cont",
    p_free: "Cont gratuit",
    p_nofee: "fără taxe",
    p_guest_1: "Toate calculatoarele",
    p_guest_2: "Catalog de materiale",
    p_guest_3: "Convertor de unități",
    p_free_1: "Totul fără cont",
    p_free_2: "Proiecte și încăperi",
    p_free_3: "Calcule salvate",
    p_free_4: "Listă de cumpărături fără prețuri",
    p_free_5: "Sincronizare cu telefonul",
    p_pro_1: "Totul din contul gratuit",
    p_pro_2: "Clienți și istoricul colaborării",
    p_pro_3: "Oferte cu manoperă, marjă și TVA",
    p_pro_4: "PDF cu logoul firmei",
    p_pro_5: "Link către oferta online",
    p_pro_6: "Prețuri și costuri în proiecte",
    p_pro_7: "Termene",
    p_open_calc: "Deschide calculatoarele",
    p_signup: "Creează cont",
    p_trial_line: "sau 14 zile gratuit, fără card",
    p_pay_line: "Plata prin Stripe: card, Apple Pay, Link sau Klarna. Anulezi când vrei, iar Pro funcționează până la finalul perioadei plătite.",
    p_yours: "Ai LiczMat Pro. Planul și plățile sunt în contul tău.",
    p_account: "Contul meu",
    t_h: "Comparație detaliată",
    t_feature: "Funcție",
    g_count: "Calcul",
    g_projects: "Proiecte",
    g_money: "Bani",
    g_work: "Clienți și muncă",
    g_docs: "Documente",
    r_calcs: "Toate calculatoarele",
    r_materials: "Catalog de materiale",
    r_converter: "Convertor de unități",
    r_projects: "Proiecte și încăperi",
    r_saved: "Calcule salvate",
    r_shopping: "Listă de cumpărături fără prețuri",
    r_sync: "Sincronizare cu telefonul",
    r_prices: "Prețuri unitare și valori",
    r_waste: "Costul pierderilor și sume",
    r_quotes: "Oferte cu marjă și manoperă",
    r_vat: "TVA în ofertă",
    r_clients: "Clienți și date de contact",
    r_calendar: "Calendarul proiectelor",
    r_history: "Istoricul colaborării",
    r_pdf: "PDF cu logoul firmei",
    r_link: "Link către oferta online",
    t_yes: "este",
    t_no: "nu este",
    b_h: "Înainte de a cumpăra",
    b_1: "Anulezi când vrei. Pro funcționează până la finalul perioadei plătite.",
    b_2: "Când Pro expiră, nu se pierde nimic: clienții, ofertele și sumele rămân în cont și revin la reînnoire.",
    b_3: "Prețurile sunt în 7 valute. Stripe alege valuta de plată în funcție de țara din care plătești.",
    b_4: "Pro nu emite facturi și nu gestionează stocuri sau resurse umane. Calendarul nu trimite notificări.",
    x_firm: "Renovări Popescu",
    x_firm_street: "Strada Mare 15",
    x_firm_postal: "010011",
    x_firm_city: "București",
    x_firm_phone: "0722 123 456",
    x_firm_email: "birou@renovari-popescu.example",
    x_client: "Ana Radu",
    x_street: "Strada Lungă 22",
    x_postal: "020022",
    x_city: "București",
    x_phone: "0733 987 654",
    x_project: "Baie, Strada Lungă 22",
    x_project2: "Vopsire living",
    x_project3: "Bucătărie, gresie deasupra blatului",
    x_project4: "Terasă",
    x_client2: "Petre Dumitrescu",
    x_client3: "Marta Ionescu",
    x_quote: "Baie, ofertă",
    x_room: "Baie",
    x_mat1: "Gresie 60×60 cm",
    x_mat2: "Adeziv pentru gresie",
    x_mat3: "Chit",
    x_other: "Transport",
    x_labour: "Montare gresie",
    x_unit_pack: "cut.",
    x_unit_bag: "sac",
  },
  hr: {
    meta: "LiczMat Pro: ponude iz rezultata kalkulatora, klijenti, kalendar, PDF s logotipom tvrtke i poveznica na ponudu za klijenta. Svaki novi račun ima 14 dana besplatno.",
    lead: "Ponude, klijenti i rokovi na projektima koje računaš u kalkulatorima.",
    buy: "Kupi LiczMat Pro",
    trial: "14 dana besplatno",
    f1_t: "Ponuda iz kalkulatora",
    f1_d: "Materijali iz projekta sami ulaze u ponudu.",
    f2_t: "PDF s logotipom tvrtke",
    f2_d: "Podatke o tvrtki upisuješ jednom, u kartici Moja tvrtka.",
    f3_t: "Poveznica za klijenta",
    f3_d: "Klijent otvara ponudu u pregledniku, bez računa.",
    f4_t: "Također na Androidu",
    f4_d: "Klijenti i ponude su na računu, pa ih vidiš i u aplikaciji.",
    k_client: "Klijent",
    k_date: "Rok",
    s1_t: "Klijent",
    s1_d: "Kontaktni podaci i bilješke o klijentu.",
    s2_t: "Projekt",
    s2_d: "Rezultati iz kalkulatora već su u projektu.",
    s3_t: "Ponuda",
    s3_d: "Dopisuješ rad, troškove, maržu i PDV.",
    s4_t: "PDF ili poveznica",
    s4_d: "Klijent dobiva gotovu ponudu.",
    q_h: "Ponuda se računa iz projekta",
    q_d: "Materijali i troškovi dolaze iz projekta. Ti dopisuješ rad, maržu i PDV, a zbroj se računa sam.",
    q_1: "Jedinične cijene i vrijednosti stavki",
    q_2: "Rad i dodatni troškovi",
    q_3: "Marža i PDV",
    q_4: "PDF s podacima tvrtke i logotipom",
    c_h: "Klijenti, povijest i rokovi",
    c_d: "Uz klijenta vidiš njegove projekte, ponude i povijest. Rok projekta odmah stoji u kalendaru.",
    c_1: "Kontakt podaci i bilješke",
    c_2: "Projekti i ponude klijenta",
    c_3: "Povijest suradnje",
    c_4: "Rokovi projekata u kalendaru",
    p_h: "Koliko košta",
    p_month: "Mjesečno",
    p_year: "Godišnje",
    p_guest: "Bez računa",
    p_free: "Besplatan račun",
    p_nofee: "bez naknada",
    p_guest_1: "Svi kalkulatori",
    p_guest_2: "Katalog materijala",
    p_guest_3: "Pretvarač jedinica",
    p_free_1: "Sve bez računa",
    p_free_2: "Projekti i prostorije",
    p_free_3: "Spremljeni izračuni",
    p_free_4: "Popis za kupnju bez cijena",
    p_free_5: "Sinkronizacija s telefonom",
    p_pro_1: "Sve s besplatnog računa",
    p_pro_2: "Klijenti i povijest suradnje",
    p_pro_3: "Ponude s radom, maržom i PDV-om",
    p_pro_4: "PDF s logotipom tvrtke",
    p_pro_5: "Poveznica na online ponudu",
    p_pro_6: "Cijene i troškovi u projektima",
    p_pro_7: "Rokovi",
    p_open_calc: "Otvori kalkulatore",
    p_signup: "Napravi račun",
    p_trial_line: "ili 14 dana besplatno, bez kartice",
    p_pay_line: "Plaćanje preko Stripea: kartica, Apple Pay, Link ili Klarna. Otkažeš kada želiš, a Pro radi do kraja plaćenog razdoblja.",
    p_yours: "Imaš LiczMat Pro. Plan i plaćanja su na tvom računu.",
    p_account: "Moj račun",
    t_h: "Detaljna usporedba",
    t_feature: "Funkcija",
    g_count: "Računanje",
    g_projects: "Projekti",
    g_money: "Novac",
    g_work: "Klijenti i rad",
    g_docs: "Dokumenti",
    r_calcs: "Svi kalkulatori",
    r_materials: "Katalog materijala",
    r_converter: "Pretvarač jedinica",
    r_projects: "Projekti i prostorije",
    r_saved: "Spremljeni izračuni",
    r_shopping: "Popis za kupnju bez cijena",
    r_sync: "Sinkronizacija s telefonom",
    r_prices: "Jedinične cijene i vrijednosti",
    r_waste: "Trošak otpada i zbrojevi",
    r_quotes: "Ponude s maržom i radom",
    r_vat: "PDV u ponudi",
    r_clients: "Klijenti i kontakt podaci",
    r_calendar: "Kalendar projekata",
    r_history: "Povijest suradnje",
    r_pdf: "PDF s logotipom tvrtke",
    r_link: "Poveznica na online ponudu",
    t_yes: "ima",
    t_no: "nema",
    b_h: "Prije nego što kupiš",
    b_1: "Otkažeš kada želiš. Pro radi do kraja plaćenog razdoblja.",
    b_2: "Kada Pro istekne, ništa se ne gubi: klijenti, ponude i iznosi ostaju na računu i vraćaju se nakon obnove.",
    b_3: "Cijene su u 7 valuta. Stripe bira valutu plaćanja prema zemlji iz koje plaćaš.",
    b_4: "Pro ne izdaje račune i ne vodi skladište ni kadrove. Kalendar ne šalje obavijesti.",
    x_firm: "Renovacije Horvat",
    x_firm_street: "Zagrebačka 15",
    x_firm_postal: "10000",
    x_firm_city: "Zagreb",
    x_firm_phone: "091 123 4567",
    x_firm_email: "ured@renovacije-horvat.example",
    x_client: "Ana Kovač",
    x_street: "Ilica 22",
    x_postal: "10000",
    x_city: "Zagreb",
    x_phone: "098 987 6543",
    x_project: "Kupaonica, Ilica 22",
    x_project2: "Bojanje dnevnog boravka",
    x_project3: "Kuhinja, pločice iznad pulta",
    x_project4: "Terasa",
    x_client2: "Petar Babić",
    x_client3: "Marta Jurić",
    x_quote: "Kupaonica, ponuda",
    x_room: "Kupaonica",
    x_mat1: "Pločice 60×60 cm",
    x_mat2: "Ljepilo za pločice",
    x_mat3: "Fuga",
    x_other: "Prijevoz",
    x_labour: "Postavljanje pločica",
    x_unit_pack: "pak.",
    x_unit_bag: "vreća",
  },
  sr: {
    meta: "LiczMat Pro: ponude iz rezultata kalkulatora, klijenti, kalendar, PDF sa logotipom firme i link ka ponudi za klijenta. Svaki novi nalog ima 14 dana besplatno.",
    lead: "Ponude, klijenti i rokovi na projektima koje računaš u kalkulatorima.",
    buy: "Kupi LiczMat Pro",
    trial: "14 dana besplatno",
    f1_t: "Ponuda iz kalkulatora",
    f1_d: "Materijali iz projekta sami ulaze u ponudu.",
    f2_t: "PDF sa logotipom firme",
    f2_d: "Podatke o firmi upisuješ jednom, u kartici Moja firma.",
    f3_t: "Link za klijenta",
    f3_d: "Klijent otvara ponudu u pregledaču, bez naloga.",
    f4_t: "Takođe na Androidu",
    f4_d: "Klijenti i ponude su na nalogu, pa ih vidiš i u aplikaciji.",
    k_client: "Klijent",
    k_date: "Rok",
    s1_t: "Klijent",
    s1_d: "Kontakt podaci i beleške o klijentu.",
    s2_t: "Projekat",
    s2_d: "Rezultati iz kalkulatora su već u projektu.",
    s3_t: "Ponuda",
    s3_d: "Dopisuješ rad, troškove, maržu i PDV.",
    s4_t: "PDF ili link",
    s4_d: "Klijent dobija gotovu ponudu.",
    q_h: "Ponuda se računa iz projekta",
    q_d: "Materijali i troškovi dolaze iz projekta. Ti dopisuješ rad, maržu i PDV, a zbir se računa sam.",
    q_1: "Jedinične cene i vrednosti stavki",
    q_2: "Rad i dodatni troškovi",
    q_3: "Marža i PDV",
    q_4: "PDF sa podacima firme i logotipom",
    c_h: "Klijenti, istorija i rokovi",
    c_d: "Uz klijenta vidiš njegove projekte, ponude i istoriju. Rok projekta odmah stoji u kalendaru.",
    c_1: "Kontakt podaci i beleške",
    c_2: "Projekti i ponude klijenta",
    c_3: "Istorija saradnje",
    c_4: "Rokovi projekata u kalendaru",
    p_h: "Koliko košta",
    p_month: "Mesečno",
    p_year: "Godišnje",
    p_guest: "Bez naloga",
    p_free: "Besplatan nalog",
    p_nofee: "bez naknada",
    p_guest_1: "Svi kalkulatori",
    p_guest_2: "Katalog materijala",
    p_guest_3: "Pretvarač jedinica",
    p_free_1: "Sve bez naloga",
    p_free_2: "Projekti i prostorije",
    p_free_3: "Sačuvani proračuni",
    p_free_4: "Spisak za kupovinu bez cena",
    p_free_5: "Sinhronizacija sa telefonom",
    p_pro_1: "Sve sa besplatnog naloga",
    p_pro_2: "Klijenti i istorija saradnje",
    p_pro_3: "Ponude sa radom, maržom i PDV-om",
    p_pro_4: "PDF sa logotipom firme",
    p_pro_5: "Link ka online ponudi",
    p_pro_6: "Cene i troškovi u projektima",
    p_pro_7: "Rokovi",
    p_open_calc: "Otvori kalkulatore",
    p_signup: "Napravi nalog",
    p_trial_line: "ili 14 dana besplatno, bez kartice",
    p_pay_line: "Plaćanje preko Stripe-a: kartica, Apple Pay, Link ili Klarna. Otkažeš kada želiš, a Pro radi do kraja plaćenog perioda.",
    p_yours: "Imaš LiczMat Pro. Plan i plaćanja su na tvom nalogu.",
    p_account: "Moj nalog",
    t_h: "Detaljno poređenje",
    t_feature: "Funkcija",
    g_count: "Računanje",
    g_projects: "Projekti",
    g_money: "Novac",
    g_work: "Klijenti i rad",
    g_docs: "Dokumenti",
    r_calcs: "Svi kalkulatori",
    r_materials: "Katalog materijala",
    r_converter: "Pretvarač jedinica",
    r_projects: "Projekti i prostorije",
    r_saved: "Sačuvani proračuni",
    r_shopping: "Spisak za kupovinu bez cena",
    r_sync: "Sinhronizacija sa telefonom",
    r_prices: "Jedinične cene i vrednosti",
    r_waste: "Trošak otpada i zbirovi",
    r_quotes: "Ponude sa maržom i radom",
    r_vat: "PDV u ponudi",
    r_clients: "Klijenti i kontakt podaci",
    r_calendar: "Kalendar projekata",
    r_history: "Istorija saradnje",
    r_pdf: "PDF sa logotipom firme",
    r_link: "Link ka online ponudi",
    t_yes: "ima",
    t_no: "nema",
    b_h: "Pre nego što kupiš",
    b_1: "Otkažeš kada želiš. Pro radi do kraja plaćenog perioda.",
    b_2: "Kada Pro istekne, ništa se ne gubi: klijenti, ponude i iznosi ostaju na nalogu i vraćaju se nakon obnove.",
    b_3: "Cene su u 7 valuta. Stripe bira valutu plaćanja prema zemlji iz koje plaćaš.",
    b_4: "Pro ne izdaje račune i ne vodi magacin ni kadrove. Kalendar ne šalje obaveštenja.",
    x_firm: "Renovacije Jovanović",
    x_firm_street: "Kneza Miloša 15",
    x_firm_postal: "11000",
    x_firm_city: "Beograd",
    x_firm_phone: "060 123 4567",
    x_firm_email: "kancelarija@renovacije-jovanovic.example",
    x_client: "Ana Petrović",
    x_street: "Bulevar kralja Aleksandra 22",
    x_postal: "11000",
    x_city: "Beograd",
    x_phone: "064 987 6543",
    x_project: "Kupatilo, Bulevar kralja Aleksandra 22",
    x_project2: "Krečenje dnevne sobe",
    x_project3: "Kuhinja, pločice iznad pulta",
    x_project4: "Terasa",
    x_client2: "Petar Ilić",
    x_client3: "Marta Đorđević",
    x_quote: "Kupatilo, ponuda",
    x_room: "Kupatilo",
    x_mat1: "Pločice 60×60 cm",
    x_mat2: "Lepak za pločice",
    x_mat3: "Fuga",
    x_other: "Prevoz",
    x_labour: "Postavljanje pločica",
    x_unit_pack: "pak.",
    x_unit_bag: "vreća",
  },
  it: {
    meta: "LiczMat Pro: preventivi dai risultati del calcolatore, clienti, calendario, PDF con il logo dell'azienda e link al preventivo per il cliente. Ogni nuovo account ha 14 giorni gratis.",
    lead: "Preventivi, clienti e scadenze per i progetti che calcoli nei calcolatori.",
    buy: "Acquista LiczMat Pro",
    trial: "14 giorni gratis",
    f1_t: "Preventivo dal calcolatore",
    f1_d: "I materiali del progetto vengono inseriti automaticamente nel preventivo.",
    f2_t: "PDF con logo dell'azienda",
    f2_d: "Inserisci i dati dell'azienda una volta sola, nella scheda La mia azienda.",
    f3_t: "Link per il cliente",
    f3_d: "Il cliente apre il preventivo nel browser, senza account.",
    f4_t: "Anche su Android",
    f4_d: "Clienti e preventivi sono nell'account, così li vedi anche nell'app.",
    k_client: "Cliente",
    k_date: "Scadenza",
    s1_t: "Cliente",
    s1_d: "Dati di contatto e note sul cliente.",
    s2_t: "Progetto",
    s2_d: "I risultati dei calcolatori sono già nel progetto.",
    s3_t: "Preventivo",
    s3_d: "Aggiungi manodopera, costi, margine e IVA.",
    s4_t: "PDF o link",
    s4_d: "Il cliente riceve il preventivo finito.",
    q_h: "Il preventivo si calcola dal progetto",
    q_d: "Materiali e costi provengono dal progetto. Tu aggiungi manodopera, margine e IVA, e il totale si calcola da solo.",
    q_1: "Prezzi unitari e valori delle voci",
    q_2: "Manodopera e costi aggiuntivi",
    q_3: "Margine e IVA",
    q_4: "PDF con dati dell'azienda e logo",
    c_h: "Clienti, cronologia e scadenze",
    c_d: "Nella scheda del cliente trovi i suoi progetti, i preventivi e la cronologia. La scadenza del progetto compare subito nel calendario.",
    c_1: "Dati di contatto e note",
    c_2: "Progetti e preventivi del cliente",
    c_3: "Cronologia della collaborazione",
    c_4: "Scadenze dei progetti nel calendario",
    p_h: "Quanto costa",
    p_month: "Mensile",
    p_year: "Annuale",
    p_guest: "Senza account",
    p_free: "Account gratuito",
    p_nofee: "senza commissioni",
    p_guest_1: "Tutti i calcolatori",
    p_guest_2: "Catalogo dei materiali",
    p_guest_3: "Convertitore di unità",
    p_free_1: "Tutto senza account",
    p_free_2: "Progetti e stanze",
    p_free_3: "Calcoli salvati",
    p_free_4: "Lista della spesa senza prezzi",
    p_free_5: "Sincronizzazione con il telefono",
    p_pro_1: "Tutto dall'account gratuito",
    p_pro_2: "Clienti e cronologia della collaborazione",
    p_pro_3: "Preventivi con manodopera, margine e IVA",
    p_pro_4: "PDF con logo dell'azienda",
    p_pro_5: "Link al preventivo online",
    p_pro_6: "Prezzi e costi nei progetti",
    p_pro_7: "Scadenze",
    p_open_calc: "Apri i calcolatori",
    p_signup: "Crea account",
    p_trial_line: "oppure 14 giorni gratis, senza carta",
    p_pay_line: "Pagamento tramite Stripe: carta, Apple Pay, Link o Klarna. Annulli quando vuoi, e Pro funziona fino alla fine del periodo pagato.",
    p_yours: "Hai LiczMat Pro. Piano e pagamenti sono nel tuo account.",
    p_account: "Il mio account",
    t_h: "Confronto dettagliato",
    t_feature: "Funzione",
    g_count: "Calcolo",
    g_projects: "Progetti",
    g_money: "Soldi",
    g_work: "Clienti e lavoro",
    g_docs: "Documenti",
    r_calcs: "Tutti i calcolatori",
    r_materials: "Catalogo dei materiali",
    r_converter: "Convertitore di unità",
    r_projects: "Progetti e stanze",
    r_saved: "Calcoli salvati",
    r_shopping: "Lista della spesa senza prezzi",
    r_sync: "Sincronizzazione con il telefono",
    r_prices: "Prezzi unitari e valori",
    r_waste: "Costo dello scarto e totali",
    r_quotes: "Preventivi con margine e manodopera",
    r_vat: "IVA nel preventivo",
    r_clients: "Clienti e dati di contatto",
    r_calendar: "Calendario dei progetti",
    r_history: "Cronologia della collaborazione",
    r_pdf: "PDF con logo dell'azienda",
    r_link: "Link al preventivo online",
    t_yes: "c'è",
    t_no: "non c'è",
    b_h: "Prima di acquistare",
    b_1: "Annulli quando vuoi. Pro funziona fino alla fine del periodo pagato.",
    b_2: "Quando Pro scade, non perdi nulla: clienti, preventivi e importi restano nell'account e tornano disponibili dopo il rinnovo.",
    b_3: "I prezzi sono in 7 valute. Stripe sceglie la valuta di pagamento in base al paese da cui paghi.",
    b_4: "Pro non emette fatture e non gestisce il magazzino o le risorse umane. Il calendario non invia notifiche.",
    x_firm: "Ristrutturazioni Rossi",
    x_firm_street: "Via Roma 15",
    x_firm_postal: "00184",
    x_firm_city: "Roma",
    x_firm_phone: "320 123 4567",
    x_firm_email: "ufficio@ristrutturazioni-rossi.example",
    x_client: "Anna Bianchi",
    x_street: "Via Milano 22",
    x_postal: "00185",
    x_city: "Roma",
    x_phone: "333 987 6543",
    x_project: "Bagno, Via Milano 22",
    x_project2: "Pittura soggiorno",
    x_project3: "Cucina, piastrelle sopra il top",
    x_project4: "Terrazza",
    x_client2: "Pietro Verdi",
    x_client3: "Marta Colombo",
    x_quote: "Bagno, preventivo",
    x_room: "Bagno",
    x_mat1: "Gres porcellanato 60×60 cm",
    x_mat2: "Colla per piastrelle",
    x_mat3: "Stucco",
    x_other: "Trasporto",
    x_labour: "Posa piastrelle",
    x_unit_pack: "conf.",
    x_unit_bag: "sacco",
  },
  nl: {
    meta: "LiczMat Pro: offertes op basis van rekenresultaten, klanten, planning, een PDF met bedrijfslogo en een offertelink voor de klant. Elk nieuw account krijgt 14 dagen gratis.",
    lead: "Offertes, klanten en deadlines voor projecten die je met de rekenmachines berekent.",
    buy: "Koop LiczMat Pro",
    trial: "14 dagen gratis",
    f1_t: "Offerte uit de rekenmachine",
    f1_d: "Materialen uit het project belanden vanzelf in de offerte.",
    f2_t: "PDF met bedrijfslogo",
    f2_d: "Je vult je bedrijfsgegevens één keer in, op het tabblad Mijn bedrijf.",
    f3_t: "Link voor de klant",
    f3_d: "De klant opent de offerte in de browser, zonder account.",
    f4_t: "Ook op Android",
    f4_d: "Klanten en offertes staan in het account, dus je ziet ze ook in de app.",
    k_client: "Klant",
    k_date: "Deadline",
    s1_t: "Klant",
    s1_d: "Contactgegevens en notities bij de klant.",
    s2_t: "Project",
    s2_d: "Resultaten uit de rekenmachines staan al in het project.",
    s3_t: "Offerte",
    s3_d: "Je voegt arbeid, kosten, marge en btw toe.",
    s4_t: "PDF of link",
    s4_d: "De klant krijgt een kant-en-klare offerte.",
    q_h: "De offerte berekent zichzelf uit het project",
    q_d: "Materialen en kosten komen uit het project. Jij voegt arbeid, marge en btw toe, en het totaal wordt vanzelf berekend.",
    q_1: "Stuksprijzen en waarden van items",
    q_2: "Arbeid en extra kosten",
    q_3: "Marge en btw",
    q_4: "PDF met bedrijfsgegevens en logo",
    c_h: "Klanten, geschiedenis en planning",
    c_d: "Bij de klant zie je zijn projecten, offertes en geschiedenis. De deadline van het project staat direct in de kalender.",
    c_1: "Contactgegevens en notities",
    c_2: "Projecten en offertes van de klant",
    c_3: "Samenwerkingsgeschiedenis",
    c_4: "Projectdeadlines in de kalender",
    p_h: "Wat het kost",
    p_month: "Maandelijks",
    p_year: "Jaarlijks",
    p_guest: "Zonder account",
    p_free: "Gratis account",
    p_nofee: "zonder kosten",
    p_guest_1: "Alle rekenmachines",
    p_guest_2: "Materialencatalogus",
    p_guest_3: "Eenhedenomzetter",
    p_free_1: "Alles zonder account",
    p_free_2: "Projecten en kamers",
    p_free_3: "Opgeslagen berekeningen",
    p_free_4: "Boodschappenlijst zonder prijzen",
    p_free_5: "Synchronisatie met telefoon",
    p_pro_1: "Alles uit het gratis account",
    p_pro_2: "Klanten en samenwerkingsgeschiedenis",
    p_pro_3: "Offertes met arbeid, marge en btw",
    p_pro_4: "PDF met bedrijfslogo",
    p_pro_5: "Link naar online offerte",
    p_pro_6: "Prijzen en kosten in projecten",
    p_pro_7: "Planning",
    p_open_calc: "Open de rekenmachines",
    p_signup: "Account aanmaken",
    p_trial_line: "of 14 dagen gratis, zonder kaart",
    p_pay_line: "Betaling via Stripe: kaart, Apple Pay, Link of Klarna. Je annuleert wanneer je wilt, en Pro werkt tot het einde van de betaalde periode.",
    p_yours: "Je hebt LiczMat Pro. Abonnement en betalingen staan in je account.",
    p_account: "Mijn account",
    t_h: "Gedetailleerde vergelijking",
    t_feature: "Functie",
    g_count: "Berekenen",
    g_projects: "Projecten",
    g_money: "Geld",
    g_work: "Klanten en werk",
    g_docs: "Documenten",
    r_calcs: "Alle rekenmachines",
    r_materials: "Materialencatalogus",
    r_converter: "Eenhedenomzetter",
    r_projects: "Projecten en kamers",
    r_saved: "Opgeslagen berekeningen",
    r_shopping: "Boodschappenlijst zonder prijzen",
    r_sync: "Synchronisatie met telefoon",
    r_prices: "Stuksprijzen en waarden",
    r_waste: "Snijverlieskosten en totalen",
    r_quotes: "Offertes met marge en arbeid",
    r_vat: "btw in de offerte",
    r_clients: "Klanten en contactgegevens",
    r_calendar: "Projectkalender",
    r_history: "Samenwerkingsgeschiedenis",
    r_pdf: "PDF met bedrijfslogo",
    r_link: "Link naar online offerte",
    t_yes: "is er",
    t_no: "is er niet",
    b_h: "Voordat je koopt",
    b_1: "Je annuleert wanneer je wilt. Pro werkt tot het einde van de betaalde periode.",
    b_2: "Wanneer Pro verloopt, gaat er niets verloren: klanten, offertes en bedragen blijven in je account en komen terug na vernieuwing.",
    b_3: "Prijzen zijn in 7 valuta's. Stripe kiest de betalingsvaluta op basis van het land waaruit je betaalt.",
    b_4: "Pro geeft geen facturen uit en beheert geen voorraad of HR. De kalender stuurt geen meldingen.",
    x_firm: "Renovaties De Jong",
    x_firm_street: "Kerkstraat 15",
    x_firm_postal: "1017 AB",
    x_firm_city: "Amsterdam",
    x_firm_phone: "06 12345678",
    x_firm_email: "kantoor@renovaties-dejong.example",
    x_client: "Anna Visser",
    x_street: "Hoofdstraat 22",
    x_postal: "1071 CA",
    x_city: "Amsterdam",
    x_phone: "06 98765432",
    x_project: "Badkamer, Hoofdstraat 22",
    x_project2: "Woonkamer schilderen",
    x_project3: "Keuken, tegels boven aanrecht",
    x_project4: "Terras",
    x_client2: "Pieter Bakker",
    x_client3: "Marta Smit",
    x_quote: "Badkamer, offerte",
    x_room: "Badkamer",
    x_mat1: "Tegels 60×60 cm",
    x_mat2: "Tegellijm",
    x_mat3: "Voegmiddel",
    x_other: "Vervoer",
    x_labour: "Tegels leggen",
    x_unit_pack: "pak",
    x_unit_bag: "zak",
  },
  es: {
    meta: "LiczMat Pro: presupuestos a partir de los resultados de la calculadora, clientes, calendario, PDF con el logo de la empresa y enlace al presupuesto para el cliente. Cada cuenta nueva tiene 14 días gratis.",
    lead: "Presupuestos, clientes y plazos en los proyectos que calculas en las calculadoras.",
    buy: "Comprar LiczMat Pro",
    trial: "14 días gratis",
    f1_t: "Presupuesto desde la calculadora",
    f1_d: "Los materiales del proyecto se añaden automáticamente al presupuesto.",
    f2_t: "PDF con el logo de la empresa",
    f2_d: "Ingresas los datos de la empresa una vez, en la pestaña Mi empresa.",
    f3_t: "Enlace para el cliente",
    f3_d: "El cliente abre el presupuesto en el navegador, sin cuenta.",
    f4_t: "También en Android",
    f4_d: "Los clientes y presupuestos están en la cuenta, así que también los ves en la app.",
    k_client: "Cliente",
    k_date: "Plazo",
    s1_t: "Cliente",
    s1_d: "Datos de contacto y notas del cliente.",
    s2_t: "Proyecto",
    s2_d: "Los resultados de las calculadoras ya están en el proyecto.",
    s3_t: "Presupuesto",
    s3_d: "Tú añades mano de obra, gastos, margen e IVA.",
    s4_t: "PDF o enlace",
    s4_d: "El cliente recibe el presupuesto listo.",
    q_h: "El presupuesto se calcula desde el proyecto",
    q_d: "Los materiales y costos vienen del proyecto. Tú añades mano de obra, margen e IVA, y la suma se calcula sola.",
    q_1: "Precios unitarios y valores de las partidas",
    q_2: "Mano de obra y gastos adicionales",
    q_3: "Margen e IVA",
    q_4: "PDF con datos de la empresa y logo",
    c_h: "Clientes, historial y plazos",
    c_d: "En el cliente ves sus proyectos, presupuestos e historial. El plazo del proyecto va directo al calendario.",
    c_1: "Datos de contacto y notas",
    c_2: "Proyectos y presupuestos del cliente",
    c_3: "Historial de colaboración",
    c_4: "Plazos de los proyectos en el calendario",
    p_h: "Cuánto cuesta",
    p_month: "Mensual",
    p_year: "Anual",
    p_guest: "Sin cuenta",
    p_free: "Cuenta gratis",
    p_nofee: "sin cargos",
    p_guest_1: "Todas las calculadoras",
    p_guest_2: "Catálogo de materiales",
    p_guest_3: "Convertidor de unidades",
    p_free_1: "Todo lo disponible sin cuenta",
    p_free_2: "Proyectos y habitaciones",
    p_free_3: "Cálculos guardados",
    p_free_4: "Lista de compras sin precios",
    p_free_5: "Sincronización con el teléfono",
    p_pro_1: "Todo lo de la cuenta gratis",
    p_pro_2: "Clientes e historial de colaboración",
    p_pro_3: "Presupuestos con mano de obra, margen e IVA",
    p_pro_4: "PDF con el logo de la empresa",
    p_pro_5: "Enlace al presupuesto online",
    p_pro_6: "Precios y costos en proyectos",
    p_pro_7: "Plazos",
    p_open_calc: "Abrir calculadoras",
    p_signup: "Crear cuenta",
    p_trial_line: "o 14 días gratis, sin tarjeta",
    p_pay_line: "Pago a través de Stripe: tarjeta, Apple Pay, Link o Klarna. Cancelas cuando quieres, y Pro funciona hasta el final del período pagado.",
    p_yours: "Tienes LiczMat Pro. El plan y los pagos están en tu cuenta.",
    p_account: "Mi cuenta",
    t_h: "Comparación detallada",
    t_feature: "Función",
    g_count: "Cálculo",
    g_projects: "Proyectos",
    g_money: "Dinero",
    g_work: "Clientes y trabajo",
    g_docs: "Documentos",
    r_calcs: "Todas las calculadoras",
    r_materials: "Catálogo de materiales",
    r_converter: "Convertidor de unidades",
    r_projects: "Proyectos y habitaciones",
    r_saved: "Cálculos guardados",
    r_shopping: "Lista de compras sin precios",
    r_sync: "Sincronización con el teléfono",
    r_prices: "Precios unitarios y valores",
    r_waste: "Costo de mermas y sumas",
    r_quotes: "Presupuestos con margen y mano de obra",
    r_vat: "IVA en el presupuesto",
    r_clients: "Clientes y datos de contacto",
    r_calendar: "Calendario de proyectos",
    r_history: "Historial de colaboración",
    r_pdf: "PDF con el logo de la empresa",
    r_link: "Enlace al presupuesto online",
    t_yes: "sí",
    t_no: "no",
    b_h: "Antes de comprar",
    b_1: "Cancelas cuando quieres. Pro funciona hasta el final del período pagado.",
    b_2: "Cuando Pro expira, no se pierde nada: los clientes, presupuestos e importes se quedan en la cuenta y vuelven tras renovar.",
    b_3: "Los precios están en 7 monedas. Stripe elige la moneda de pago según el país desde el que pagas.",
    b_4: "Pro no emite facturas y no gestiona inventario ni personal. El calendario no envía notificaciones.",
    x_firm: "Reformas García",
    x_firm_street: "Calle Mayor 15",
    x_firm_postal: "28013",
    x_firm_city: "Madrid",
    x_firm_phone: "600 123 456",
    x_firm_email: "oficina@reformas-garcia.example",
    x_client: "Ana Martínez",
    x_street: "Calle de Alcalá 22",
    x_postal: "28014",
    x_city: "Madrid",
    x_phone: "611 987 654",
    x_project: "Baño, Calle de Alcalá 22",
    x_project2: "Pintar salón",
    x_project3: "Cocina, azulejos sobre encimera",
    x_project4: "Terraza",
    x_client2: "Pedro López",
    x_client3: "Marta Sánchez",
    x_quote: "Baño, presupuesto",
    x_room: "Baño",
    x_mat1: "Azulejos porcelánicos 60×60 cm",
    x_mat2: "Cemento cola",
    x_mat3: "Lechada",
    x_other: "Transporte",
    x_labour: "Alicatado",
    x_unit_pack: "caja",
    x_unit_bag: "saco",
  },
  fr: {
    meta: "LiczMat Pro : devis à partir des résultats du calculateur, clients, calendrier, PDF avec le logo de l'entreprise et lien vers le devis pour le client. Chaque nouveau compte a 14 jours gratuits.",
    lead: "Devis, clients et échéances pour les projets dont tu calcules les matériaux.",
    buy: "Acheter LiczMat Pro",
    trial: "14 jours gratuits",
    f1_t: "Devis depuis le calculateur",
    f1_d: "Les matériaux du projet sont ajoutés automatiquement au devis.",
    f2_t: "PDF avec le logo de l'entreprise",
    f2_d: "Tu saisis les données de l'entreprise une seule fois, dans l'onglet Mon entreprise.",
    f3_t: "Lien pour le client",
    f3_d: "Le client ouvre le devis dans son navigateur, sans compte.",
    f4_t: "Aussi sur Android",
    f4_d: "Les clients et les devis sont sur le compte, donc tu les vois aussi dans l'application.",
    k_client: "Client",
    k_date: "Délai",
    s1_t: "Client",
    s1_d: "Coordonnées et notes du client.",
    s2_t: "Projet",
    s2_d: "Les résultats des calculateurs sont déjà dans le projet.",
    s3_t: "Devis",
    s3_d: "Tu ajoutes la main-d'œuvre, les frais, la marge et la TVA.",
    s4_t: "PDF ou lien",
    s4_d: "Le client reçoit le devis finalisé.",
    q_h: "Le devis se calcule depuis le projet",
    q_d: "Les matériaux et les coûts viennent du projet. Tu ajoutes la main-d'œuvre, la marge et la TVA, et le total se calcule tout seul.",
    q_1: "Prix unitaires et valeurs des postes",
    q_2: "Main-d'œuvre et frais supplémentaires",
    q_3: "Marge et TVA",
    q_4: "PDF avec données de l'entreprise et logo",
    c_h: "Clients, historique et échéances",
    c_d: "Chez le client, tu vois ses projets, ses devis et son historique. Le délai du projet est directement dans le calendrier.",
    c_1: "Coordonnées et notes",
    c_2: "Projets et devis du client",
    c_3: "Historique de collaboration",
    c_4: "Délais des projets dans le calendrier",
    p_h: "Combien ça coûte",
    p_month: "Par mois",
    p_year: "Par an",
    p_guest: "Sans compte",
    p_free: "Compte gratuit",
    p_nofee: "sans frais",
    p_guest_1: "Tous les calculateurs",
    p_guest_2: "Catalogue de matériaux",
    p_guest_3: "Convertisseur d'unités",
    p_free_1: "Tout ce qui est sans compte",
    p_free_2: "Projets et pièces",
    p_free_3: "Calculs enregistrés",
    p_free_4: "Liste de courses sans prix",
    p_free_5: "Synchronisation avec le téléphone",
    p_pro_1: "Tout ce qui est dans le compte gratuit",
    p_pro_2: "Clients et historique de collaboration",
    p_pro_3: "Devis avec main-d'œuvre, marge et TVA",
    p_pro_4: "PDF avec le logo de l'entreprise",
    p_pro_5: "Lien vers le devis en ligne",
    p_pro_6: "Prix et coûts dans les projets",
    p_pro_7: "Échéances",
    p_open_calc: "Ouvrir les calculateurs",
    p_signup: "Créer un compte",
    p_trial_line: "ou 14 jours gratuits, sans carte",
    p_pay_line: "Paiement via Stripe : carte, Apple Pay, Link ou Klarna. Tu annules quand tu veux, et Pro fonctionne jusqu'à la fin de la période payée.",
    p_yours: "Tu as LiczMat Pro. Le forfait et les paiements sont dans ton compte.",
    p_account: "Mon compte",
    t_h: "Comparaison détaillée",
    t_feature: "Fonctionnalité",
    g_count: "Calcul",
    g_projects: "Projets",
    g_money: "Argent",
    g_work: "Clients et travail",
    g_docs: "Documents",
    r_calcs: "Tous les calculateurs",
    r_materials: "Catalogue de matériaux",
    r_converter: "Convertisseur d'unités",
    r_projects: "Projets et pièces",
    r_saved: "Calculs enregistrés",
    r_shopping: "Liste de courses sans prix",
    r_sync: "Synchronisation avec le téléphone",
    r_prices: "Prix unitaires et valeurs",
    r_waste: "Coût des chutes et totaux",
    r_quotes: "Devis avec marge et main-d'œuvre",
    r_vat: "TVA dans le devis",
    r_clients: "Clients et coordonnées",
    r_calendar: "Calendrier des projets",
    r_history: "Historique de collaboration",
    r_pdf: "PDF avec le logo de l'entreprise",
    r_link: "Lien vers le devis en ligne",
    t_yes: "oui",
    t_no: "non",
    b_h: "Avant d'acheter",
    b_1: "Tu annules quand tu veux. Pro fonctionne jusqu'à la fin de la période payée.",
    b_2: "Quand Pro expire, rien n'est perdu : les clients, les devis et les montants restent sur le compte et reviennent après renouvellement.",
    b_3: "Les prix sont dans 7 devises. Stripe choisit la devise de paiement en fonction du pays d'où tu paies.",
    b_4: "Pro n'émet pas de factures et ne gère ni stock ni RH. Le calendrier n'envoie pas de notifications.",
    x_firm: "Rénovations Dubois",
    x_firm_street: "Rue de la Paix 15",
    x_firm_postal: "75002",
    x_firm_city: "Paris",
    x_firm_phone: "06 12 34 56 78",
    x_firm_email: "bureau@renovations-dubois.example",
    x_client: "Anne Martin",
    x_street: "Rue de Rivoli 22",
    x_postal: "75001",
    x_city: "Paris",
    x_phone: "06 98 76 54 32",
    x_project: "Salle de bain, Rue de Rivoli 22",
    x_project2: "Peinture du salon",
    x_project3: "Cuisine, carrelage au-dessus du plan de travail",
    x_project4: "Terrasse",
    x_client2: "Pierre Lefebvre",
    x_client3: "Marthe Bernard",
    x_quote: "Salle de bain, devis",
    x_room: "Salle de bain",
    x_mat1: "Carrelage 60×60 cm",
    x_mat2: "Colle à carrelage",
    x_mat3: "Joint",
    x_other: "Transport",
    x_labour: "Pose de carrelage",
    x_unit_pack: "boîte",
    x_unit_bag: "sac",
  },
};

export const PRO_COPY_KEYS = Object.keys(PRO_COPY.pl);
